import fs from 'node:fs'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'
const require=createRequire('F:/Projects/WorldBreaker/PlotWeave-kidnapped-qa/package.json'),{chromium}=require('playwright'),qa=new URL('./qa/',import.meta.url);fs.mkdirSync(qa,{recursive:true})
const path=name=>fileURLToPath(new URL(`./qa/${name}`,import.meta.url)),browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage(),errors=[],checks=[],views={}
page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});page.on('pageerror',e=>errors.push(`page: ${e.message}`))
const assert=(ok,label)=>{if(!ok)throw Error(label);checks.push(label)},text=async()=>(await page.locator('body').innerText()).replace(/\s+/g,' '),shot=async name=>page.screenshot({path:path(name),fullPage:true})
async function visit(name,file,need=[]){await page.getByRole('link',{name,exact:true}).click();await page.waitForTimeout(1200);const t=await text();for(const value of need)assert(t.includes(value),`${name} contains “${value}”`);views[name]=t.slice(0,4000);await shot(file);return t}
async function imageAudit(label){const result=await page.locator('img').evaluateAll(imgs=>imgs.map(i=>({src:i.getAttribute('src'),complete:i.complete,width:i.naturalWidth,height:i.naturalHeight}))),broken=result.filter(x=>!x.complete||!x.width||!x.height);assert(broken.length===0,`${label}: all ${result.length} rendered images loaded`);return result.length}
await page.goto('http://127.0.0.1:5174/',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Library'}).click();await page.getByRole('textbox',{name:/Search the library/}).fill('Kidnapped')
const card=page.getByRole('listitem').filter({hasText:'Kidnapped'}),cardText=await card.innerText();assert(cardText.includes('20 characters · 30 chapters · 90 scenes · 35 locations'),'Library card exposes canonical counts');assert(cardText.includes('73 original generated illustrations'),'Library card documents generated artwork');await shot('library-dialog.png')
await card.getByRole('button',{name:/Download/}).click();await page.waitForURL(/\/worlds\/kidnapped-world/,{timeout:30000});await page.waitForFunction(()=>document.body.innerText.includes('Reading mode is on'),null,{timeout:60000});await page.waitForTimeout(1500)
const opening=await text();assert(opening.includes('18 characters, 34 places and 10 items you have not met stay hidden'),'Opening dashboard reports spoiler-gated entities');assert(opening.includes('30 Timeline chapters')&&opening.includes('1 scene')&&opening.includes('2 Characters you have met so far'),'Opening dashboard counts are correct');await shot('opening-dashboard.png')
const openingCharacters=await visit('Characters','opening-characters.png',['Characters 2','David Balfour','Mr Campbell','18 characters not yet met']);assert(!openingCharacters.includes('Alan Breck Stewart'),'Alan remains hidden at the opening');assert(await imageAudit('Opening characters')>=2,'Opening character portraits render')
await visit('Read','opening-manuscript.png',['DEDICATION','MY DEAR CHARLES BAXTER','Chapter I'])
const openingMaps=await visit('Maps','opening-map.png',['MAP LAYERS 1','Scotland, 1751','LOCATIONS 1']);assert(!openingMaps.includes('Brig Covenant Appin'),'Future map layers remain hidden at the opening');await imageAudit('Opening map')
await visit('Items','opening-items.png',['Items','Mr Campbell’s Letter','David’s Purse']);await imageAudit('Opening items');await visit('Calendar','opening-calendar.png',['Calendar','1751']);await visit('Lore','opening-lore.png',['Source Edition','Extraction and Reconstruction','Editorial Chronology','Map Method']);await visit('Knowledge','opening-knowledge.png',['Knowledge']);await visit('Factions','opening-factions.png',['Factions'])
await page.getByRole('button',{name:/Ch\.1/}).click();await page.getByRole('button',{name:'Read to here'}).last().click();await page.getByRole('button',{name:'Read ahead'}).click();await page.waitForFunction(()=>document.body.innerText.includes('Ch.30 · Duty to the Hunted'));await page.getByRole('button',{name:'Next moment'}).click();await page.getByRole('button',{name:'Next moment'}).click();await page.waitForFunction(()=>document.body.innerText.includes('Ch.30 · Parting in Edinburgh'));await page.waitForTimeout(1000)
const finalDashboard=await visit('Dashboard','final-dashboard.png',['30 Timeline chapters','90 scenes','20 Characters','5 Maps','12 Items']);assert(!finalDashboard.includes('not yet met stay hidden'),'Final dashboard has no unrevealed-entity warning')
await visit('Timeline','final-timeline.png',['Chapter I','Chapter XXX']);await visit('Read','final-manuscript.png',['Chapter XXX','GOOD-BYE','Parting in Edinburgh'])
const finalCharacters=await visit('Characters','final-characters.png',['Characters 20','Alan Breck Stewart','Mr Rankeillor','Robin Oig']);assert(await imageAudit('Final characters')>=20,'All 20 character portraits render')
await visit('Items','final-items.png',['Items 12','Alan’s Sword','Alexander Balfour’s Will','Highland Pipes']);assert(await imageAudit('Final items')>=12,'All 12 item illustrations render')
await visit('Relations','final-relations.png',['Relations','David Balfour','Alan Breck Stewart']);await visit('Arc','final-arc.png',['Character Arc','David Balfour']);await visit('Lore','final-lore.png',['Source Edition','After the Jacobite Rising','Appin and the Forfeited Estates']);await visit('Factions','final-factions.png',['Crown Authorities','Appin Stewarts','Covenant Crew','Balfour Family']);await visit('Knowledge','final-knowledge.png',['Ebenezer paid to have David kidnapped','Alan uses the name Mr Thomson','Colin Campbell is called the Red Fox'])
await visit('Maps','final-map-house-of-shaws.png',['MAP LAYERS 5','CHARACTERS 20','ITEMS 12']);const layerNames=['Brig Covenant','Appin and the Highland Flight','Cluny’s Cage','House of Shaws','Scotland, 1751'],mapImages={}
for(const name of layerNames){await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(1200);await page.getByRole('button',{name,exact:true}).click({force:true});await page.waitForTimeout(1200);checks.push(`Map layer selected: ${name}`);mapImages[name]=await imageAudit(`Map ${name}`);await shot(`map-${name.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}.png`)}
await visit('Settings','settings-reading.png',['Reading mode']);const readingButton=page.getByRole('button',{name:'Turn off reading mode'});assert(await readingButton.count()===1,'Settings exposes the reading-mode control');await readingButton.evaluate(el=>el.click());await page.waitForTimeout(1200);assert(await page.getByRole('button',{name:'Turn on reading mode'}).count()===1,'Reading mode turns off');await page.goto('http://127.0.0.1:5174/#/worlds/kidnapped-world/corkboard');await page.waitForTimeout(1200);assert((await text()).includes('Corkboard'),'Corkboard renders with reading mode off');await shot('corkboard.png');await page.goto('http://127.0.0.1:5174/#/worlds/kidnapped-world/structure');await page.waitForTimeout(1200);assert((await text()).includes('Structure'),'Structure renders with reading mode off');await shot('structure.png')
assert(errors.length===0,'No browser console or page errors');const results={appCommit:'6ffabd9ade962abb64f5a718e3b0a8a3cbf4c7d3',source:'Library UI download',url:page.url(),checks,views,mapImages,consoleErrors:errors};fs.writeFileSync(path('app-results.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify({checks:checks.length,mapImages,consoleErrors:errors},null,2));await browser.close()
