import fs from 'node:fs'
import { maps, locations, characters as characterDefs, items as itemDefs } from './world-ledger.mjs'
import { chapterPlans, withCuts } from './story-ledger.mjs'
import { sourceSections, narrativeText, sourceEdition, sourceUrl, sourceFileSha256 as sourceSha256, normalize, countWords } from './source-text.mjs'

const W='kidnapped-world',T='kidnapped-timeline',now=Date.UTC(2026,8,21),ref=(k,v)=>`kid-${k}-${v}`,stamp={worldId:W,createdAt:now,updatedAt:now}
const coords={
 essendean:[1180,160],'cramond-road':[1050,350],'shaws-gate':[930,470],'queensferry':[895,520],'hawes-inn':[850,545],'covenant-gateway':[775,570],earraid:[420,440],torosay:[500,490],morvern:[555,570],corran:[575,670],ballachulish:[610,710],lettermore:[650,735],'house-fear':[670,770],'heather-rocks':[700,780],corrynakiegh:[700,800],'rannoch-moor':[760,750],'cluny-gateway':[805,795],balquhidder:[835,660],limekilns:[875,540],'rankeillor-office':[990,510],newhalls:[915,525],edinburgh:[1015,495],
 'shaws-yard':[800,410],'shaws-kitchen':[650,530],'shaws-stair':[930,560],'shaws-bedroom':[1010,670],'shaws-woods':[420,390],
 'covenant-deck':[765,835],'covenant-forecastle':[340,650],'covenant-cabin':[1120,650],'covenant-hold':[745,310],'covenant-galley':[1040,420],'round-house':[1220,510],
 'cluny-entrance':[360,470],'cluny-chamber':[930,520]
}
const blobs=[]
function image(kind,key,path){const url=`library/kidnapped/${path??`art/${kind}/${key}.png`}`,disk=new URL(`../../${url}`,import.meta.url);if(!fs.existsSync(disk))throw Error(`Missing artwork ${url}`);const b=fs.readFileSync(disk);if(b.toString('hex',0,8)!=='89504e470d0a1a0a')throw Error(`Not PNG ${url}`);const id=ref('image',`${kind}-${key}`);blobs.push({...stamp,id,mimeType:'image/png',url});return{id,width:b.readUInt32BE(16),height:b.readUInt32BE(20)}}
const mapLayers=maps.map(([key,parent,name,description],i)=>{const a=image('map',key,`maps/${key}.png`);return{...stamp,id:ref('map',key),name,description,parentMapId:parent?ref('map',parent):null,imageId:a.id,imageWidth:a.width,imageHeight:a.height,scalePixelsPerUnit:null,scaleUnit:null,levelGroupId:null,levelIndex:i,levelLabel:null}})
const gateway={'shaws-gate':'shaws','covenant-gateway':'covenant','ballachulish':'highlands','cluny-gateway':'cluny'}
const highland=new Set(['lettermore','house-fear','heather-rocks','corrynakiegh','rannoch-moor','cluny-gateway','balquhidder'])
const locationMarkers=locations.map(([key,map,name,description,link])=>{const layer=key==='ballachulish'?'scotland':(map==='highlands'||highland.has(key)?'highlands':map);return{...stamp,id:ref('loc',key),name,description,mapLayerId:ref('map',layer),linkedMapLayerId:link?ref('map',link):(gateway[key]?ref('map',gateway[key]):null),x:coords[key][0],y:coords[key][1],iconType:(link||gateway[key])?'building':'landmark',imageId:image('locations',key).id,tags:[],factionId:null}})
const characters=characterDefs.map(([key,name,aliases,description,color])=>({...stamp,id:ref('char',key),name,aliases,description,color,portraitImageId:image('characters',key).id,isAlive:!['ransome','shuan','colin'].includes(key),birthDate:null,tags:[]}))
const items=itemDefs.map(([key,name,description,iconType])=>({...stamp,id:ref('item',key),name,description,iconType,imageId:image('items',key).id,tags:[]}))
const chapters=[],events=[],sceneTexts=[],characterSnapshots=[],itemPlacements=[];let order=0,previous=0
const deathAt={ransome:[8,3],shuan:[10,3],colin:[17,2]}
const inventoryOwner={letter:'david',purse:'david','silver-button':'david',dirk:'david',memorandum:'david',bible:'ebenezer','belt-gold':'alan',sword:'alan',pistols:'alan','button-message':'david',will:'rankeillor',pipes:'robin'}
for(let ci=0;ci<sourceSections.length;ci++){
 const s=sourceSections[ci],plan=withCuts(s,chapterPlans[ci]),paras=s.text.split(/\n{2,}/),chapterId=ref('chapter',ci+1)
 chapters.push({...stamp,id:chapterId,timelineId:T,number:ci+1,title:s.title,synopsis:plan.map(x=>x.description).join(' '),notes:`Original source heading: ${s.sourceHeading}`,wordGoal:countWords(s.text)})
 for(let ei=0;ei<plan.length;ei++){
  const e=plan[ei],id=ref('event',`${ci+1}-${ei+1}`),day=ci*1.25+ei*.25
  const threadKeys=[ci<6?'inheritance':'',ci>=5&&ci<=12?'covenant':'',ci>=8&&ci<=28?'alan-david':'',ci>=16&&ci<=25?'flight':'',ci>=26?'homecoming':''].filter(Boolean)
  const motifKeys=[/law|proof|bargain|agreement|inherit|claim|witness/i.test(e.title+' '+e.description)?'law-honour':'',/road|cross|flight|journey|route|pass/i.test(e.title+' '+e.description)?'roads':'',/gold|money|purse|payment/i.test(e.title+' '+e.description)?'money':'',/name|message|letter|token|button/i.test(e.title+' '+e.description)?'tokens':''].filter(Boolean)
  events.push({...stamp,id,chapterId,timelineId:T,title:e.title,description:e.description,locationMarkerId:ref('loc',e.location),involvedCharacterIds:e.cast.map(k=>ref('char',k)),mentionedCharacterIds:[],involvedItemIds:e.items.map(k=>ref('item',k)),threadIds:threadKeys.map(k=>ref('thread',k)),motifIds:motifKeys.map(k=>ref('motif',k)),sortOrder:order++,travelDays:Math.max(0,day-previous),inWorldTime:day,tension:e.tension,tags:[],structureBeat:null,status:'complete',povCharacterId:ref('char','david'),isFlashback:false});previous=day
  const text=paras.slice(e.cut,plan[ei+1]?.cut??paras.length).join('\n\n');sceneTexts.push({...stamp,id:ref('scene',`${ci+1}-${ei+1}`),eventId:id,text,wordCount:countWords(text)})
  e.cast.forEach((key,i)=>{const loc=locationMarkers.find(x=>x.id===ref('loc',e.location)),death=deathAt[key],alive=!death||ci+1<death[0]||(ci+1===death[0]&&ei+1<death[1]);const inv=e.items.filter(x=>inventoryOwner[x]===key);characterSnapshots.push({...stamp,id:ref('snapshot',`${ci+1}-${ei+1}-${key}`),characterId:ref('char',key),eventId:id,isAlive:alive,currentLocationMarkerId:loc.id,currentMapLayerId:loc.mapLayerId,inventoryItemIds:inv.map(k=>ref('item',k)),inventoryNotes:inv.length?`Carries or uses ${inv.map(k=>itemDefs.find(x=>x[0]===k)[1]).join(', ')}.`:'',travelModeId:null,sortKey:(ci+1)+(ei+1)/100,statusNotes:`${characterDefs.find(x=>x[0]===key)[1]} ${statusFor(key,e.title,e.description,i)}.`})})
  e.items.forEach((key,i)=>itemPlacements.push({...stamp,id:ref('placement',`${ci+1}-${ei+1}-${key}`),itemId:ref('item',key),eventId:id,locationMarkerId:ref('loc',e.location),sortKey:i,notes:`Present during “${e.title}”.`}))
 }
}
function statusFor(key,title,desc,i){const verbs={david:'narrates and endures',alan:'acts with Highland daring during',ebenezer:'protects his secret during',hoseason:'asserts a captain’s authority during',riach:'balances conscience and obedience during',rankeillor:'tests evidence during',campbell:'guides David during',ransome:'serves under fear during',shuan:'brings dangerous volatility to',james:'weighs clan duty during',cluny:'offers outlaw hospitality during',robin:'defends clan honour during',colin:'represents Crown authority during'};return `${verbs[key]??'takes a distinct part in'} “${title}”${i?`, where ${desc.charAt(0).toLowerCase()+desc.slice(1)}`:''}`}
const event=(c,e=1)=>ref('event',`${c}-${e}`)
const plotThreads=[['inheritance','The House of Shaws','David’s journey begins with a sealed letter and the unanswered question of his birthright.'],['covenant','The Covenant','Kidnapping and shipboard violence carry David far from the legal claim he hoped to settle.'],['alan-david','David and Alan','A Lowland Whig and Highland Jacobite build a friendship across danger and disagreement.'],['flight','The Flight in the Heather','The Appin murder turns travellers into hunted suspects crossing the Highlands.'],['homecoming','The Road Home','Evidence, friendship, and legal strategy bring David back to Shaws.']].map(([k,name,description])=>({...stamp,id:ref('thread',k),name,description,color:'#6f6d54',status:'complete',tags:[]}))
const motifs=[['law-honour','Law and Honour','Formal evidence and personal honour offer rival ways to decide what is true and owed.'],['roads','Roads, Seas, and Crossings','Each crossing changes David’s knowledge, alliances, and degree of freedom.'],['money','Money and Obligation','Coins, gold, wagers, and bargains measure loyalties as often as wealth.'],['tokens','Letters, Names, and Tokens','Documents, aliases, and small signs open doors while concealing dangerous identities.']].map(([k,name,description])=>({...stamp,id:ref('motif',k),name,description,color:'#75634d',tags:[]}))
const relationships=[['david','ebenezer','Nephew and uncle','negative','David seeks family truth from an uncle who fears his claim.',event(2,3)],['david','alan','Travelling companions','positive','Mutual rescue grows into a friendship tested by politics, pride, and exhaustion.',event(9,2)],['david','rankeillor','Client and counsel','positive','Rankeillor listens, verifies, and turns David’s story into a legal strategy.',event(27,1)],['alan','colin','Jacobite and Crown factor','negative','Alan’s political hatred fixes upon the factor known in Appin as the Red Fox.',event(12,1)],['hoseason','ebenezer','Captain and secret client','negative','A private bargain makes the captain the instrument of Ebenezer’s scheme.',event(5,3)],['alan','james','Clan allies','positive','Shared Stewart loyalty binds the fugitive swordsman to the Appin leader.',event(12,1)]].map(([a,b,label,sentiment,description,start],i)=>({...stamp,id:ref('relationship',i+1),characterAId:ref('char',a),characterBId:ref('char',b),label,sentiment,description,strength:6,isBidirectional:true,startEventId:start}))
const relationshipSnapshots=[[1,event(10,3),'Comrades in defence','positive','Shared danger in the round-house turns necessity into trust.',8],[1,event(24,3),'Friends after a bitter quarrel','positive','Alan’s care when David collapses restores the friendship.',9],[0,event(29,3),'Claim resolved by agreement','mixed','Ebenezer yields income and recognition after his confession is witnessed.',4]].map(([ri,eventId,label,sentiment,description,strength],i)=>({...stamp,id:ref('relationship-snapshot',i+1),relationshipId:relationships[ri].id,eventId,label,sentiment,description,strength,isActive:true,sortKey:i}))
const loreCategories=[{...stamp,id:ref('lore-category','edition'),name:'Edition and Reading',color:'#82664b',sortOrder:0},{...stamp,id:ref('lore-category','history'),name:'Scotland in 1751',color:'#596a55',sortOrder:1}]
const lorePages=[['source','edition','Source Edition',`Scene drafts reproduce the retained text of ${sourceEdition}. Exact source: ${sourceUrl}. SHA-256: ${sourceSha256}. Project Gutenberg framing, licence text, and end delimiter are excluded. Original English; no translator. Public domain in the United States.`,event(1)],['boundaries','edition','Extraction and Reconstruction','Extraction begins with the dedication and continues through the final chapter. Event cuts occur only at paragraph boundaries; validation reconstructs the normalized retained source without omission, duplication, or reordering.',event(1)],['calendar','edition','Editorial Chronology','The narrative opens in June 1751. Because many elapsed intervals are literary rather than fully dated, event times use a monotonic editorial day count; travel values record the difference between consecutive events.',event(1)],['maps','edition','Map Method','The Scotland and Highlands charts are interpretive reading aids, while the House of Shaws, Covenant, and Cluny maps are invented plans based on narrated movement. Coordinates rise from each image’s bottom edge.',event(1)],['rising','history','After the Jacobite Rising','The story takes place after the failed rising of 1745, when Jacobite loyalty remains politically dangerous and Highland districts are watched by government power.',event(12,1)],['appin','history','Appin and the Forfeited Estates','Government management of forfeited Stewart lands, rents, and removals sharpens conflict around Colin Campbell and James Stewart.',event(17,1)]].map(([k,c,title,body,visibleFromEventId])=>({...stamp,id:ref('lore',k),categoryId:ref('lore-category',c),title,body,visibleFromEventId,tags:[],coverImageId:null,linkedEntityIds:[]}))
const factDefs=[['uncle','Ebenezer is David’s uncle','The letter and Ebenezer’s answers establish the family connection.',event(2,3),['david','ebenezer']],['sale','David is being carried for sale','The Covenant intends to sell David into colonial service.',event(7,3),['david','riach']],['alan','The survivor is Alan Breck Stewart','The armed stranger identifies himself and bargains for passage.',event(9,3),['david','alan']],['redfox','Colin Campbell is called the Red Fox','Alan names the Crown factor he hates.',event(12,1),['david','alan']],['murder','Colin Campbell has been murdered','A shot on the Appin road kills the factor beside David.',event(17,2),['david','alan']],['inheritance','David is the rightful heir of Shaws','Rankeillor explains the brothers’ bargain and Alexander Balfour’s marriage.',event(27,2),['david','rankeillor']],['thomson','Alan uses the name Mr Thomson','The plan at Shaws gives Alan an English alias while he bargains with Ebenezer.',event(28,1),['david','alan','rankeillor']],['confession','Ebenezer paid to have David kidnapped','Ebenezer’s own bargaining words reveal the arrangement with Hoseason.',event(29,1),['david','alan','rankeillor','torrance']]]
const knowledgeFacts=factDefs.map(([k,title,description,at])=>({...stamp,id:ref('fact',k),title,description,readerLearnsAtEventId:at,originEventId:at,tags:[]})),knowledgeReveals=factDefs.flatMap(([k,,,at,who])=>who.map(p=>({...stamp,id:ref('reveal',`${k}-${p}`),factId:ref('fact',k),characterId:ref('char',p),eventId:at,note:'Learned through direct observation, testimony, or shared action.'})))
const factionDefs=[['government','Crown Authorities','Soldiers, factors, and officers enforcing government control after the rising.','#6a5961'],['appin','Appin Stewarts','A Highland kinship network living under forfeiture, removal, and suspicion.','#53684f'],['covenant','Covenant Crew','The officers and sailors of Hoseason’s brig.','#536b75'],['balfour','Balfour Family','The divided family whose old bargain controls the estate of Shaws.','#765f48']]
const factions=factionDefs.map(([k,name,description,color])=>({...stamp,id:ref('faction',k),name,description,color,tags:[],coverImageId:null}))
const factionMemberships=[['government','colin','Factor',event(12,1),event(17,2)],['appin','james','Stewart leader',event(12,1)],['appin','alan','Jacobite agent',event(9,3)],['covenant','hoseason','Captain',event(5,2)],['covenant','shuan','First mate',event(7,1),event(10,3)],['covenant','riach','Second mate',event(7,1)],['balfour','david','Heir',event(27,2)],['balfour','ebenezer','Laird in possession',event(2,3)]].map(([f,c,role,startEventId,endEventId=null],i)=>({...stamp,id:ref('membership',i+1),factionId:ref('faction',f),characterId:ref('char',c),role,startEventId,endEventId,notes:''}))
const characterGoals=[['david','Reach Shaws and learn what his father’s letter means',event(1,1),event(6,3)],['david','Survive captivity and return to Scotland',event(6,3),event(14,3)],['david','Cross the Highlands and clear himself of suspicion',event(17,3),event(26,3)],['david','Prove his inheritance without betraying Alan',event(27,1),event(30,3)],['alan','Carry the Jacobite gold and escape government pursuit',event(9,3),event(30,3)],['ebenezer','Keep possession of Shaws by concealing David’s claim',event(2,3),event(29,3)]].map(([c,text,startEventId,endEventId],i)=>({...stamp,id:ref('goal',i+1),characterId:ref('char',c),type:'primary',text,startEventId,endEventId}))
const mapRoutes=[['outward','Road to Shaws','scotland',['essendean','cramond-road','shaws-gate','queensferry'],'trail'],['sea','Voyage of the Covenant','scotland',['covenant-gateway','earraid'],'sea'],['highland','Flight through the Highlands','highlands',['lettermore','house-fear','heather-rocks','corrynakiegh','rannoch-moor','cluny-gateway','balquhidder'],'trail'],['return','Return to Shaws','scotland',['limekilns','rankeillor-office','newhalls','shaws-gate','edinburgh'],'trail'],['house','The Trap at Shaws','shaws',['shaws-yard','shaws-woods','shaws-kitchen'],'trail'],['ship','Through the Covenant','covenant',['covenant-deck','covenant-hold','covenant-forecastle','covenant-galley','covenant-cabin','round-house'],'trail'],['cage','Cluny’s Cage','cluny',['cluny-entrance','cluny-chamber'],'trail']].map(([k,name,map,points,routeType])=>({...stamp,id:ref('route',k),mapLayerId:ref('map',map),name,routeType,waypoints:points.map(x=>ref('loc',x)),color:'#8b6546',notes:'Editorial route based on narrated movement; no surveyed distance is claimed.'}))
const cover=image('world','cover','art/world.png').id
const world={version:18,type:'world',exportedAt:now,world:{...stamp,id:W,name:'Kidnapped',description:'In Scotland after the Jacobite rising, a newly orphaned Lowland youth sets out to claim his place in a divided family and enters a country of dangerous seas, Highland loyalties, and contested law.',coverImageId:cover,theme:'theme-historical',readingMode:true,continuityStaleThreshold:5,wordTarget:countWords(narrativeText),calendar:{startYear:1751,yearSuffix:'',months:[{name:'January',days:31},{name:'February',days:28},{name:'March',days:31},{name:'April',days:30},{name:'May',days:31},{name:'June',days:30},{name:'July',days:31},{name:'August',days:31},{name:'September',days:30},{name:'October',days:31},{name:'November',days:30},{name:'December',days:31}]}},mapLayers,locationMarkers,characters,items,characterSnapshots,itemPlacements,chapters,events,sceneTexts,blobs,relationships,relationshipSnapshots,timelines:[{...stamp,id:T,name:'David Balfour’s Memoir',description:'The dedication and thirty chapters in their original reading order, using an editorial elapsed-day calendar.',color:'#5d704f',dayOffset:0}],plotThreads,motifs,loreCategories,lorePages,knowledgeFacts,knowledgeReveals,factions,factionMemberships,characterGoals,mapRoutes}
for(const k of ['characterMovements','locationSnapshots','itemSnapshots','travelModes','timelineRelationships','crossTimelineArtifacts','mapRegions','mapRegionSnapshots','mapAnnotations','factionRelationships','continuitySuppressions','writingLogs','sceneRevisions'])world[k]=[]
if(normalize(sceneTexts.map(x=>x.text).join('\n\n'))!==normalize(narrativeText))throw Error('Source reconstruction failed')
fs.writeFileSync(new URL('../../library/kidnapped.pwk',import.meta.url),JSON.stringify(world,null,2)+'\n')
console.log({chapters:chapters.length,events:events.length,words:sceneTexts.reduce((n,x)=>n+x.wordCount,0),characters:characters.length,locations:locationMarkers.length,maps:mapLayers.length,items:items.length,images:blobs.length,snapshots:characterSnapshots.length,sourceSha256})
