const E=(title,description,location,tension,cast,items=[])=>({title,description,location,tension,cast,items})
export const chapterPlans = [
 [E('The Last Morning in Essendean','David leaves the minister who raised him and receives a letter for the House of Shaws.','essendean',2,['david','campbell'],['letter','purse']),E('A Road of Warnings','Travellers along the Edinburgh road react uneasily when David names his destination.','cramond-road',2,['david'],['letter']),E('The Tower at Dusk','David reaches the neglected estate and calls through a barred door to its unseen master.','shaws-gate',3,['david','ebenezer'],['letter'])],
 [E('A House Feared Nearby','Neighbours describe Shaws and its solitary owner before David approaches the tower.','cramond-road',2,['david']),E('Parley through a Door','Ebenezer questions the stranger outside while keeping bolts and walls between them.','shaws-yard',3,['david','ebenezer'],['letter']),E('Admitted to Shaws','The letter forces Ebenezer to acknowledge his nephew and offer grudging shelter.','shaws-kitchen',3,['david','ebenezer'],['letter'])],
 [E('Supper under Suspicion','David studies his uncle’s meanness while Ebenezer probes what the boy knows.','shaws-kitchen',3,['david','ebenezer'],['bible']),E('The Family Question','Questions about David’s father expose fear beneath Ebenezer’s hostility.','shaws-kitchen',4,['david','ebenezer']),E('A Bargain for Answers','From his sparse chamber, David weighs Ebenezer’s promise of information and money against the danger gathering in the house.','shaws-bedroom',4,['david','ebenezer'])],
 [E('The Unlit Stair','David climbs the unfinished tower stair without lamp or warning.','shaws-stair',4,['david','ebenezer']),E('A Step into Emptiness','Wind and lightning reveal a fatal gap at the head of the stair just before David falls.','shaws-stair',5,['david']),E('Uncle and Nephew at Bay','David returns alive, forces Ebenezer to yield, and demands movement toward a lawyer.','shaws-kitchen',4,['david','ebenezer'])],
 [E('Toward Queen’s Ferry','Ebenezer conducts David to the Forth while trying to recover control of their bargain.','queensferry',2,['david','ebenezer']),E('Ransome from the Brig','A bruised cabin-boy brings Captain Hoseason’s invitation from the Covenant.','hawes-inn',3,['david','ebenezer','ransome','hoseason']),E('Private Business','Ebenezer and Hoseason confer while David learns that Rankeillor knows the Balfour family.','hawes-inn',4,['david','ebenezer','ransome','hoseason'],['letter'])],
 [E('Aboard for a Look','Hoseason coaxes David into visiting the brig before the tide changes.','covenant-deck',3,['david','hoseason','ransome']),E('The Shore Recedes','David realizes the boat has left the quay while Hoseason delays every request to return.','covenant-deck',4,['david','hoseason','ransome']),E('Kidnapped','A blow ends David’s resistance as the Covenant gets under way with Ebenezer’s bargain complete.','covenant-deck',5,['david','hoseason','shuan','ransome'])],
 [E('Darkness below Deck','David wakes injured and desperately sick in the brig’s hold.','covenant-hold',4,['david','riach']),E('Riach Intervenes','The second mate insists that David must have air and humane treatment if he is to live.','covenant-hold',3,['david','riach','hoseason']),E('Bound for the Carolinas','Moved forward, David learns he is cargo intended for sale into colonial service.','covenant-forecastle',4,['david','riach','hoseason','ransome'])],
 [E('Life in the Forecastle','David recovers among sailors and observes the fear surrounding Mr Shuan.','covenant-forecastle',3,['david','riach','shuan','ransome']),E('The Cabin-Boy’s Terror','Ransome’s wounds and obedience reveal the violence he endures.','covenant-cabin',4,['david','ransome','shuan','hoseason']),E('Death in the Cabin','Shuan kills Ransome during a drunken rage, and the officers close ranks around the death.','covenant-cabin',5,['david','ransome','shuan','hoseason','riach'])],
 [E('David Takes the Galley','David assumes the dead boy’s work as weather and tempers worsen.','covenant-galley',3,['david','hoseason','shuan','riach']),E('Alan and the Gold','The Covenant rescues Alan Breck Stewart, who bargains for passage while the officers mark the belt beneath his coat.','covenant-cabin',4,['david','hoseason','alan'],['belt-gold','sword','pistols']),E('Warning the Stranger','David overhears the murder plan, warns Alan, and helps prepare the round-house for defence.','round-house',5,['david','alan','hoseason','shuan','riach'],['belt-gold','sword','dirk','pistols'])],
 [E('The First Assault','The crew rushes the round-house and meets Alan’s sword and David’s fire.','round-house',5,['david','alan','hoseason','shuan','riach'],['sword','dirk','pistols']),E('Steel in the Doorway','Alan holds the entrance while David guards the skylight and reloads.','round-house',5,['david','alan','shuan'],['sword','dirk','pistols']),E('The Attack Breaks','Shuan falls and the surviving officers withdraw, leaving the defenders in command of the stern.','round-house',5,['david','alan','shuan','hoseason','riach'],['sword'])],
 [E('Terms across the Deck','Hoseason negotiates food, movement, and safety with the men he tried to murder.','covenant-deck',3,['david','alan','hoseason','riach']),E('Alan’s Confidence','Alan and David exchange histories while a guarded truce settles over the brig.','round-house',2,['david','alan'],['silver-button','belt-gold']),E('A Course for the Hebrides','The Covenant turns toward the western islands under an agreement to land Alan.','covenant-cabin',3,['david','alan','hoseason'])],
 [E('The Red Fox Named','Alan explains the divided Highlands and his hatred of Colin Campbell.','round-house',3,['david','alan','colin','james']),E('Loyalties Declared','David’s Whig principles and Alan’s Jacobitism test their new friendship.','round-house',3,['david','alan']),E('Reefs in the Dark','The brig enters dangerous waters while Hoseason relies on Alan’s local knowledge.','covenant-deck',4,['david','alan','hoseason','riach'])],
 [E('Among the Torran Rocks','Wind, darkness, and uncertain bearings drive the Covenant into the reef.','covenant-deck',5,['david','alan','hoseason','riach']),E('The Brig Strikes','The hull breaks upon the rocks and every alliance gives way to survival.','covenant-deck',5,['david','alan','hoseason','riach']),E('Swept Away','David clings to wreckage and loses sight of Alan and the ship in the surf.','covenant-deck',5,['david'])],
 [E('Alone on Earraid','David wakes on a barren islet with little food and no clear way ashore.','earraid',4,['david'],['purse']),E('Hunger and Misreading','Repeated efforts to escape fail because David mistakes a tidal channel for open sea.','earraid',4,['david']),E('The Crossing Revealed','Local fishers show that the strait can be crossed on foot when the tide withdraws.','earraid',2,['david'])],
 [E('Across Mull','David walks through wet country seeking news of Alan and a route to the mainland.','torosay',3,['david'],['silver-button']),E('Henderland’s Shelter','The catechist feeds David and explains local names, dangers, and sympathies.','torosay',2,['david','henderland']),E('The Silver-Button Trail','A chain of guarded messages directs David onward without openly naming Alan.','torosay',3,['david','henderland','breck'],['silver-button','button-message'])],
 [E('Guided through Morvern','Boatmen and sympathizers carry David across water and along watched tracks.','morvern',3,['david','breck'],['silver-button']),E('Duncan’s Household','The blind catechist welcomes David with Gaelic music and questions.','morvern',2,['david','duncan']),E('Word from Alan','Neil Roy recognizes the token and arranges the final steps toward Appin.','corran',3,['david','neil'],['silver-button','button-message'])],
 [E('The Appin Road','David enters a district tense with evictions, soldiers, and clan resentment.','ballachulish',3,['david','colin']),E('A Shot from the Wood','Colin Campbell is killed on the road as David stands nearby.','ballachulish',5,['david','colin']),E('Flight from the Murder','Alan pulls David away before soldiers can seize them as suspects.','ballachulish',5,['david','alan','colin'])],
 [E('Questions in Lettermore','David demands to know whether Alan had foreknowledge of the killing.','lettermore',4,['david','alan']),E('Trust under Strain','Alan denies participation but refuses the kind of answer David wants.','lettermore',4,['david','alan']),E('Choosing the Flight','David accepts the immediate need to flee while reserving judgment.','lettermore',3,['david','alan'])],
 [E('Shelter with James','James of the Glens receives the fugitives while messengers report the tightening search.','house-fear',4,['david','alan','james']),E('Money for the Road','Clan funds and French gold become entangled with the danger created by the murder.','house-fear',4,['david','alan','james'],['belt-gold']),E('Into the Heather','David and Alan leave before dawn with soldiers moving through Appin.','house-fear',5,['david','alan','james'],['silver-button'])],
 [E('Above the Soldiers','The fugitives hide among exposed rocks while troops search below.','heather-rocks',5,['david','alan']),E('Heat and Thirst','Sun, lack of water, and enforced stillness wear down David’s strength.','heather-rocks',4,['david','alan']),E('Night Escape','Darkness permits a dangerous descent beyond the nearest patrols.','heather-rocks',4,['david','alan'])],
 [E('The Heugh','David and Alan conceal themselves in a narrow hollow with soldiers close at hand.','corrynakiegh',4,['david','alan']),E('A Drop at a Time','Alan contrives to bring water while David lies exhausted and feverish.','corrynakiegh',4,['david','alan']),E('Patrols Pass','The search moves onward and the fugitives prepare for another night march.','corrynakiegh',4,['david','alan'])],
 [E('Across Rannoch','The pair crosses open moor by night, steering between roads and settlements.','rannoch-moor',4,['david','alan']),E('Strength Failing','Hunger, sleeplessness, and wet ground push David toward collapse.','rannoch-moor',4,['david','alan']),E('Ben Alder Ahead','Alan aims for the concealed refuge of the outlawed Cluny Macpherson.','cluny-gateway',3,['david','alan','cluny'])],
 [E('Entrance to the Cage','Guides lead the travellers through a hidden approach beneath Ben Alder.','cluny-entrance',3,['david','alan','cluny']),E('Cluny’s Hospitality','The outlawed chief welcomes Alan and provides food, shelter, and news.','cluny-chamber',2,['david','alan','cluny']),E('The Cards','Alan loses much of their money gambling and pride makes the loss harder to repair.','cluny-chamber',4,['david','alan','cluny'],['belt-gold','purse'])],
 [E('Money and Pride','David condemns Alan’s losses while Alan resents the Lowlander’s judgment.','cluny-chamber',4,['david','alan','cluny']),E('The Quarrel on the Road','Fatigue turns grievance into cruel words after they leave the refuge.','rannoch-moor',5,['david','alan']),E('David Collapses','Alan’s attempt to provoke a duel ends when David’s illness and exhaustion become undeniable.','rannoch-moor',4,['david','alan'])],
 [E('Recovery in Balquhidder','David recovers under shelter while Alan seeks contacts and a safer road.','balquhidder',2,['david','alan']),E('Robin Oig’s Challenge','Alan and Robin measure clan honour through boasts and the possibility of steel.','balquhidder',4,['david','alan','robin']),E('A Contest of Pipes','Music replaces violence and lets both Highlanders preserve their pride.','balquhidder',3,['david','alan','robin'],['pipes'])],
 [E('Toward the Forth','David and Alan pass through more settled country while avoiding warrants and questions.','limekilns',3,['david','alan']),E('Help at Limekilns','An innkeeper’s household understands their danger and quietly arranges a boat.','limekilns',3,['david','alan','innkeeper','daughter']),E('Across the Forth','The fugitives cross by night and separate the Highland danger from David’s legal business.','limekilns',4,['david','alan','daughter'])],
 [E('Rankeillor Hears the Story','David reaches the lawyer, who listens carefully before accepting his identity.','rankeillor-office',3,['david','rankeillor']),E('The Balfour History','Rankeillor explains the brothers’ rivalry, marriage bargain, and the ownership of Shaws.','rankeillor-office',3,['david','rankeillor'],['will']),E('A Plan for Proof','Lawyer and heir devise a way to make Ebenezer confess without exposing Alan.','rankeillor-office',4,['david','rankeillor','torrance'])],
 [E('Alan as Messenger','From the party’s base at Newhalls, Alan takes an English name and carries their story toward Shaws.','newhalls',4,['alan','david','rankeillor','torrance'],['silver-button']),E('The Price of a Nephew','Alan leads Ebenezer into bargaining over what he supposedly paid to have David carried away.','shaws-yard',4,['alan','ebenezer']),E('Witnesses in the Wood','David, Rankeillor, and Torrance listen from concealment as the trap closes.','shaws-woods',4,['david','rankeillor','torrance','alan','ebenezer'])],
 [E('The Confession','Ebenezer names Hoseason and the kidnapping payment loudly enough for the witnesses.','shaws-yard',5,['alan','ebenezer','david','rankeillor','torrance']),E('David Comes Home','David reveals himself and the lawyer converts Ebenezer’s panic into negotiation.','shaws-kitchen',4,['david','ebenezer','rankeillor','torrance','alan']),E('An Agreement at Shaws','Ebenezer signs terms granting David income and recognition while accounts remain to be settled.','shaws-kitchen',3,['david','ebenezer','rankeillor','torrance','alan'],['memorandum','will'])],
 [E('Duty to the Hunted','David asks Rankeillor how he can help Alan and James without joining them in the dock.','shaws-yard',3,['david','rankeillor','alan']),E('Letters for the Road','Rankeillor prepares introductions that can aid Alan’s escape and David’s testimony.','shaws-kitchen',2,['david','rankeillor','alan'],['memorandum']),E('Parting in Edinburgh','David and Alan reach the capital and part with friendship tested but intact.','edinburgh',4,['david','alan'],['silver-button'])],
]

if (chapterPlans.length !== 30) throw Error(`Expected 30 chapter plans, found ${chapterPlans.length}`)

// Events always begin at paragraph boundaries. The three-way divisions were
// reviewed against the chapter sequence and deliberately keep headings/front
// matter with the first event. Exact indices are derived reproducibly from each
// chapter's retained paragraph count to avoid line-ending-dependent offsets.
export function withCuts(section, plan) {
  const paragraphs = section.text.split(/\n{2,}/)
  const cuts = [0, Math.max(1, Math.floor(paragraphs.length / 3)), Math.max(2, Math.floor(paragraphs.length * 2 / 3))]
  cuts[2] = Math.max(cuts[1] + 1, cuts[2])
  if (cuts[2] >= paragraphs.length) cuts[2] = paragraphs.length - 1
  return plan.map((event, i) => ({ ...event, cut: cuts[i] }))
}
