export const maps = [
  ['scotland', null, 'Scotland, 1751', 'An editorial route map of David Balfour’s journey through the Lowlands, western seas, Highlands, and the Forth approaches.'],
  ['shaws', 'scotland', 'House of Shaws', 'An interpretive plan of the unfinished tower-house, yard, stair, upper rooms, and neglected grounds.'],
  ['covenant', 'scotland', 'Brig Covenant', 'An interpretive deck plan of the brig, including forecastle, cabin, hold, galley, and round-house.'],
  ['highlands', 'scotland', 'Appin and the Highland Flight', 'A detailed route map from Morvern and Appin through the heather, corries, caves, and eastern passes.'],
  ['cluny', 'highlands', 'Cluny’s Cage', 'An interpretive plan of the concealed cave and its chambers beneath Ben Alder.'],
]

export const locations = [
  ['essendean','scotland','Essendean','The Lowland parish where David is raised by Mr Campbell before beginning his journey.'],
  ['cramond-road','scotland','Road through Cramond','The road north-west from Edinburgh where local warnings make the House of Shaws seem increasingly ominous.'],
  ['shaws-gate','scotland','House of Shaws','A neglected estate dominated by an unfinished tower and guarded by its suspicious owner.','shaws'],
  ['shaws-yard','shaws','Yard and Door','The bare threshold where Ebenezer bargains through a locked door before admitting his nephew.'],
  ['shaws-kitchen','shaws','Kitchen','A smoky, comfortless room where uncle and nephew eat under mutual watch.'],
  ['shaws-stair','shaws','Unfinished Stair','A dark stair whose upper flight lacks both windows and a finished landing.'],
  ['shaws-bedroom','shaws','David’s Chamber','A sparse upper room assigned to David after the tower ordeal.'],
  ['queensferry','scotland','Queen’s Ferry','The Forth-side town where David meets Mr Rankeillor’s name and his uncle meets Captain Hoseason.'],
  ['hawes-inn','scotland','Hawes Inn','The busy waterside inn used by Hoseason and Ebenezer to settle their private bargain.'],
  ['covenant-gateway','scotland','Brig Covenant','The Dysart brig lying off Queen’s Ferry before sailing for the Carolinas.','covenant'],
  ['covenant-deck','covenant','Main Deck','The working deck where David is carried aboard, wakes at sea, and later faces storm and wreck.'],
  ['covenant-forecastle','covenant','Forecastle','The cramped sailors’ quarters where David tends the injured and hears the crew’s opinions.'],
  ['covenant-cabin','covenant','Captain’s Cabin','Hoseason’s stern cabin for charts, meals, bargains, and guarded councils.'],
  ['covenant-hold','covenant','Hold','A dark, airless confinement below deck where sickness and concussion nearly kill David.'],
  ['covenant-galley','covenant','Galley','The ship’s cooking space where David works after Ransome’s death.'],
  ['round-house','covenant','Round-House','The stern cabin defended by David and Alan against the officers and crew.'],
  ['earraid','scotland','Islet of Earraid','A tidal islet off Mull where David survives alone until local knowledge reveals the crossing.'],
  ['torosay','scotland','Torosay and Mull','Farm country and rough roads across Mull where David follows Alan’s silver-button messages.'],
  ['morvern','highlands','Morvern','The mainland shore and wooded tracks crossed with guides while redcoat patrols search the district.'],
  ['corran','highlands','Corran Ferry','The narrow crossing into Appin where David rejoins Alan.'],
  ['ballachulish','highlands','Ballachulish','The Appin roadside where Colin Campbell is shot and suspicion falls upon nearby Highlanders.'],
  ['lettermore','highlands','Wood of Lettermore','A concealed wood where David confronts Alan about the murder and their peril.'],
  ['house-fear','highlands','James of the Glens’s House','The Stewart household that shelters the fugitives while the district closes around them.'],
  ['heather-rocks','highlands','The Rocks','A high, exposed refuge where David and Alan hide above soldiers searching the glen.'],
  ['corrynakiegh','highlands','Heugh of Corrynakiegh','A narrow hollow where the fugitives endure thirst and wait for darkness.'],
  ['rannoch-moor','highlands','Rannoch Moor','Open moorland crossed by night under hunger, fatigue, and the threat of patrols.'],
  ['cluny-gateway','highlands','Cluny’s Cage','A hidden refuge beneath Ben Alder occupied by the outlawed chief and his household.','cluny'],
  ['cluny-entrance','cluny','Hidden Entrance','A screened approach through rock and brush leading into the chief’s refuge.'],
  ['cluny-chamber','cluny','Cluny’s Chamber','A dry inner cave furnished for council, hospitality, gaming, and concealment.'],
  ['balquhidder','highlands','Balquhidder','Rob Roy country where clan pride turns a meeting with Robin Oig into a dangerous contest.'],
  ['limekilns','scotland','Limekilns','The Forth shore reached after the fugitives cross the water with the help of an innkeeper’s daughter.'],
  ['rankeillor-office','scotland','Rankeillor’s Office','The lawyer’s orderly room where David’s identity and inheritance are examined.'],
  ['newhalls','scotland','Newhalls','The lodging used as the base for David and Rankeillor’s plan against Ebenezer.'],
  ['shaws-woods','shaws','Woods by Shaws','The concealed position from which David listens while Alan draws out Ebenezer’s confession.'],
  ['edinburgh','scotland','Edinburgh','The capital to which David returns with his affairs settled and Alan’s escape still to arrange.'],
]

export const characters = [
  ['david','David Balfour',[],'A recently orphaned seventeen-year-old Lowlander setting out with a letter, a small inheritance, and firm ideas of justice.','#526d7b'],
  ['campbell','Mr Campbell',[],'The minister of Essendean and David’s guardian, who sends him toward the House of Shaws.','#786b58'],
  ['ebenezer','Ebenezer Balfour',[],'The reclusive master of Shaws, miserly, fearful, and reluctant to discuss David’s father.','#6c5847'],
  ['ransome','Ransome',[],'A mistreated cabin-boy from the Covenant, eager to please and frightened of the officers.','#98704f'],
  ['hoseason','Captain Elias Hoseason',[],'Master of the brig Covenant, outwardly devout and capable of ruthless commerce.','#435d69'],
  ['shuan','Mr Shuan',[],'The Covenant’s first mate, violent when drunk and troubled afterward.','#714f45'],
  ['riach','Mr Riach',[],'The Covenant’s second mate, a medical man whose conscience competes with drink and obedience.','#5c6d70'],
  ['alan','Alan Breck Stewart',[],'A poised Highland Jacobite carrying French gold and travelling under danger from the law.','#79533e'],
  ['henderland','Henderland',[],'A Mull catechist who gives David food, shelter, and news of the country.','#68704f'],
  ['duncan','Duncan Mackiegh',[],'A blind Highland catechist whose household offers music, hospitality, and guidance.','#6b5f73'],
  ['neil','Neil Roy Macrob',[],'An innkeeper and covert Jacobite contact who passes Alan’s token and instructions.','#7d6848'],
  ['colin','Colin Campbell of Glenure',[],'The Crown’s factor in Appin, responsible for managing forfeited Stewart lands.','#9a533f'],
  ['james','James Stewart',['James of the Glens'],'The Stewart leader in Appin, burdened by evictions, clan obligations, and government suspicion.','#556947'],
  ['cluny','Cluny Macpherson',[],'An outlawed Highland chief living in a hidden refuge with retainers and dwindling resources.','#66513e'],
  ['robin','Robin Oig',[],'A proud son of Rob Roy, quick to test honour through music and steel.','#824b3f'],
  ['rankeillor','Mr Rankeillor',[],'A careful Edinburgh lawyer who knew David’s parents and respects evidence over appearance.','#596b65'],
  ['torrance','Torrance',[],'Rankeillor’s clerk, entrusted with practical arrangements in the recovery of David’s rights.','#6f725b'],
  ['innkeeper','Limekilns Innkeeper',[],'A cautious Forth-side host whose family quietly helps two hunted travellers.','#78644e'],
  ['daughter','Innkeeper’s Daughter',[],'A resourceful young woman who helps arrange the fugitives’ passage across the Forth.','#916b63'],
  ['breck','John Breck MacColl',[],'A Highland boatman involved in carrying David between islands and mainland contacts.','#4f6870'],
]

export const items = [
  ['letter','Mr Campbell’s Letter','A sealed introduction directing David to Ebenezer Balfour at the House of Shaws.','document'],
  ['purse','David’s Purse','David’s small store of money, guarded carefully throughout the journey.','container'],
  ['bible','Ebenezer’s Bible','A large Bible used conspicuously by the master of Shaws.','book'],
  ['silver-button','Silver Button','A distinctive token used to identify Alan’s friends and carry messages through the Highlands.','token'],
  ['belt-gold','Belt of Gold','French gold carried for Jacobite leaders and concealed beneath Alan’s clothes.','container'],
  ['sword','Alan’s Sword','A well-used Highland blade wielded with exceptional skill in the round-house.','weapon'],
  ['dirk','David’s Dirk','A short blade taken up during the defence of the round-house.','weapon'],
  ['pistols','Alan’s Pistols','A pair of pistols carried with Alan’s travelling arms.','weapon'],
  ['button-message','Button Messages','Instructions and tokens passed among sympathetic households along David’s route.','document'],
  ['will','Alexander Balfour’s Will','The family settlement whose history explains the competing claims to Shaws.','document'],
  ['memorandum','Ebenezer’s Memorandum','A written agreement extracted after Ebenezer reveals the kidnapping bargain.','document'],
  ['pipes','Highland Pipes','The instrument through which Alan and Robin Oig turn rivalry into musical contest.','instrument'],
]
