// Paragraph offsets are zero-based within each retained Gutenberg chapter.
// A cut begins with the paragraph named here, never inside a paragraph.
export const cuts = [
  [
    [0,'Holmes at Rest','Watson confronts Holmes over cocaine and hears why idle days trouble him.'],
    [18,'The Consulting Detective','Holmes describes his published methods and shows Watson the difference between observing and deducing.'],
    [33,'The Watch Test','Watson lends Holmes an inherited watch and challenges him to read its former owner.'],
    [41,'A Painful Deduction','Holmes describes Watson’s brother, then explains the marks that led him there.'],
    [53,'A Visitor Announced','Mrs. Hudson brings the card of a young woman unknown to Holmes.'],
  ],
  [
    [0,'Miss Morstan Arrives','Mary Morstan asks Holmes and Watson to hear a strange and private case.'],
    [9,'A Missing Father','Mary recounts Captain Morstan’s disappearance after his return to London.'],
    [17,'The Pearls','Mary describes the anonymous gifts that followed the disappearance.'],
    [19,'An Invitation','A new letter asks Mary to attend a meeting and permits two companions.'],
    [31,'After the Visitor','Watson and Holmes differ over Mary and examine the handwriting she leaves behind.'],
  ],
  [
    [0,'Holmes’s First Lead','Holmes returns with a connection between Captain Morstan and Major Sholto.'],
    [9,'The Indian Diagram','Mary joins the two men and shares a paper found among her father’s effects.'],
    [17,'At the Lyceum','An unknown messenger identifies the party outside the theatre.'],
    [23,'Through London','The closed cab crosses the city toward an undisclosed destination.'],
    [27,'An Unfamiliar Door','The travellers arrive in a guarded and poorly lit neighbourhood.'],
  ],
  [
    [0,'Thaddeus Sholto','The visitors meet the nervous man who summoned them.'],
    [19,'The Major’s Fear','Thaddeus describes his father’s anxious retirement and the mystery around him.'],
    [24,'Morstan’s Fate','The account of Major Sholto’s last hours explains what happened to Mary’s father.'],
    [28,'The Face at the Window','The major’s confession ends in terror at an intruder.'],
    [31,'A Pearl Each Year','Thaddeus tells how he and his brother searched and why he sent Mary the pearls.'],
    [36,'Toward Pondicherry Lodge','Thaddeus takes the party to the house where the treasure has been located.'],
    [40,'At the Lodge','The carriage reaches Bartholomew Sholto’s estate.'],
  ],
  [
    [0,'The Guarded Gate','At Pondicherry Lodge, a porter bars the visitors until Holmes gains entry.'],
    [15,'A Darkened House','The silent house and troubled grounds unsettle the arriving party.'],
    [32,'Mrs. Bernstone','The housekeeper tells them Bartholomew has shut himself in.'],
    [36,'The Upper Passage','Holmes and Watson climb to the locked chamber and look inside.'],
    [41,'Bartholomew Found','The door gives way, exposing Bartholomew’s body and the written sign.'],
    [47,'A Poisoned Thorn','Holmes identifies the fatal wound and warns Watson about the weapon.'],
    [53,'The Missing Treasure','Thaddeus sees that the hidden chest has gone and fears suspicion.'],
  ],
  [
    [0,'The Window Marks','Holmes reads the wooden-leg impression and rope marks in the chamber.'],
    [19,'Above the Chamber','The roof route and unusual bare footprints point to a second intruder.'],
    [28,'The Creasote Trace','Holmes finds a scent that may let a dog follow the escape.'],
    [42,'Athelney Jones','The official detective reaches the scene with a competing theory.'],
    [57,'An Arrest','Jones takes Thaddeus into custody despite Holmes’s objections.'],
    [68,'Separate Errands','Watson takes Mary home and undertakes to bring Toby back.'],
  ],
  [
    [0,'Mary Home Safely','Watson escorts Mary to Camberwell and weighs the case on his way out.'],
    [4,'Toby at Pinchin Lane','Watson wakes Sherman and obtains the scent dog.'],
    [17,'Back at the Lodge','Watson returns with Toby while Holmes prepares to trace the roof route.'],
    [19,'The Footprints Revisited','Holmes and Watson return to the chamber to compare the accomplice’s prints.'],
    [31,'Over the Wall','Holmes follows the fugitives across the roof and down into the grounds.'],
    [49,'The Morning Trail','Toby follows creasote through the suburbs as Holmes works out Small’s part.'],
    [72,'The Trail Turns','The dog brings the men through south London toward the river.'],
    [78,'The Wrong Barrel','They discover that Toby has followed a second creasote source.'],
  ],
  [
    [0,'The Scent Recovered','Holmes and Watson return to the true trail after Toby’s mistake.'],
    [8,'At the River','The trail ends at Mordecai Smith’s landing stage.'],
    [12,'Mrs. Smith’s Account','Holmes questions the boatman’s wife about the missing steam launch.'],
    [38,'The Aurora','The two men learn the vessel’s description and consider how to search the Thames.'],
    [48,'A Search Ordered','Holmes sends for help and returns to Baker Street.'],
    [55,'Jones in Print','The morning paper attributes a different account of the murder to the police.'],
    [63,'The Irregulars','Wiggins and the street boys receive a commission to find the launch.'],
    [71,'The Second Footprint','Holmes explains what the small bare prints suggest about the accomplice.'],
  ],
  [
    [0,'No Word from the River','Holmes waits for news of the launch while Watson wakes.'],
    [13,'A Call in Camberwell','Watson returns Toby and visits Mary and Mrs. Forrester.'],
    [19,'Holmes Restless','Watson finds Holmes distressed by the stalled search.'],
    [25,'The Search Widens','Holmes considers more ways the launch could be hidden.'],
    [33,'A Sailor’s Disguise','Holmes leaves in costume to search the river himself.'],
    [39,'An Advertisement','Watson notices Holmes’s notice asking after Smith and the Aurora.'],
    [45,'Jones Returns','The inspector calls at Baker Street with a telegram and a changed view.'],
    [58,'The Old Sailor','A stranger arrives claiming knowledge of the boat and treasure.'],
    [77,'Holmes Revealed','The visitor removes his disguise and tells Watson what he has learned.'],
    [87,'A Plan for the River','Holmes asks Jones for a launch and men at Westminster.'],
  ],
  [
    [0,'Before the Chase','Holmes, Watson and Jones prepare to leave Baker Street armed.'],
    [5,'Westminster Stairs','The party boards an unmarked police launch at dusk.'],
    [15,'The Hidden Launch','Holmes explains why he has watched Jacobson’s repair yard.'],
    [28,'Across the Thames','The police boat waits near the yard while the river traffic passes.'],
    [36,'The Aurora Runs','The fugitive launch emerges and both vessels accelerate downstream.'],
    [45,'Shots at Close Range','A tug interrupts the pursuit before the boats meet in violence.'],
  ],
  [
    [0,'Small in Custody','Holmes questions the captured man aboard the police launch.'],
    [18,'The Iron Chest Arrives','Watson carries the recovered box to Mary’s sitting room.'],
    [36,'The Chest Is Empty','The opened box contains no jewels.'],
    [38,'Watson Speaks','Watson tells Mary what the loss means for his hopes.'],
  ],
  [
    [0,'Back at Baker Street','Watson returns with the empty chest, and Small disputes ownership of the jewels.'],
    [14,'Small’s Early Life','Small begins his account in England and recalls the loss of his leg in India.'],
    [17,'The Agra Fort','The uprising drives Small to the fort and its isolated night guard.'],
    [23,'A Proposal at the Gate','Three men invite Small into a plan to seize a merchant’s treasure.'],
    [34,'Achmet’s Journey','Small hears how the merchant will arrive with the sealed iron box.'],
    [42,'The Merchant Arrives','The conspirators confront Achmet at the gate.'],
    [53,'The Killing','The merchant is killed inside the fort and the box is concealed.'],
    [61,'Imprisoned Partners','The conspiracy is uncovered and the four men lose access to the treasure.'],
    [64,'The Andamans','Small reaches the penal settlement and watches officers’ gambling debts.'],
    [70,'Sholto Hears of the Treasure','Small tests whether Major Sholto will bargain for its location.'],
    [81,'A Bargain with Two Officers','Sholto and Morstan discuss the treasure and the prisoners’ release.'],
    [100,'The Agreement','All four prisoners join the bargain and give the officers a map.'],
    [102,'Tonga’s Help','Small describes his escape with the aid of a boatman.'],
    [105,'Years of Pursuit','Small follows Sholto and the hidden jewels to England.'],
    [108,'The Case Explained','Small closes his account; Holmes tests the remaining details.'],
    [117,'After the Case','Watson tells Holmes of his marriage plans and Holmes turns back to his bottle.'],
  ],
]
