// Coordinates are on a 1400 × 1000 grid, with Y measured from the bottom.
// London and the river are interpretive charts; the Lodge levels are invented.
export const maps = [
  ['london',null,'London and Upper Norwood','Interpretive London chart of the southward journey, Baker Street, the Thames, and Pondicherry Lodge.'],
  ['baker-street','london','Baker Street Rooms','Invented plan of Holmes and Watson’s rooms and Mrs. Hudson’s approach.'],
  ['pondicherry','london','Pondicherry Lodge','Invented estate and ground-floor plan showing the walled grounds, gate, entrance and housekeeper’s room.','pondicherry',0,'Ground floor'],
  ['pondicherry-upper','london','Pondicherry Lodge — Upper Floor','Invented upper-floor plan showing the passage, staircase and Bartholomew’s chamber.','pondicherry',1,'Upper floor'],
  ['pondicherry-roof','london','Pondicherry Lodge — Roof','Invented roof plan showing the tiles, chimneys and trapdoor used in the escape.','pondicherry',2,'Roof'],
  ['thames','london','The Thames','Interpretive chart of the investigation and pursuit along the river.'],
]

export const locations = [
  ['Baker Street','london',390,760,'The north London address where Holmes and Watson receive clients and work through evidence.','baker-street'],
  ['Baker Street sitting room','baker-street',285,390,'The shared sitting room with Holmes’s chair, papers, experiments and fireplace.'],
  ['Baker Street stair','baker-street',695,700,'The stair and passage by which Mrs. Hudson announces callers.'],
  ['Watson’s room','baker-street',1130,385,'Watson’s private room adjoining the shared quarters.'],
  ['Lyceum Theatre','london',720,665,'A busy theatre entrance where the invited party meets a stranger in the evening fog.'],
  ['Thaddeus’s house','london',770,365,'A modest south London exterior hiding Thaddeus Sholto’s richly furnished sitting room.'],
  ['South London carriage road','london',730,430,'A succession of streets toward Upper Norwood, watched from a closed cab.'],
  ['Pondicherry Lodge','london',990,170,'The walled Upper Norwood estate once held by Major Sholto.','pondicherry'],
  ['Lodge gate','pondicherry',855,70,'A guarded opening in the south boundary wall, attended by McMurdo.'],
  ['Lodge grounds','pondicherry',400,485,'Garden paths and excavated earth surrounding the silent house.'],
  ['Housekeeper’s room','pondicherry',1080,480,'Mrs. Bernstone’s small room close to the entrance passage.'],
  ['Upper passage','pondicherry-upper',855,690,'The top-floor corridor beside the central staircase before Bartholomew’s locked chamber.'],
  ['Bartholomew’s chamber','pondicherry-upper',1030,530,'The shuttered eastern upper room furnished as a chemical laboratory and bedchamber.'],
  ['Lodge roof','pondicherry-roof',1100,670,'Eastern roof and trapdoor directly above Bartholomew’s chamber.'],
  ['Lodge boundary wall','pondicherry',55,510,'The outer wall over which the fugitives’ scent leads.'],
  ['Camberwell house','london',780,275,'Mrs. Forrester’s home, where Mary Morstan lives and Watson calls.'],
  ['Pinchin Lane','london',610,340,'A Lambeth lane of animal cages and Toby’s keeper.'],
  ['South London trail','london',780,300,'Streets through Streatham, Brixton and Kennington followed in the dawn.'],
  ['Timber yard','london',840,400,'A Nine Elms yard where a creasote barrel briefly draws Toby astray.'],
  ['The Thames','london',900,565,'London’s working river, crossed and followed during the investigation.','thames'],
  ['Smith’s Wharf','thames',450,625,'A rough landing stage and the Smith family’s boat-house beside the river.'],
  ['Westminster Stairs','thames',375,700,'A river landing where the police steam launch takes on Holmes’s party.'],
  ['Jacobson’s Yard','thames',1050,625,'A repair yard where the Aurora is hidden while its engine is mended.'],
  ['Police launch','thames',850,600,'The fast police boat used to watch and pursue the Aurora.'],
  ['Aurora','thames',1190,570,'Mordecai Smith’s small black steam launch with two red stripes.'],
  ['Vauxhall landing','thames',250,560,'The river landing where Watson disembarks with the iron chest.'],
]

// Each standing description says what a reader can know at first appearance.
export const characters = [
  ['Sherlock Holmes','A consulting detective whose close observation and appetite for difficult problems drive his work.'],
  ['Dr. John Watson','Holmes’s physician friend and the first-person narrator of the case.'],
  ['Mary Morstan','A young governess seeking an explanation for her father’s disappearance and anonymous gifts.'],
  ['Mrs. Hudson','The landlady who receives callers at the Baker Street rooms.'],
  ['Thaddeus Sholto','A nervous, wealthy young man who asks Mary Morstan to hear his account.'],
  ['Bartholomew Sholto','Thaddeus’s brother, living at Pondicherry Lodge and searching its grounds.'],
  ['McMurdo','The former prize-fighter who guards the gate of Pondicherry Lodge.'],
  ['Mrs. Bernstone','The housekeeper at Pondicherry Lodge, worried by her master’s silence.'],
  ['Athelney Jones','A Scotland Yard detective eager to turn the Norwood mystery into an arrest.'],
  ['Jonathan Small','One of four names on the Indian diagram found among Captain Morstan’s effects.'],
  ['The bare-footed accomplice','A small figure seen with the fugitives on the Aurora. Small later names him as Tonga.'],
  ['Mordecai Smith','A Thames boatman who owns a fast steam launch.'],
  ['Mrs. Smith','The boatman’s wife, watching for news from the river.'],
  ['Mr. Sherman','The animal keeper in Pinchin Lane who lends Toby to Watson.'],
  ['Toby','A brown-and-white scent dog whose nose follows creasote through London.'],
  ['Wiggins','The leader of Holmes’s group of street boys, sent to look for the missing launch.'],
  ['Mrs. Cecil Forrester','Mary’s employer and companion in the Camberwell house.'],
  ['The old sailor','A weary, insistent caller who claims to know where the missing launch can be found.'],
  ['Captain Arthur Morstan','Mary Morstan’s father, an army officer whose failure to meet her in London begins the mystery.'],
  ['Major John Sholto','A retired officer associated with Captain Morstan during service in India.'],
  ['Achmet','A merchant whose journey to Agra Fort carries an iron chest.'],
  ['Abdullah Khan','One of the Sikh guards whose proposal Jonathan Small recounts.'],
  ['Mahomet Singh','A guard at Agra Fort and one of the four men in Small’s account.'],
  ['Dost Akbar','Another guard at Agra Fort, named in the agreement of four.'],
  ['Lal Rao','A servant at Pondicherry Lodge named only in the case’s closing explanation.'],
]
