// Paragraph indexes refer to each section's retained Project Gutenberg text.
// Every retained section has planned paragraph cuts and narrative event descriptions.
const E = (start, title, description, place, cast, tension) => ({ start, title, description, place, cast, tension })
export const plans = new Map([
  [1, [
    E(0, 'The Dedication and Tunstall Bell', 'The authorial dedication leads into Tunstall, where the moat-house bell calls villagers from their work and Dick arrives.', 'Tunstall hamlet', ['Dick Shelton', 'Bennet Hatch', 'Clipsby'], 1),
    E(25, 'Dick Rides to the Moat House', 'Dick carries news toward the Moat House and questions Bennet about the gathering of Sir Daniel’s men.', 'Tunstall road', ['Dick Shelton', 'Bennet Hatch'], 2),
    E(26, 'Appleyard’s Warning', 'At the old archer’s field, Bennet summons him to the Moat House and Appleyard warns of enemies in the forest.', 'Tunstall green', ['Dick Shelton', 'Bennet Hatch', 'Appleyard'], 3),
    E(56, 'Appleyard Falls', 'A black arrow kills the old archer as he speaks with Dick and Bennet.', 'Tunstall green', ['Dick Shelton', 'Bennet Hatch', 'Appleyard'], 5),
    E(78, 'Sir Oliver Sees the Arrow', 'Sir Oliver sees Appleyard’s body and the black arrow while Bennet presses for a response.', 'Appleyard’s house', ['Dick Shelton', 'Bennet Hatch', 'Sir Oliver Oates', 'Clipsby', 'Appleyard'], 4),
    E(104, 'The Black Arrow’s Warning', 'A written rhyme names four targets, and Dick departs with a sealed message for Sir Daniel.', 'Tunstall church', ['Dick Shelton', 'Bennet Hatch', 'Sir Oliver Oates', 'Clipsby'], 4),
  ]],
  [2, [
    E(0, 'Sir Daniel at Kettley', 'Sir Daniel extorts a tenant at the inn while Selden obeys his orders; Dick arrives at the threshold.', 'Kettley inn', ['Sir Daniel Brackley', 'Selden', 'Dick Shelton'], 3),
    E(35, 'Dick Reaches Kettley', 'Dick brings Sir Oliver’s letter and hears Sir Daniel’s guarded response to the black arrow.', 'Kettley inn', ['Dick Shelton', 'Sir Daniel Brackley', 'Selden', 'Clipsby'], 3),
    E(58, 'Matcham Asks the Way', 'A young traveller quietly asks Dick for the route to Till Ferry.', 'Kettley inn', ['Dick Shelton', 'Jack Matcham'], 3),
    E(63, 'News from the Fighting', 'A messenger describes the battle, and Sir Daniel orders Selden to sound the muster.', 'Kettley inn', ['Dick Shelton', 'Sir Daniel Brackley', 'Selden'], 4),
    E(69, 'Sir Daniel Misses His Ward', 'Sir Daniel notices the young fugitive has escaped and sends Selden in pursuit.', 'Kettley inn', ['Sir Daniel Brackley', 'Selden'], 4),
  ]],
  [3, [
    E(0, 'The Causeway into the Fen', 'Dick rides homeward through the fen at dawn.', 'Fen causeway', ['Dick Shelton'], 2),
    E(8, 'Matcham Calls from the Reeds', 'Matcham asks Dick for help and joins him on the dangerous causeway.', 'Fen causeway', ['Dick Shelton', 'Jack Matcham'], 3),
    E(24, 'Two Wards of Sir Daniel', 'The travellers compare their dependence on Sir Daniel and the marriage arranged for Dick.', 'Fen causeway', ['Dick Shelton', 'Jack Matcham'], 3),
    E(49, 'Toward the River Till', 'Their quarrel softens as they hurry across the remaining fen.', 'Fen causeway', ['Dick Shelton', 'Jack Matcham'], 2),
  ]],
  [4, [
    E(0, 'At the Fen Ferry', 'Dick and Matcham reach the River Till and rouse the feverish ferryman to take them across.', 'River Till ferry', ['Dick Shelton', 'Jack Matcham', 'Hugh Ferryman'], 2),
    E(22, 'The Ferryman’s Fear', 'The ferryman insists on the appearance of coercion because he fears the Black Arrow.', 'River Till ferry', ['Dick Shelton', 'Jack Matcham', 'Hugh Ferryman'], 4),
    E(31, 'Arrows on the Water', 'A shout from the island exposes the crossing, and an arrow capsizes the ferry.', 'River Till ferry', ['Dick Shelton', 'Jack Matcham', 'Hugh Ferryman', 'John-a-Fenne'], 5),
    E(48, 'Matcham Cannot Keep Pace', 'After the ferry, Matcham’s hurt foot slows their escape.', 'River Till bank', ['Dick Shelton', 'Jack Matcham'], 3),
    E(60, 'The Two Continue on Foot', 'Dick and Matcham negotiate how to proceed despite fear and exhaustion.', 'River Till bank', ['Dick Shelton', 'Jack Matcham'], 2),
  ]],
  [5, [
    E(0, 'An Unfamiliar Forest Track', 'The travellers follow a track Dick does not know.', 'Tunstall forest', ['Dick Shelton', 'Jack Matcham'], 2),
    E(16, 'The Camp Below', 'Hidden above a hollow, they hear Lawless among the Black Arrow men at their fire.', 'Black Arrow camp', ['Dick Shelton', 'Jack Matcham', 'Lawless'], 3),
    E(37, 'Lawless and the Company', 'The outlaws speak of Sir Daniel’s coming passage through the forest.', 'Black Arrow camp', ['Dick Shelton', 'Jack Matcham', 'Lawless', 'Ellis Duckworth'], 4),
    E(50, 'Men Take Their Stations', 'The Black Arrow company disperses to prepare its attack.', 'Tunstall forest', ['Dick Shelton', 'Jack Matcham', 'Ellis Duckworth'], 4),
  ]],
  [6, [
    E(0, 'Whether to Warn Sir Daniel', 'Dick argues that his duty requires warning men threatened by the ambush.', 'Tunstall forest', ['Dick Shelton', 'Jack Matcham'], 3),
    E(21, 'The Lads Quarrel', 'Their disagreement over Dick’s oath continues as Ellis Duckworth leads foresters across a nearby rise.', 'Tunstall forest', ['Dick Shelton', 'Jack Matcham', 'Ellis Duckworth'], 4),
    E(48, 'The Ambush on the Road', 'From a rise Dick watches the armed company enter the Black Arrow’s trap.', 'Forest ridge', ['Dick Shelton', 'Jack Matcham', 'Selden'], 5),
    E(60, 'Dick Calls to Selden', 'Dick tries to save the last survivor; Ellis calls from the wood to take Dick alive.', 'Forest ridge', ['Dick Shelton', 'Jack Matcham', 'Selden', 'Ellis Duckworth'], 5),
  ]],
  [7, [
    E(0, 'Fleeing the Search', 'Dick and Matcham run while the Black Arrow company closes through the forest.', 'Tunstall forest', ['Dick Shelton', 'Jack Matcham'], 5),
    E(18, 'Anger between the Companions', 'The strain of flight revives their argument.', 'Tunstall forest', ['Dick Shelton', 'Jack Matcham'], 3),
    E(38, 'A Crossbow Offered', 'As they reconcile, Dick offers Matcham his crossbow, but Matcham cannot use it.', 'Tunstall forest', ['Dick Shelton', 'Jack Matcham'], 2),
    E(48, 'Water at Day’s End', 'Thirst leads them to a stream as daylight fades.', 'Forest stream', ['Dick Shelton', 'Jack Matcham'], 2),
  ]],
  [8, [
    E(0, 'The Hooded Traveller', 'Dick and Matcham see a bell-bearing figure who appears to be a leper.', 'Forest stream', ['Dick Shelton', 'Jack Matcham'], 3),
    E(31, 'Up from the Stream', 'The two climb away from the water and encounter new danger.', 'Forest hillside', ['Dick Shelton', 'Jack Matcham'], 4),
    E(47, 'The Leper Throws Back His Hood', 'The frightening pursuer catches Matcham and reveals himself to Dick as Sir Daniel.', 'Forest hillside', ['Dick Shelton', 'Jack Matcham', 'Sir Daniel Brackley'], 5),
    E(62, 'The News of Selden', 'Dick tells Sir Daniel of the ambush and his retainer’s death.', 'Forest hillside', ['Dick Shelton', 'Jack Matcham', 'Sir Daniel Brackley'], 4),
    E(78, 'Farewell to Jack Matcham', 'Dick’s companion says that the identity of Jack Matcham is ending as they approach Tunstall.', 'Forest hillside', ['Dick Shelton', 'Jack Matcham'], 3),
    E(81, 'The Moat House Gate', 'The drawbridge opens and Sir Daniel, Bennet, and Sir Oliver receive the travellers.', 'Moat House gate', ['Dick Shelton', 'Jack Matcham', 'Sir Daniel Brackley', 'Bennet Hatch', 'Sir Oliver Oates'], 3),
  ]],
  [9, [
    E(0, 'The Moat House under Watch', 'The survivors reach the defended house, where Bennet hears of Selden’s death and Carter groans nearby.', 'Moat House', ['Dick Shelton', 'Bennet Hatch', 'Carter'], 4),
    E(10, 'Carter’s Wound', 'A wounded retainer asks Dick to bring the priest.', 'Moat House gate', ['Dick Shelton', 'Bennet Hatch', 'Carter'], 4),
    E(16, 'Throgmorton’s Errand', 'Sir Daniel selects Throgmorton to carry a letter through the guarded forest.', 'Moat House gate', ['Dick Shelton', 'Sir Daniel Brackley', 'Bennet Hatch', 'Throgmorton'], 4),
    E(29, 'Dick Questions Bennet', 'Bennet refuses to explain how Harry Shelton died and points Dick toward Carter.', 'Moat House gate', ['Dick Shelton', 'Bennet Hatch'], 4),
    E(33, 'Dick Asks about His Father', 'Dick presses Carter for the truth of Harry Shelton’s death, but receives no clear account.', 'Moat House gate', ['Dick Shelton', 'Carter'], 4),
    E(50, 'Sir Oliver’s Unease', 'Dick finds the priest troubled by the attack and by questions about the past.', 'Moat House', ['Dick Shelton', 'Sir Oliver Oates'], 3),
    E(64, 'Dinner in the Hall', 'Dick questions Goody Hatch about Matcham’s absence, and Bennet warns him before a summons to Sir Daniel.', 'Moat House hall', ['Dick Shelton', 'Goody Hatch', 'Bennet Hatch'], 3),
  ]],
  [10, [
    E(0, 'Sir Daniel’s Oath', 'Dick asks his guardian to deny involvement in his father’s death, and Sir Daniel makes his answer under oath.', 'Moat House hall', ['Dick Shelton', 'Sir Daniel Brackley'], 4),
    E(23, 'Sir Oliver Must Swear', 'Dick asks the priest for the same assurance as the house comes under threat.', 'Moat House hall', ['Dick Shelton', 'Sir Daniel Brackley', 'Sir Oliver Oates'], 4),
    E(48, 'The Priest’s Warning', 'Sir Oliver gives Dick a fearful answer whose manner deepens his suspicion.', 'Moat House hall', ['Dick Shelton', 'Sir Oliver Oates'], 4),
    E(60, 'A Chamber over the Chapel', 'Dick recognizes his danger and is shown to an unfamiliar chamber.', 'Moat House chapel wing', ['Dick Shelton'], 4),
  ]],
  [11, [
    E(0, 'Throgmorton Escapes', 'Sir Daniel and Bennet watch the messenger swim the moat and reach the far bank.', 'Moat House moat', ['Sir Daniel Brackley', 'Bennet Hatch', 'Throgmorton'], 4),
    E(5, 'The Assigned Chamber', 'Dick examines the room above the chapel and wonders why he was moved there.', 'Room over the chapel', ['Dick Shelton'], 3),
    E(11, 'Matcham Comes in Secret', 'Dick’s companion enters the chamber and urges him to see the danger in the house.', 'Room over the chapel', ['Dick Shelton', 'Jack Matcham'], 4),
    E(28, 'Footsteps Below', 'Sounds beneath the floor reveal a concealed approach to the room.', 'Room over the chapel', ['Dick Shelton', 'Jack Matcham'], 5),
    E(44, 'Joanna Names Herself', 'The disguised ward speaks openly with Dick as their peril draws them closer.', 'Room over the chapel', ['Dick Shelton', 'Joanna Sedley'], 4),
    E(55, 'The Door Is Challenged', 'Sir Daniel orders his men to break the chamber door while Dick and Joanna search for an escape.', 'Room over the chapel', ['Dick Shelton', 'Joanna Sedley', 'Sir Daniel Brackley'], 5),
    E(62, 'The Trap Opens', 'They move the bed, find the hidden opening, and descend before the door gives way.', 'Room over the chapel', ['Dick Shelton', 'Joanna Sedley'], 5),
  ]],
  [12, [
    E(0, 'The First Passage Ends', 'The hidden way leads to a dead end and forces Dick and Joanna to turn back.', 'Moat House passage', ['Dick Shelton', 'Joanna Sedley'], 4),
    E(7, 'A Narrower Branch', 'They explore another dark, descending branch of the passage.', 'Moat House passage', ['Dick Shelton', 'Joanna Sedley'], 4),
    E(13, 'Their Promise', 'In the pause underground, the pair speak plainly about their attachment.', 'Moat House passage', ['Dick Shelton', 'Joanna Sedley'], 3),
    E(21, 'Bennet in the Dark', 'Bennet finds them, and Dick refuses to surrender Joanna.', 'Moat House passage', ['Dick Shelton', 'Joanna Sedley', 'Bennet Hatch'], 5),
    E(30, 'The Rope and Trap', 'Bennet directs them toward a way out of the underground passage.', 'Moat House passage', ['Dick Shelton', 'Joanna Sedley', 'Bennet Hatch'], 4),
  ]],
  [13, [
    E(0, 'Flight from the House', 'Dick attempts to get Joanna away from the Moat House as the defenders close in.', 'Moat House moat', ['Dick Shelton', 'Joanna Sedley'], 5),
    E(20, 'A Body in the Trees', 'Wounded and alone, Dick finds an unidentified hanged man in the forest.', 'Tunstall forest', ['Dick Shelton'], 4),
    E(26, 'Throgmorton Discovered', 'Dick raises the hood, recognizes Throgmorton, and takes Sir Daniel’s letter to Wensleydale.', 'Tunstall forest', ['Dick Shelton', 'Throgmorton'], 4),
    E(30, 'The Outlaws Find Dick', 'Men of the Black Arrow discover the exhausted fugitive and carry him to their company.', 'Forest road', ['Dick Shelton', 'Lawless', 'Greensheve'], 4),
    E(42, 'The Black Arrow’s Watchword', 'The outlaws challenge Dick and bring him among their leaders.', 'Black Arrow camp', ['Dick Shelton', 'Lawless', 'Ellis Duckworth'], 4),
    E(56, 'A Letter Reaches the Camp', 'As Dick recovers, a new message brings news to the outlaws.', 'Black Arrow camp', ['Dick Shelton', 'Ellis Duckworth'], 3),
  ]],
  [14, [
    E(0, 'A Watch in Shoreby', 'Dick and the unnamed men of the forest company wait in a harbour alehouse as Lancaster holds the town.', 'Shoreby alehouse', ['Dick Shelton'], 3),
    E(10, 'Following the Torches', 'Capper reports Sir Daniel’s departure, and Dick and Greensheve follow the torchlit party through Shoreby.', 'Shoreby streets', ['Dick Shelton', 'Lawless', 'Greensheve', 'Capper'], 3),
    E(22, 'Sir Daniel and Lord Shoreby', 'The watched party meets another armed company; Dick asks Capper to lift him toward the garden wall.', 'Shoreby downs', ['Dick Shelton', 'Sir Daniel Brackley', 'Lord Shoreby', 'Capper'], 4),
    E(38, 'The Garden Wall', 'Capper helps Dick over the wall while Greensheve watches; Dick sees Joanna with Goody Hatch inside.', 'House by the shore', ['Dick Shelton', 'Joanna Sedley', 'Goody Hatch', 'Greensheve', 'Capper'], 4),
    E(49, 'Another Watcher', 'Dick’s scout warns that more men are observing the house, forcing a careful withdrawal.', 'House by the shore', ['Dick Shelton', 'Greensheve', 'Capper'], 4),
  ]],
  [15, [
    E(0, 'The Men in the Dark', 'Dick learns that armed strangers have gathered near the watched house.', 'Shoreby downs', ['Dick Shelton', 'Greensheve'], 4),
    E(10, 'Reinforcements Arrive', 'Dick entrusts the larger force to Greensheve and positions his gathered men around the garden wall.', 'House by the shore', ['Dick Shelton', 'Greensheve'], 4),
    E(17, 'Swordplay in the Dark', 'Dick survives a fierce clash with an as yet unidentified armoured opponent.', 'House by the shore', ['Dick Shelton'], 5),
    E(25, 'The Opponent Yields', 'Dick accepts the unidentified knight’s surrender, stops the fighting, and calls to Lawless.', 'House by the shore', ['Dick Shelton', 'Lawless'], 4),
    E(35, 'Lantern and Recognition', 'The opponents learn they share an enemy, and Hawksley urges them to leave before Sir Daniel’s men arrive.', 'House by the shore', ['Dick Shelton', 'Hawksley'], 3),
  ]],
  [16, [
    E(0, 'At St. Bride’s Cross', 'Dick meets the still unnamed nobleman at the appointed cross.', 'St. Bride’s Cross', ['Dick Shelton'], 3),
    E(12, 'Joanna’s Guardian', 'Dick learns how Lord Foxham is connected to Joanna and asks for his support.', 'St. Bride’s Cross', ['Dick Shelton', 'Lord Foxham'], 3),
    E(20, 'An Alliance for Joanna', 'Sir Daniel’s proposed marriage for Joanna gives Dick and Foxham a common purpose.', 'St. Bride’s Cross', ['Dick Shelton', 'Lord Foxham'], 4),
  ]],
  [17, [
    E(0, 'A Plan by Water', 'Dick asks the former seaman Lawless to find a ship that can approach the guarded house.', 'Shoreby harbour', ['Dick Shelton', 'Lawless'], 3),
    E(12, 'Arblaster and the Good Hope', 'Lawless draws an old acquaintance and his sailor Tom into the attempt.', 'Shoreby harbour', ['Dick Shelton', 'Lawless', 'Captain Arblaster', 'Tom'], 3),
    E(25, 'The Good Hope Seized', 'Dick and two outlaws board the unattended Good Hope, mark it with a lamp, and fear the rising swell.', 'Good Hope', ['Dick Shelton'], 4),
    E(32, 'Foxham Accepts the Sea Plan', 'Dick returns to the landing and persuades Foxham that only a sea approach can evade Sir Daniel’s mounted watch.', 'Shoreby harbour', ['Dick Shelton', 'Lord Foxham'], 4),
    E(38, 'Arblaster Taken', 'At the alehouse Dick lures the drunken skipper outside, where the outlaws bind him and his crew.', 'Shoreby alehouse', ['Dick Shelton', 'Lawless', 'Lord Foxham', 'Captain Arblaster', 'Tom'], 5),
    E(45, 'The Good Hope Departs', 'Foxham’s followers board the captured vessel; Lawless steers Dick’s company out through the breakers.', 'Good Hope', ['Dick Shelton', 'Lawless', 'Lord Foxham'], 5),
  ]],
  [18, [
    E(0, 'Arrows in the Night', 'A signal exposes the rescue party to archers on shore.', 'Good Hope', ['Dick Shelton', 'Lawless', 'Lord Foxham', 'Hawksley'], 5),
    E(10, 'The Crew Turns Fearful', 'The frightened men accuse their leaders of betrayal as the ship pulls away.', 'Good Hope', ['Dick Shelton', 'Lawless'], 5),
    E(20, 'Lawless Holds the Ship', 'Lawless restores enough order to keep the battered vessel moving while Greensheve guards the helm.', 'Good Hope', ['Dick Shelton', 'Lawless', 'Greensheve'], 4),
  ]],
  [19, [
    E(0, 'Foxham’s Charge', 'Wounded Lord Foxham gives Dick papers and directions for the next stage of their cause.', 'Good Hope', ['Dick Shelton', 'Lord Foxham'], 4),
    E(21, 'The Foundering Vessel', 'Water rises in the Good Hope while Greensheve and Hawksley tear up the deck for a raft.', 'Good Hope', ['Dick Shelton', 'Lawless', 'Greensheve', 'Hawksley'], 5),
    E(30, 'The Stranded Company', 'The shipwrecked company waits aboard the grounded vessel for the tide to fall while Dick reassures Foxham.', 'Good Hope', ['Dick Shelton', 'Lawless', 'Lord Foxham'], 3),
    E(35, 'Men on the Shore', 'A wary armed group fires at Dick, Hawksley, Greensheve and the wounded Foxham, mistaking them for French raiders.', 'Shoreby coast', ['Dick Shelton', 'Greensheve', 'Lord Foxham', 'Hawksley'], 4),
  ]],
  [20, [
    E(0, 'Foxham’s Party Departs', 'The wounded Foxham is carried toward Holywood Abbey as Dick’s remaining volunteers separate.', 'Holywood road', ['Dick Shelton', 'Lawless', 'Lord Foxham'], 2),
    E(3, 'The Forest Den', 'Dick dismisses the remaining volunteers and walks with Lawless to a hidden earth shelter.', 'Black Arrow den', ['Dick Shelton', 'Lawless'], 2),
    E(20, 'A Friar’s Habit', 'They use clothing and cosmetics from the den to prepare a disguise for Shoreby.', 'Black Arrow den', ['Dick Shelton', 'Lawless'], 3),
    E(42, 'Testing the False Faces', 'The disguised pair meet another outlaw before continuing toward town.', 'Tunstall forest', ['Dick Shelton', 'Lawless', 'Capper'], 3),
  ]],
  [21, [
    E(0, 'The House in the Snow', 'Disguised as religious men, Dick and Lawless enter Sir Daniel’s guarded Shoreby house and follow Lady Brackley’s party.', 'Sir Daniel’s Shoreby house', ['Dick Shelton', 'Lawless', 'Lady Brackley'], 4),
    E(12, 'Alicia in the Stairway', 'Dick follows Lady Brackley’s party, then encounters a young lady who sees through more of his presence than he intended.', 'Shoreby house stair', ['Dick Shelton', 'Alicia Risingham', 'Lady Brackley'], 4),
    E(26, 'Joanna Recognizes Dick', 'Alicia brings the disguised visitor into Joanna’s chamber, where Joanna recognizes him.', 'Joanna’s chamber', ['Dick Shelton', 'Joanna Sedley', 'Alicia Risingham'], 3),
    E(45, 'Alicia Helps Them', 'Alicia interrupts the lovers’ talk and helps Dick plan his departure.', 'Joanna’s chamber', ['Dick Shelton', 'Joanna Sedley', 'Alicia Risingham'], 3),
    E(57, 'The Spy Finds a Tassel', 'A small spy discovers the token Dick dropped while hiding behind the arras.', 'Sir Daniel’s Shoreby house', ['Dick Shelton', 'The spy'], 4),
    E(58, 'Lawless in Drink', 'Dick finds Lawless drunk as the spy slips away with the token that could expose him.', 'Sir Daniel’s Shoreby house', ['Dick Shelton', 'Lawless', 'The spy'], 5),
    E(67, 'The Spy Is Killed', 'Dick catches the spy in the arras and kills him with his poniard.', 'Sir Daniel’s Shoreby house', ['Dick Shelton', 'Lawless', 'The spy'], 5),
  ]],
  [22, [
    E(0, 'The Dead Spy’s Warning', 'Dick and Lawless pin a black arrow and message to the dead spy before leaving his body in the house.', 'Sir Daniel’s Shoreby house', ['Dick Shelton', 'Lawless', 'The spy'], 4),
    E(14, 'Guests Discover the Body', 'Sir Daniel and Shoreby find the dead spy and confront the killing in the house.', 'Sir Daniel’s Shoreby house', ['Dick Shelton', 'Sir Daniel Brackley', 'Lord Shoreby', 'The spy'], 5),
    E(29, 'Joanna and Alicia Wait', 'The young women discuss Dick’s danger while he decides how to leave.', 'Joanna’s chamber', ['Dick Shelton', 'Joanna Sedley', 'Alicia Risingham'], 3),
    E(47, 'Taken to Sir Oliver', 'Guards seize Dick and bring him before the priest in the abbey.', 'Shoreby abbey', ['Dick Shelton', 'Sir Oliver Oates'], 5),
  ]],
  [23, [
    E(0, 'Before the Abbey Altar', 'Dick confronts Sir Oliver by the dead spy’s vigil; Lawless catches his eye before morning.', 'Shoreby abbey church', ['Dick Shelton', 'Sir Oliver Oates', 'Lawless', 'The spy'], 4),
    E(14, 'Lawless Joins the Service', 'Lawless reaches Dick beside Rutter’s vigil as the church fills.', 'Shoreby abbey church', ['Dick Shelton', 'Lawless', 'The spy'], 3),
    E(30, 'The Wedding Procession', 'The marriage procession arrives; black arrows kill Lord Shoreby and wound Sir Daniel while Dick and Lawless are trapped in the church.', 'Shoreby abbey church', ['Dick Shelton', 'Lawless', 'Joanna Sedley', 'Alicia Risingham', 'Lord Shoreby', 'Sir Daniel Brackley'], 5),
    E(40, 'Dick Is Recognized', 'Sir Oliver points Dick out beside the dead Shoreby, and Sir Daniel seizes the disguised outlaw.', 'Shoreby abbey church', ['Dick Shelton', 'Sir Oliver Oates', 'Sir Daniel Brackley', 'Lawless', 'Lord Shoreby'], 5),
    E(55, 'Joanna Appeals to Risingham', 'Joanna and Alicia appeal to the earl while Shoreby lies dead and his men carry Dick and Lawless away.', 'Shoreby abbey church', ['Dick Shelton', 'Joanna Sedley', 'Alicia Risingham', 'Earl Risingham', 'Sir Daniel Brackley', 'Lawless', 'Lord Shoreby'], 5),
  ]],
  [24, [
    E(0, 'Lawless’s Counsel', 'After the abbey disturbance, Lawless looks for a way to save Dick.', 'Shoreby abbey', ['Dick Shelton', 'Lawless'], 3),
    E(9, 'Before Earl Risingham', 'The earl questions Dick about a letter and the loyalties it exposes.', 'Risingham’s chamber', ['Dick Shelton', 'Earl Risingham'], 4),
    E(24, 'The Earl’s Decision', 'The contents of the letter sharpen Risingham’s anger and alter Dick’s position.', 'Risingham’s chamber', ['Dick Shelton', 'Earl Risingham'], 5),
  ]],
  [25, [
    E(0, 'Hiding by the Granary', 'Dick and Lawless run from immediate danger and take cover near the harbour.', 'Shoreby granary', ['Dick Shelton', 'Lawless'], 4),
    E(9, 'Arblaster Counts His Loss', 'The skipper and his companions lament the Good Hope, recognize Dick, and send Lawless fleeing.', 'Shoreby harbour', ['Dick Shelton', 'Captain Arblaster', 'Tom', 'Master Pirret', 'Lawless'], 4),
    E(27, 'The Captors’ Bargain', 'Dick tries to persuade Arblaster’s party to release him despite their grievance.', 'Shoreby harbour', ['Dick Shelton', 'Captain Arblaster', 'Tom', 'Master Pirret'], 4),
    E(49, 'The Tale of Hidden Gold', 'Dick improvises a story of secret wealth to divert his captors.', 'Shoreby harbour', ['Dick Shelton', 'Captain Arblaster', 'Tom', 'Master Pirret'], 4),
    E(64, 'The Chase through Shoreby', 'Dick outruns Tom, Pirret, and the sailors, then hides until the patrols pass.', 'Shoreby streets', ['Dick Shelton', 'Tom', 'Master Pirret'], 5),
  ]],
  [26, [
    E(0, 'A Fight on the Hill', 'Dick intervenes when several men attack an as yet unidentified young leader.', 'Shoreby hill', ['Dick Shelton'], 5),
    E(14, 'The Duke of Gloucester', 'The rescued fighter identifies himself and measures Dick’s courage.', 'Shoreby hill', ['Dick Shelton', 'Richard of Gloucester'], 3),
    E(39, 'Waiting at St. Bride’s Cross', 'Dick brings what he knows of Shoreby’s defenders to Gloucester’s council.', 'St. Bride’s Cross', ['Dick Shelton', 'Richard of Gloucester'], 4),
    E(50, 'The Trumpet Sounds', 'Gloucester’s force gathers and moves toward the town at dawn.', 'St. Bride’s Cross', ['Dick Shelton', 'Richard of Gloucester'], 5),
  ]],
  [27, [
    E(0, 'The First Streets', 'Gloucester’s advance meets scattered defenders at the edge of Shoreby.', 'Shoreby streets', ['Dick Shelton', 'Richard of Gloucester'], 4),
    E(14, 'Dick Sent Forward', 'The duke gives Dick a dangerous task in the fighting and assigns Dutton to watch him.', 'Shoreby streets', ['Dick Shelton', 'Richard of Gloucester', 'Dutton'], 5),
    E(20, 'Sir Daniel’s Men', 'Dick recognizes Sir Daniel commanding a body of armed men ahead.', 'Shoreby streets', ['Dick Shelton', 'Sir Daniel Brackley'], 5),
    E(28, 'The Charge', 'Mounted force breaks the defenders while Dick fights in the street and Gloucester strikes their rear.', 'Shoreby streets', ['Dick Shelton', 'Richard of Gloucester', 'Catesby'], 5),
  ]],
  [28, [
    E(0, 'The Barricade Holds', 'Dick hears from Dutton that Gloucester ordered him watched and sees how costly the defended post has been.', 'Shoreby barricade', ['Dick Shelton', 'Dutton'], 5),
    E(14, 'The Archers Advance', 'Arrows fall as the attacking force renews its push toward the barrier.', 'Shoreby barricade', ['Dick Shelton'], 5),
    E(20, 'Dick Turns the Fight', 'Dick holds the street while Gloucester meets Risingham in battle and the earl falls.', 'Shoreby barricade', ['Dick Shelton', 'Richard of Gloucester', 'Earl Risingham'], 5),
  ]],
  [29, [
    E(0, 'Seeking Joanna in the Sack', 'Dick leads his men through the newly captured town toward the abbey.', 'Shoreby streets', ['Dick Shelton'], 5),
    E(22, 'From the Abbey Tower', 'Dick climbs the abbey tower and sees Sir Daniel’s company escaping toward Holywood.', 'Shoreby abbey', ['Dick Shelton'], 4),
    E(36, 'The Duke’s Judgment', 'Dick meets Gloucester in the streets and claims Arblaster’s life as his reward while other captives face execution.', 'Shoreby streets', ['Dick Shelton', 'Richard of Gloucester', 'Catesby', 'Captain Arblaster'], 4),
    E(58, 'Arblaster’s Plea', 'The skipper confronts Dick with the cost of taking the Good Hope before Catesby gives Dick a horse for the pursuit.', 'Shoreby streets', ['Dick Shelton', 'Captain Arblaster', 'Catesby'], 4),
    E(74, 'Alicia on the Road', 'Dick reaches Alicia amid the violence of the sack and tries to help her.', 'Shoreby streets', ['Dick Shelton', 'Alicia Risingham'], 4),
  ]],
  [30, [
    E(0, 'Following the Snow Trail', 'Dick and his men track riders through the winter woods.', 'Tunstall forest', ['Dick Shelton', 'Alicia Risingham'], 4),
    E(18, 'Alicia Refuses Food', 'Alicia reproaches Dick over her kinsman’s death and refuses his help.', 'Tunstall forest', ['Dick Shelton', 'Alicia Risingham'], 3),
    E(39, 'Alicia’s Terms', 'Their talk turns playful and pointed as Alicia tests Dick’s intentions toward Joanna.', 'Tunstall forest', ['Dick Shelton', 'Alicia Risingham'], 3),
  ]],
  [31, [
    E(0, 'Toward the Encampment', 'Dick and Alicia approach the snowy camp, where he recognizes Bennet, Joanna, and Lady Brackley by the fire.', 'Tunstall forest', ['Dick Shelton', 'Alicia Risingham', 'Bennet Hatch', 'Joanna Sedley', 'Lady Brackley'], 4),
    E(14, 'Bennet’s Men', 'Dick calls on Bennet to yield; Joanna reaches him before Sir Daniel’s horsemen scatter his force, while Lady Brackley remains with the captured party.', 'Tunstall forest', ['Dick Shelton', 'Joanna Sedley', 'Bennet Hatch', 'Lady Brackley'], 5),
    E(33, 'Dick and Joan Reunited', 'Dick reaches Joanna and learns how she has fared amid the fighting.', 'Tunstall forest', ['Dick Shelton', 'Joanna Sedley', 'Alicia Risingham'], 3),
    E(52, 'Foxham and Gloucester', 'The noblemen and Catesby discuss Dick’s military service and Joanna’s marriage.', 'Holywood refectory', ['Dick Shelton', 'Lord Foxham', 'Richard of Gloucester', 'Catesby'], 4),
    E(70, 'A Late Arrival', 'As Dick leaves the refectory, a messenger kneels before Gloucester with news of another Yorkist victory.', 'Holywood refectory', ['Dick Shelton', 'Richard of Gloucester', 'Lord Foxham', 'Catesby'], 3),
  ]],
  [32, [
    E(0, 'Dick Faces Sir Daniel', 'Dick meets his former guardian on the road and blocks the way toward Holywood.', 'Holywood road', ['Dick Shelton', 'Sir Daniel Brackley'], 4),
    E(17, 'Sir Daniel’s Last Threat', 'Sir Daniel tests Dick’s mercy with a sudden armed move.', 'Holywood road', ['Dick Shelton', 'Sir Daniel Brackley'], 5),
    E(24, 'A Black Arrow Strikes', 'The old knight falls to an arrow before Dick can settle the encounter himself.', 'Holywood road', ['Dick Shelton', 'Sir Daniel Brackley'], 5),
    E(30, 'Ellis Duckworth Appears', 'Dick meets the outlaw at Sir Daniel’s body and hears that the Black Arrow company is disbanded.', 'Holywood road', ['Dick Shelton', 'Ellis Duckworth', 'Sir Daniel Brackley'], 4),
  ]],
  [33, [
    E(0, 'Before Gloucester', 'Foxham leads Joanna and Alicia to Gloucester, and Joanna refuses a different marriage.', 'Holywood church', ['Joanna Sedley', 'Alicia Risingham', 'Lord Foxham', 'Richard of Gloucester'], 3),
    E(12, 'Alicia and the Duke', 'Foxham proposes a husband for Alicia; her reply briefly unsettles the duke and wedding party.', 'Holywood church', ['Joanna Sedley', 'Alicia Risingham', 'Lord Foxham', 'Richard of Gloucester'], 2),
    E(22, 'The Wedding', 'Dick and Joan marry as Gloucester rides away with his army and Hamley courts Alicia at breakfast.', 'Holywood church', ['Dick Shelton', 'Joanna Sedley', 'Sir John Hamley', 'Alicia Risingham', 'Richard of Gloucester'], 2),
    E(23, 'Peace in the Forest', 'Dick and Joanna live together in the green forest beyond the violence of the war.', 'Tunstall forest', ['Dick Shelton', 'Joanna Sedley'], 1),
    E(24, 'The Two Old Men', 'Arblaster and Lawless draw pensions in Tunstall; Lawless eventually dies as Brother Honestus in the neighbouring abbey.', 'Tunstall hamlet', ['Captain Arblaster', 'Lawless'], 1),
  ]],
])
