import fs from 'node:fs/promises'
import path from 'node:path'
import { createRequire } from 'node:module'
import { fileURLToPath } from 'node:url'

const appPackage = path.resolve(import.meta.dirname, '../../../Plot' + 'Weave/package.json')
const require = createRequire(appPackage)
const { chromium } = require('playwright')
const browser = await chromium.launch({headless:true,executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe',args:['--no-proxy-server','--host-resolver-rules=MAP fonts.googleapis.com ~NOTFOUND, MAP fonts.gstatic.com ~NOTFOUND']})
const context = await browser.newContext({viewport:{width:1500,height:950}})
const root = path.resolve(import.meta.dirname,'../..')
const errors = []
await context.route('**/library/**',async route=>{
  const url = new URL(route.request().url())
  const name = decodeURIComponent(url.pathname.split('/library/')[1]??'')
  const file = path.resolve(root,'library',name)
  if (!file.startsWith(path.resolve(root,'library')+path.sep)) return route.abort()
  try {
    const body = await fs.readFile(file)
    const contentType = file.endsWith('.json')?'application/json':file.endsWith('.png')?'image/png':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream'
    await route.fulfill({status:200,body,contentType})
  } catch { await route.fulfill({status:404,body:'Missing local Library asset'}) }
})
const page = await context.newPage()
page.on('console',message=>{if(message.type()==='error')errors.push(message.text())})
page.on('pageerror',error=>errors.push(error.message))
await page.goto('http://127.0.0.1:5173/',{waitUntil:'domcontentloaded'})
await page.getByRole('button',{name:'Library',exact:true}).click()
await page.getByRole('heading',{name:'Library'}).waitFor()
await page.getByRole('textbox',{name:/Search the library/}).fill('Black Arrow')
await page.getByText('The Black Arrow: A Tale of the Two Roses',{exact:true}).waitFor()
await page.screenshot({path:fileURLToPath(new URL('./qa/library.png',import.meta.url)),fullPage:true})
await page.getByRole('button',{name:/Download \([\d,.]+ (?:KB|MB)\)/}).click()
await page.waitForURL(/#\/worlds\/black-arrow-world/, {timeout:60000})
await page.getByText('The Black Arrow: A Tale of the Two Roses',{exact:true}).first().waitFor({timeout:60000})
await page.waitForTimeout(3000)
await page.screenshot({path:fileURLToPath(new URL('./qa/dashboard.png',import.meta.url)),fullPage:true})
console.log('url',page.url())
const views=['timeline','characters','maps','calendar','items','relationships','arc','lore','factions','knowledge','settings']
for (const view of views) {
  await page.goto(`http://127.0.0.1:5173/#/worlds/black-arrow-world/${view}`,{waitUntil:'domcontentloaded'})
  await page.waitForTimeout(1200)
  const text=(await page.locator('main').innerText()).replace(/\s+/g,' ').slice(0,360)
  const images=await page.locator('main img').evaluateAll(xs=>xs.map(x=>({alt:x.alt,loaded:x.complete&&x.naturalWidth>0})))
  await page.screenshot({path:fileURLToPath(new URL(`./qa/${view}.png`,import.meta.url)),fullPage:true})
  console.log('view',view,JSON.stringify({text:text.slice(0,80),images:images.length,broken:images.filter(x=>!x.loaded)}))
  if(view==='lore' && !text.includes('Lore 4'))throw Error(`Initial lore reveal gate failed: ${text}`)
}
await page.goto('http://127.0.0.1:5173/#/worlds/black-arrow-world/',{waitUntil:'domcontentloaded'})
await page.waitForTimeout(1800)
console.log('returnDashboard', (await page.locator('main').innerText()).replace(/\s+/g,' ').slice(0,400))
console.log('cursorControl', await page.getByText('Set where you have read to',{exact:true}).first().evaluate(x=>x.outerHTML))
await page.getByText('Set where you have read to',{exact:true}).click()
await page.waitForTimeout(900)
console.log('readButtons',await page.getByRole('button',{name:'Read to here'}).count())
await page.getByRole('button',{name:'Read to here'}).last().click()
await page.waitForTimeout(800)
for (const view of ['characters','maps','items','relationships','lore','factions','knowledge']) {
  await page.goto(`http://127.0.0.1:5173/#/worlds/black-arrow-world/${view}`,{waitUntil:'domcontentloaded'})
  await page.waitForTimeout(1100)
  const text=(await page.locator('main').innerText()).replace(/\s+/g,' ').slice(0,220)
  const broken=await page.locator('main img').evaluateAll(xs=>xs.filter(x=>!x.complete||x.naturalWidth===0).map(x=>x.alt))
  await page.screenshot({path:fileURLToPath(new URL(`./qa/${view}-end.png`,import.meta.url)),fullPage:true})
  console.log('endView',view,JSON.stringify({text,broken}))
  if(view==='lore' && !text.includes('Lore 6'))throw Error(`Wedding lore reveal gate failed: ${text}`)
  if(view==='knowledge' && !text.includes('Knowledge 10'))throw Error(`Wedding knowledge reveal gate failed: ${text}`)
  if(view==='maps') console.log('mapButtons',await page.locator('main button').allTextContents())
}
await page.goto('http://127.0.0.1:5173/#/worlds/black-arrow-world/maps',{waitUntil:'domcontentloaded'})
await page.waitForTimeout(900)
for (const name of ['Tunstall Forest','Holywood Abbey','The Moat House','Shoreby','The Good Hope','Shoreby Abbey','Sir Daniel’s Shoreby House','Tunstall Hamlet']) {
  await page.getByRole('button',{name,exact:true}).first().click()
  await page.waitForTimeout(750)
  const slug=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')
  await page.screenshot({path:fileURLToPath(new URL(`./qa/map-${slug}.png`,import.meta.url)),fullPage:true})
  const imgs=await page.locator('main img').evaluateAll(xs=>xs.map(x=>({alt:x.alt,loaded:x.complete&&x.naturalWidth>0})))
  console.log('mapLayer',name,JSON.stringify({broken:imgs.filter(x=>!x.loaded),mapText:(await page.locator('main').innerText()).replace(/\s+/g,' ').slice(0,100)}))
}
await page.getByRole('button',{name:'Next scene in this chapter'}).click()
await page.getByRole('button',{name:'Next scene in this chapter'}).click()
console.log('finalCursor',(await page.locator('header').innerText()).replace(/\s+/g,' '))
await page.goto('http://127.0.0.1:5173/#/worlds/black-arrow-world/characters',{waitUntil:'domcontentloaded'})
await page.waitForTimeout(650)
console.log('weddingCharacters',(await page.locator('main').innerText()).replace(/\s+/g,' ').slice(0,170))
const weddingPortraits=await page.locator('main img').evaluateAll(xs=>({count:xs.length,broken:xs.filter(x=>!x.complete||x.naturalWidth===0).map(x=>x.alt)}))
console.log('weddingPortraits',weddingPortraits)
if(weddingPortraits.count!==32 || weddingPortraits.broken.length)throw Error('Final character portrait load failed')
await page.goto('http://127.0.0.1:5173/#/worlds/black-arrow-world/items',{waitUntil:'domcontentloaded'})
await page.waitForTimeout(650)
const weddingItemArt=await page.locator('main img').evaluateAll(xs=>({count:xs.length,broken:xs.filter(x=>!x.complete||x.naturalWidth===0).map(x=>x.alt)}))
console.log('weddingItemArt',weddingItemArt)
if(weddingItemArt.count!==6 || weddingItemArt.broken.length)throw Error('Final item artwork load failed')
await page.goto('http://127.0.0.1:5173/#/worlds/black-arrow-world/maps',{waitUntil:'domcontentloaded'})
await page.getByRole('button',{name:'Next scene in this chapter'}).click()
await page.getByRole('button',{name:'Next scene in this chapter'}).click()
await page.goto('http://127.0.0.1:5173/#/worlds/black-arrow-world/lore',{waitUntil:'domcontentloaded'})
await page.waitForTimeout(650)
const closingLore=(await page.locator('main').innerText()).replace(/\s+/g,' ')
if(!closingLore.includes('Lore 7')||!closingLore.includes('Closing Chronology'))throw Error(`Closing lore reveal gate failed: ${closingLore.slice(0,220)}`)
console.log('closingLore',closingLore.slice(0,130))
await page.goto('http://127.0.0.1:5173/#/worlds/black-arrow-world/settings',{waitUntil:'domcontentloaded'})
await page.getByRole('button',{name:'Turn off reading mode'}).click()
await page.waitForTimeout(500)
for(const view of ['manuscript','corkboard','structure']) {
  await page.goto(`http://127.0.0.1:5173/#/worlds/black-arrow-world/${view}`,{waitUntil:'domcontentloaded'})
  await page.waitForTimeout(900)
  await page.screenshot({path:fileURLToPath(new URL(`./qa/${view}-editor.png`,import.meta.url)),fullPage:true})
  const broken=await page.locator('main img').evaluateAll(xs=>xs.filter(x=>!x.complete||x.naturalWidth===0).map(x=>x.alt))
  console.log('editorView',view,JSON.stringify({text:(await page.locator('main').innerText()).replace(/\s+/g,' ').slice(0,260),broken}))
}
console.log('errors',errors)
if(errors.length)throw Error(errors.join('\n'))
await browser.close()
