// Standing descriptions are pinned to the reader's first encounter. Later
// identities and outcomes belong in gated knowledge and event state.
export const characters = [
  ['Dick Shelton', 'Sir Daniel’s young ward, a skilled crossbowman who wants a clear account of his father’s death.'],
  ['Bennet Hatch', 'A weathered Tunstall retainer charged with mustering and defending Sir Daniel’s men.'],
  ['Appleyard', 'An old Tunstall archer whose years of service have not softened his tongue.'],
  ['Sir Oliver Oates', 'The local priest at Tunstall, outwardly dutiful and deeply anxious when the past is questioned.'],
  ['Sir Daniel Brackley', 'A powerful guardian and fighting knight whose loyalties shift with the fortunes of war.'],
  ['Jack Matcham', 'A slight young ward travelling in fear of Sir Daniel and asking Dick for help through the fen.'],
  ['Hugh Ferryman', 'The ferryman on the River Till, caught between duty to Sir Daniel and fear of the forest company.'],
  ['John-a-Fenne', 'A Black Arrow archer who watches the islands and willows of the Till.'],
  ['Lawless', 'A resourceful forest outlaw and former sailor, given to ale, quick improvisation, and dangerous loyalty.'],
  ['Ellis Duckworth', 'A fierce leader of the Black Arrow company who demands redress from Sir Daniel’s household.'],
  ['Selden', 'One of Sir Daniel’s armed men, helping organize the newly arrived levy at Kettley.'],
  ['Carter', 'A wounded Tunstall retainer who knows more about old household affairs than he wishes to say.'],
  ['Goody Hatch', 'A practical woman of the Moat House household who speaks with Dick about the missing ward.'],
  ['Joanna Sedley', 'A young ward of rank whose choices are constrained by guardians, soldiers, and marriage plans.'],
  ['Greensheve', 'A forester of the Black Arrow company who scouts and fights beside Dick.'],
  ['Lord Shoreby', 'A Lancastrian nobleman whose household and proposed marriage place him close to Sir Daniel.'],
  ['Capper', 'A Black Arrow scout who carries news through Shoreby’s guarded streets.'],
  ['Lord Foxham', 'A nobleman with an interest in the ward held by Sir Daniel.'],
  ['Captain Arblaster', 'Master of the Good Hope, proud of his vessel and wary of strangers along the harbour.'],
  ['Alicia Risingham', 'A quick-witted noblewoman travelling under the protection of her family.'],
  ['Earl Risingham', 'A powerful Lancastrian earl accustomed to weighing letters, loyalties, and prisoners.'],
  ['Tom', 'A sailor serving under Arblaster, vocal about the loss of the Good Hope.'],
  ['Master Pirret', 'A Shoreby companion of Arblaster who sees opportunity in a captive.'],
  ['Richard of Gloucester', 'A young Yorkist commander with a crooked back, acute judgment, and a taste for battle.'],
  ['Dutton', 'A man in Gloucester’s service assigned to follow Dick into the fighting.'],
  ['The spy', 'A small, stealthy servant searching Sir Daniel’s house and carrying a token that could expose Dick.'],
  ['Sir John Hamley', 'A young knight in Foxham’s kinship whose proposed marriage is entangled with the wards’ futures.'],
  ['Hawksley', 'A capable retainer who warns the shore fighters that Sir Daniel’s men may arrive.'],
  ['Lady Brackley', 'Sir Daniel’s wife, moving among the guarded rooms and obligations of his household.'],
  ['Clipsby', 'A Tunstall peasant formerly tied to the Walsinghams, outspoken about the shifting lord who now demands his service.'],
  ['Catesby', 'A capable officer serving Richard of Gloucester, courteous in speech and alert to the duke’s severe commands.'],
  ['Throgmorton', 'A household messenger chosen for a dangerous errand from the besieged Moat House.'],
]

// map, marker X, marker Y measured upward from the bottom edge, description.
// Gateway markers are separate records where a broader place opens a submap.
export const locations = [
  ['Tunstall hamlet','region',490,620,'A small wooded valley of timber houses, church, stone cross, and bridge below the road to the Moat House.','village'],
  ['Tunstall road','village',900,500,'The rising road from the hamlet bridge toward Sir Daniel’s forest and moated residence.'],
  ['Tunstall green','village',760,555,'Open grass by the stone cross where neighbours gather within sight of the church and bridge.'],
  ['Appleyard’s house','village',380,840,'The old archer’s plain cottage, sparsely furnished and close to the Tunstall green.'],
  ['Tunstall church','village',1095,810,'A parish church among yews, where a message is pinned for the household to find.'],
  ['Kettley inn','region',250,900,'The village inn where Sir Daniel lodges with armed men and receives news from the fighting.'],
  ['Fen causeway','region',760,330,'An uneven raised track across wet fen, bordered by reeds and treacherous ground.'],
  ['River Till ferry','region',1110,530,'A crossing on the broad, sluggish Till, with willow-fringed islands and a watched landing.'],
  ['River Till bank','region',1040,560,'The firmer rising ground beyond the ferry where the travellers regain the forest road.'],
  ['Tunstall forest','region',540,780,'Extensive oak and elm woodland between the hamlet, river, abbey, and coast.','forest'],
  ['Black Arrow camp','forest',1225,850,'A sheltered hollow and fire where the foresters gather, eat, and plan their ambushes.'],
  ['Forest ridge','forest',660,765,'A heathy rise overlooking the road down which Sir Daniel’s men ride.'],
  ['Forest stream','forest',265,340,'A small watercourse among willows where two weary travellers seek drink and shelter.'],
  ['Forest hillside','forest',735,510,'Sloping ground above the stream where the forest path climbs toward Tunstall.'],
  ['Moat House','region',290,490,'Sir Daniel’s defended residence beyond Tunstall, with water, walls, chapel, and hidden passages.','moat'],
  ['Moat House gate','moat',400,365,'The guarded approach across the moat into the house and its inner yard.'],
  ['Moat House hall','moat',610,580,'The principal chamber for meals, orders, and difficult questions before the household.'],
  ['Moat House chapel wing','moat',930,555,'Rooms beside and above the private chapel, separated from the main hall.'],
  ['Room over the chapel','moat',1225,830,'An assigned upper chamber with old furniture and a concealed opening beneath the floor.'],
  ['Moat House passage','moat',1230,220,'A branching dark way beneath the chapel rooms, damp and narrow in its lower reaches.'],
  ['Moat House moat','moat',195,470,'The water barrier around Sir Daniel’s residence, dangerous to cross under fire.'],
  ['Forest road','forest',755,225,'The woodland route on which fugitives and outlaws encounter one another.'],
  ['Shoreby','region',1210,380,'A fortified coastal town with harbour, abbey, noble houses, and streets fought over by rival forces.','shoreby'],
  ['Shoreby alehouse','shoreby',405,530,'A low harbour tavern where scouts watch movement through the town.'],
  ['Shoreby streets','shoreby',640,545,'Narrow streets and lanes joining the harbour, abbey, houses, and eastern approach.'],
  ['Shoreby downs','shoreby',1180,840,'Open rising ground beyond the town where armed parties can be followed by torchlight.'],
  ['House by the shore','shoreby',265,715,'A watched house near the sea with a garden wall and lit rooms visible from outside.'],
  ['St. Bride’s Cross','shoreby',1130,715,'A roadside cross outside Shoreby where prisoners and allies can confer away from the houses.'],
  ['Shoreby harbour','shoreby',375,385,'The waterfront of moored ships and working boats below the town.','ship'],
  ['Good Hope','ship',710,500,'Arblaster’s vessel moored at Shoreby harbour.'],
  ['Shoreby coast','shoreby',85,555,'A stretch of surf and shingle adjoining the harbour and roads into town.'],
  ['Black Arrow den','forest',105,870,'A concealed earth shelter under twisted oaks, stocked with clothes and provisions.'],
  ['Sir Daniel’s Shoreby house','shoreby',945,510,'A guarded town residence with a stair, guest rooms, and upper chambers.','shoreby-house'],
  ['Shoreby house stair','shoreby-house',190,575,'A polished oak stair rising from the guarded entrance to the family rooms.'],
  ['Joanna’s chamber','shoreby-house',1125,360,'An upper room where Joanna receives visitors under the household’s watch.'],
  ['Shoreby abbey','shoreby',800,810,'A large abbey with a church and private rooms used for worship and custody.','shoreby-abbey'],
  ['Shoreby abbey church','shoreby-abbey',610,520,'The nave and choir where worshippers and soldiers gather.'],
  ['Risingham’s chamber','shoreby-abbey',1095,860,'A private room in the abbey where the earl examines a letter and questions Dick.'],
  ['Shoreby granary','shoreby',470,370,'A harbour storehouse whose shadow offers brief cover from pursuit.'],
  ['Shoreby hill','shoreby',1180,575,'A rise outside the walls from which the approaches to battle can be seen.'],
  ['Shoreby barricade','shoreby',990,530,'A defended street obstruction that becomes a vital point in the battle.'],
  ['Holywood Abbey','region',170,190,'An abbey near Tunstall forest, with a church and refectory for refuge and council.','holywood'],
  ['Holywood road','region',390,230,'The road through woods toward the abbey, narrow enough for a fugitive to be confronted.'],
  ['Holywood church','holywood',505,525,'The abbey church and chancel where the gathered lords confer.'],
  ['Holywood refectory','holywood',1010,545,'The abbey dining hall used by the lords and their followers after the fighting.'],
]

export const maps = [
  ['region',null,'Tunstall, the Till, and Shoreby','Interpretive regional map of the forested inland valley, fen crossing, abbey, and coastal town.'],
  ['village','region','Tunstall Hamlet','Interpretive village plan of the bridge, green, church, cottages, and rising road.'],
  ['forest','region','Tunstall Forest','Interpretive woodland chart of the ambush road, ridge, stream, and Black Arrow shelters.'],
  ['moat','region','The Moat House','Invented plan of Sir Daniel’s moat, gate, hall, chapel wing, chamber, and underground passage.'],
  ['shoreby','region','Shoreby','Interpretive town map of the harbour, abbey, guarded houses, downs, and battle streets.'],
  ['ship','shoreby','The Good Hope','Invented deck plan of Arblaster’s vessel based on the narrated night voyage.'],
  ['shoreby-house','shoreby','Sir Daniel’s Shoreby House','Invented plan of the guarded town residence, stairs, and upper chamber.'],
  ['shoreby-abbey','shoreby','Shoreby Abbey','Invented plan of the abbey church and adjoining chamber used by Risingham.'],
  ['holywood','region','Holywood Abbey','Invented abbey plan for the approach, church, and refectory.'],
]
