import fs from 'node:fs'
import { maps, locations, characters as characterDefs, items as itemDefs } from './world-ledger.mjs'
import { chapterPlans, withCuts } from './story-ledger.mjs'
import { sourceSections, narrativeText, sourceEdition, sourceUrl, sourceSha256, normalize, countWords } from './source-text.mjs'

const W='a-princess-of-mars-world',T='mars-timeline',now=Date.UTC(2026,8,21),ref=(k,v)=>`mars-${k}-${v}`,stamp={worldId:W,createdAt:now,updatedAt:now}
const coords={
  hudson:[1260,760],'arizona-hills':[610,530],'arizona-cave':[900,690],barsoom:[760,510],korad:[470,310],incubator:[750,780],'korad-plaza':[420,500],'carter-quarters':[300,570],'thark-city':[590,285],'thark-palace':[960,520],'thark-outskirts':[750,120],warhoon:[1150,280],'warhoon-dungeon':[1160,310],'warhoon-arena':[1190,330],'atmosphere-gate':[1270,470],'factory-entrance':[120,510],'pump-room':[770,510],'control-room':[1400,510],'zodanga-gate':[970,435],'zodanga-barracks':[1120,670],'than-palace':[770,510],'dejah-apartment':[650,600],'palace-roof':[800,700],'zodanga-throne':[780,500],'helium-gate':[1050,660],'greater-helium':[470,520],'lesser-helium':[1120,480],'helium-palace':[450,570],'helium-garden':[520,510],desert:[770,410]
}
const blobs=[]
function image(kind,key,path){const url=`library/a-princess-of-mars/${path??`art/${kind}/${key}.png`}`,disk=new URL(`../../${url}`,import.meta.url);if(!fs.existsSync(disk))throw Error(`Missing artwork ${url}`);const b=fs.readFileSync(disk);if(b.toString('hex',0,8)!=='89504e470d0a1a0a')throw Error(`Not PNG ${url}`);const id=ref('image',`${kind}-${key}`);blobs.push({...stamp,id,mimeType:'image/png',url});return {id,width:b.readUInt32BE(16),height:b.readUInt32BE(20)}}
const mapLayers=maps.map(([key,parent,name,description],i)=>{const a=image('map',key,`maps/${key}.png`);return {...stamp,id:ref('map',key),name,description,parentMapId:parent?ref('map',parent):null,imageId:a.id,imageWidth:a.width,imageHeight:a.height,scalePixelsPerUnit:null,scaleUnit:null,levelGroupId:null,levelIndex:i,levelLabel:null}})
const gateway={korad:'thark','zodanga-gate':'zodanga','helium-gate':'helium','atmosphere-gate':'atmosphere'}
const rootMapFor=new Set(['hudson','arizona-hills','arizona-cave'])
const childLocMap={incubator:'thark','korad-plaza':'thark','carter-quarters':'thark','thark-palace':'thark','thark-outskirts':'thark','zodanga-barracks':'zodanga','than-palace':'zodanga','dejah-apartment':'zodanga','palace-roof':'zodanga','zodanga-throne':'zodanga','greater-helium':'helium','lesser-helium':'helium','helium-palace':'helium','helium-garden':'helium','factory-entrance':'atmosphere','pump-room':'atmosphere','control-room':'atmosphere'}
const locationMarkers=locations.map(([key,_map,name,description])=>{const map=rootMapFor.has(key)?'arizona':(childLocMap[key]??'barsoom');return {...stamp,id:ref('loc',key),name,description,mapLayerId:ref('map',map),linkedMapLayerId:gateway[key]?ref('map',gateway[key]):null,x:coords[key][0],y:coords[key][1],iconType:gateway[key]?'building':'landmark',imageId:image('locations',key).id,tags:[],factionId:null}})
const characters=characterDefs.map(([key,name,aliases,description,color])=>({...stamp,id:ref('char',key),name,aliases,description,color,portraitImageId:image('characters',key).id,isAlive:!['powell','bar','keeper','tal'].includes(key),birthDate:null,tags:[]}))
const items=itemDefs.map(([key,name,description,iconType])=>({...stamp,id:ref('item',key),name,description,iconType,imageId:image('items',key).id,tags:[]}))
const chapters=[],events=[],sceneTexts=[],characterSnapshots=[],itemPlacements=[];let order=0,previous=0
const deathAt={powell:[1,2],bar:[18,2],keeper:[20,2],tal:[24,2]}
const knownMentions={dejah:/Dejah/i,tars:/Tars/i,sola:/Sola/i,woola:/Woola/i,tal:/Tal Hajus/i,sab:/Sab Than/i,kantos:/Kantos/i}
for(let ci=0;ci<sourceSections.length;ci++){
 const s=sourceSections[ci],plan=withCuts(s,chapterPlans[ci]),paras=s.text.split(/\n{2,}/),chapterId=ref('chapter',ci+1)
 chapters.push({...stamp,id:chapterId,timelineId:T,number:ci+1,title:s.title,synopsis:plan.map(x=>x.description).join(' '),notes:`Original source heading: ${s.sourceHeading}`,wordGoal:countWords(s.text)})
 for(let ei=0;ei<plan.length;ei++){
  const e=plan[ei],id=ref('event',`${ci+1}-${ei+1}`),cast=e.cast,day=ci===26?3300+ei*.35:ci===27?3302+ei*.35:ci*2+ei*.35,mentioned=Object.entries(knownMentions).filter(([k,re])=>!cast.includes(k)&&re.test(e.description)).map(([k])=>ref('char',k))
  const threadKeys=[ci<3?'earth-to-mars':'',ci>=7&&ci<=25?'rescue':'',ci>=12&&ci<=26?'love':'',ci>=15&&ci<=25?'helium-war':'',ci>=26?'atmosphere':''].filter(Boolean)
  const motifKeys=[/custom|language|misread|word|telepath|thought/i.test(e.title+' '+e.description)?'communication':'',/kind|mercy|compassion|friend|love/i.test(e.title+' '+e.description)?'compassion':'',/dead|dying|air|ruin|extinct/i.test(e.title+' '+e.description)?'dying-world':'',/rank|combat|duel|fight|battle/i.test(e.title+' '+e.description)?'honor':''].filter(Boolean)
  events.push({...stamp,id,chapterId,timelineId:T,title:e.title,description:e.description,locationMarkerId:ref('loc',e.location),involvedCharacterIds:cast.map(k=>ref('char',k)),mentionedCharacterIds:mentioned,involvedItemIds:e.items.map(k=>ref('item',k)),threadIds:threadKeys.map(k=>ref('thread',k)),motifIds:motifKeys.map(k=>ref('motif',k)),sortOrder:order++,travelDays:Math.max(0,day-previous),inWorldTime:day,tension:e.tension,tags:[],structureBeat:null,status:'complete',povCharacterId:ref('char',ci===0&&ei===0?'burroughs':'carter'),isFlashback:false});previous=day
  const text=paras.slice(e.cut,plan[ei+1]?.cut??paras.length).join('\n\n');sceneTexts.push({...stamp,id:ref('scene',`${ci+1}-${ei+1}`),eventId:id,text,wordCount:countWords(text)})
  cast.forEach((key,i)=>{const loc=locationMarkers.find(x=>x.id===ref('loc',e.location)),death=deathAt[key],alive=!death||ci+1<death[0]||(ci+1===death[0]&&ei<death[1]);characterSnapshots.push({...stamp,id:ref('snapshot',`${ci+1}-${ei+1}-${key}`),characterId:ref('char',key),eventId:id,isAlive:alive,currentLocationMarkerId:loc.id,currentMapLayerId:loc.mapLayerId,inventoryItemIds:key==='carter'?e.items.map(k=>ref('item',k)):[],inventoryNotes:key==='carter'&&e.items.length?`Uses or carries ${e.items.map(k=>itemDefs.find(x=>x[0]===k)[1]).join(', ')}.`:'',travelModeId:null,sortKey:(ci+1)+(ei+1)/100,statusNotes:`${characterDefs.find(x=>x[0]===key)[1]} ${statusFor(key,e.title,e.description,i)}.`})})
  e.items.forEach((key,i)=>itemPlacements.push({...stamp,id:ref('placement',`${ci+1}-${ei+1}-${key}`),itemId:ref('item',key),eventId:id,locationMarkerId:ref('loc',e.location),sortKey:i,notes:`Active during “${e.title}”.`}))
 }
}
function statusFor(key,title,desc,i){const verbs={carter:'acts at the center of',burroughs:'records and safeguards',powell:'shares the danger of',tars:'weighs duty and judgment during',sola:'responds with wary compassion during',dejah:'holds to Heliumite dignity during',woola:'guards Carter fiercely during',lorquas:'exercises a jed’s authority during',sarkoja:'watches for advantage during',tal:'asserts fearful rule during',bar:'defends his command during',dak:'seizes opportunity during',kantos:'brings a Heliumite officer’s skill to',keeper:'entrusts the factory secret during',assistant:'betrays his charge during',thane:'protects Zodangan power during',sab:'presses his claim during',tardos:'speaks for Helium during',mors:'acts as Dejah’s father and Helium’s jed during',matai:'is invoked as sacred authority during'};return `${verbs[key]??'takes a distinct part in'} “${title}”${i?`, specifically as ${desc.charAt(0).toLowerCase()+desc.slice(1)}`:''}`}
const event=(c,e=1)=>ref('event',`${c}-${e}`)
const plotThreads=[['earth-to-mars','From Arizona to Barsoom','Carter’s unexplained passage joins an earthly frame to a lived Martian account.'],['rescue','The Road to Dejah Thoris','Captivity, escape, pursuit, and war repeatedly turn on reaching and protecting the Princess of Helium.'],['love','Words and Love','Earthly declarations and Barsoomian customs obscure a bond that actions make increasingly clear.'],['helium-war','War for Helium','Thark, Zodanga, and Helium move from private conflict toward open alliance and battle.'],['atmosphere','The Breath of Barsoom','The planet’s engineered air remains a distant wonder until its failure threatens every living thing.']].map(([k,name,description])=>({...stamp,id:ref('thread',k),name,description,color:'#9a5c45',status:'complete',tags:[]}))
const motifs=[['communication','Speech, Thought, and Misunderstanding','Language, telepathy, silence, and custom determine what characters can trust.'],['compassion','Compassion Against Custom','Kindness to animals, captives, children, and enemies unsettles inherited Martian rules.'],['dying-world','A Dying World','Ruins, empty seas, scarce water, and manufactured air make decline visible everywhere.'],['honor','Combat and Honor','Personal combat confers rank, allegiance, and political legitimacy across Barsoom.']].map(([k,name,description])=>({...stamp,id:ref('motif',k),name,description,color:'#795e4b',tags:[]}))
const relationshipDefs=[['carter','dejah','Protector and captive','positive','Carter claims the duty of protecting the Princess of Helium.',event(10,4)],['carter','tars','Rivals becoming allies','positive','Courage and mutual obligation gradually overcome the fact of captivity.',event(3,3)],['carter','sola','Trusted friends','positive','Sola teaches Carter and he trusts her compassion.',event(4,2)],['carter','woola','Master and devoted calot','positive','Kind treatment turns an assigned guard into a loyal companion.',event(5,3)],['sola','tars','Daughter and unknowing father','positive','Sola knows the father whose identity was hidden from him.',event(15,3)],['sola','sarkoja','Victim and persecutor','negative','Sarkoja polices Sola’s difference and carries the secret of her mother.',event(9,2)],['tars','tal','Chieftain and tyrant','negative','Tars serves the jeddak whose cruelty destroyed the woman he loved.',event(24,3)],['dejah','sab','Prisoner and unwanted suitor','negative','Sab Than uses war and confinement to press a political marriage.',event(22,1)],['carter','kantos','Comrades','positive','The prisoners of Warhoon become operational partners.',event(19,1)],['dejah','tardos','Granddaughter and grandfather','positive','The princess belongs to the ruling house of Helium.',event(26,4)],['dejah','mors','Daughter and father','positive','Mors Kajak commands Lesser Helium and searches for his daughter.',event(19,2)] ]
const relationships=relationshipDefs.map(([a,b,label,sentiment,description,start],i)=>({...stamp,id:ref('relationship',i+1),characterAId:ref('char',a),characterBId:ref('char',b),label,sentiment,description,strength:6,isBidirectional:true,startEventId:start}))
const relationshipSnapshots=[[0,event(13,3),'Love divided by custom','mixed','Carter’s declaration and Dejah’s response are understood differently.',7],[0,event(25,4),'Betrothed lovers','positive','Dejah answers Carter’s plea after Zodanga falls.',10],[1,event(24,4),'Allied chieftains','positive','Tars makes Carter a Thark chieftain and marches with him.',10],[4,event(24,2),'Father and daughter reunited','positive','Tars accepts Sola openly after learning her identity.',10]].map(([ri,eventId,label,sentiment,description,strength],i)=>({...stamp,id:ref('relationship-snapshot',i+1),relationshipId:relationships[ri].id,eventId,label,sentiment,description,strength,isActive:true,sortKey:i}))
const loreCategories=[{...stamp,id:ref('lore-category','edition'),name:'Edition and Reading',color:'#8e674d',sortOrder:0},{...stamp,id:ref('lore-category','barsoom'),name:'Barsoom',color:'#a64f3c',sortOrder:1}]
const lorePages=[['source','edition','Source Edition',`Scene drafts reproduce every retained word of ${sourceEdition}. Exact source: ${sourceUrl}. SHA-256: ${sourceSha256}. The Gutenberg header, licence, delimiters, illustration placeholders and captions, contents, and illustrations list are excluded; title, byline, dedication, foreword, headings, and narrative are retained. Original English; no translator. Public domain in the United States.`,event(1)],['boundaries','edition','Extraction and Reconstruction','Extraction begins at the title and ends with the final narrative sentence. Front matter is attached to Chapter I. Event cuts occur at paragraph boundaries, and validation reconstructs the normalized retained source without omission, duplication, or reordering.',event(1)],['calendar','edition','Editorial Chronology','The Martian arrival is day zero because the source gives relative durations rather than a dated Barsoomian calendar. Travel and elapsed values follow explicit nights, marches, the thirty-day arrival at Thark, and the nine years in Helium; smaller intervals are editorial approximations.',event(1)],['maps','edition','Map Method','The Barsoom chart is interpretive because the novel supplies relationships among cities and waterways rather than surveyed coordinates. City maps and the atmosphere-factory plan are invented from described movement. Marker coordinates rise from the bottom edge.',event(3,1)],['name','barsoom','Barsoom and Jasoom','The inhabitants call Mars Barsoom and Earth Jasoom. Carter learns those names only after acquiring the language.',event(11,2)],['air','barsoom','The Atmosphere Plant','Ancient engineering maintains the air of the dying planet through a guarded factory and a secret telepathic combination.',event(20,2)],['green','barsoom','Green Martian Communities','The nomadic hordes occupy ancient cities, rear children communally, and organize status around combat and captured metal.',event(7,2)],['red','barsoom','The Red Nations','Red Martian city-states preserve science, agriculture, aerial navies, dynastic rule, and rivalry along the waterways.',event(11,3)]].map(([k,c,title,body,visibleFromEventId])=>({...stamp,id:ref('lore',k),categoryId:ref('lore-category',c),title,body,visibleFromEventId,tags:[],coverImageId:null,linkedEntityIds:[]}))
const factDefs=[['mars','Carter is on Mars','The two moons and alien landscape establish that Carter has reached Mars.',event(3,1),['carter']],['dejah','The captive is Dejah Thoris','The red woman identifies herself as the daughter of Mors Kajak of Helium.',event(10,1),['carter','dejah']],['tarsfather','Tars Tarkas is Sola’s father','Sola names the warrior who never knew she survived.',event(15,3),['carter','sola']],['factory','Barsoom’s air is manufactured','The keeper explains that the factory renews the planet’s atmosphere.',event(20,2),['carter','keeper']],['prisoner','Dejah is held in Zodanga','Kantos reports the princess’s capture and the political pressure surrounding Helium.',event(21,1),['carter','kantos']],['love','Dejah understood Carter’s love','Their reunion resolves the earlier difference between Earth and Barsoomian courtship.',event(22,3),['carter','dejah']],['thark','Tars Tarkas is Jeddak of Thark','Victory over Tal Hajus gives Tars leadership of the horde.',event(24,4),['carter','tars','sola']],['failure','The atmosphere plant has stopped','Helium receives word that the factory’s machinery has failed.',event(27,2),['carter','dejah','tardos','mors']]]
const knowledgeFacts=factDefs.map(([k,title,description,at])=>({...stamp,id:ref('fact',k),title,description,readerLearnsAtEventId:at,originEventId:at,tags:[]})),knowledgeReveals=factDefs.flatMap(([k,,,at,who])=>who.map((p,i)=>({...stamp,id:ref('reveal',`${k}-${p}`),factId:ref('fact',k),characterId:ref('char',p),eventId:at,note:'Learned through direct observation, testimony, or shared action.'})))
const factionDefs=[['tharks','Tharks','A green Martian horde occupying dead cities and roaming the southern sea bottoms.','#5d7154'],['warhoons','Warhoons','A rival green horde whose arena turns captives into public combat.','#535d49'],['heliumites','Helium','The red Martian nation ruled by Tardos Mors from the twin cities.','#ae5a48'],['zodangans','Zodanga','Helium’s rival city-state under Than Kosis and Sab Than.','#8b493e']]
const factions=factionDefs.map(([k,name,description,color])=>({...stamp,id:ref('faction',k),name,description,color,tags:[],coverImageId:null}))
const factionMemberships=[['tharks','tars','Chieftain',event(3,3)],['tharks','sola','Community woman',event(4,2)],['tharks','lorquas','Jed',event(4,2)],['tharks','sarkoja','Senior woman',event(4,2)],['tharks','tal','Jeddak',event(16,2),event(24,4)],['tharks','carter','Chieftain',event(10,3)],['warhoons','bar','Jeddak',event(18,2),event(18,3)],['warhoons','dak','Lieutenant',event(18,1)],['heliumites','dejah','Princess and scientific envoy',event(8,3)],['heliumites','kantos','Naval officer',event(19,1)],['heliumites','tardos','Jeddak',event(26,4)],['heliumites','mors','Jed of Lesser Helium',event(26,2)],['zodangans','thane','Jeddak',event(21,4)],['zodangans','sab','Prince and commander',event(21,4)]].map(([f,c,role,startEventId,endEventId=null],i)=>({...stamp,id:ref('membership',i+1),factionId:ref('faction',f),characterId:ref('char',c),role,startEventId,endEventId,notes:''}))
const characterGoals=[['carter','Find safety and understand the world beneath the two moons',event(3,1),event(10,1)],['carter','Carry Dejah Thoris safely toward Helium',event(10,4),event(26,4)],['dejah','Return to Helium with the knowledge gathered by her expedition',event(10,1),event(26,4)],['tars','Replace Tal Hajus’s rule with leadership the horde can respect',event(24,2),event(24,4)],['kantos','Bring warning and military aid to Helium',event(23,1),event(26,3)],['carter','Reach the factory before Barsoom’s air is exhausted',event(27,3),event(27,4)]].map(([c,text,startEventId,endEventId],i)=>({...stamp,id:ref('goal',i+1),characterId:ref('char',c),type:'primary',text,startEventId,endEventId}))
const mapRoutes=[['earth','Arizona Pursuit','arizona',['arizona-hills','arizona-cave'],'trail'],['thark','Across Thark Country','barsoom',['korad','thark-city','desert','warhoon'],'trail'],['escape','Escape from Thark','thark',['carter-quarters','thark-outskirts'],'trail'],['zodanga','Zodanga Infiltration','zodanga',['zodanga-barracks','than-palace','dejah-apartment','palace-roof'],'air'],['helium','Relief of Helium','barsoom',['zodanga-gate','helium-gate'],'air'],['factory','Race to the Atmosphere Plant','atmosphere',['factory-entrance','pump-room','control-room'],'trail']].map(([k,name,map,points,routeType])=>({...stamp,id:ref('route',k),mapLayerId:ref('map',map),name,routeType,waypoints:points.map(x=>ref('loc',x)),color:'#9b5840',notes:'Editorial route based on narrated movement; no surveyed distance is claimed.'}))
const cover=image('world','cover','art/world.png').id
const world={version:18,type:'world',exportedAt:now,world:{...stamp,id:W,name:'A Princess of Mars',description:'A Virginia soldier wakes beneath the twin moons of a dying world, where desert nations, airborne cities, and unfamiliar customs reshape every assumption he carries from Earth.',coverImageId:cover,theme:'theme-scifi',readingMode:true,continuityStaleThreshold:5,wordTarget:countWords(narrativeText),calendar:{startYear:0,yearSuffix:' A.B. (editorial)',months:[{name:'First Cycle',days:100},{name:'Second Cycle',days:100},{name:'Third Cycle',days:100},{name:'Fourth Cycle',days:100}]}},mapLayers,locationMarkers,characters,items,characterSnapshots,itemPlacements,chapters,events,sceneTexts,blobs,relationships,relationshipSnapshots,timelines:[{...stamp,id:T,name:'John Carter’s Account',description:'The foreword and twenty-eight chapters in their original reading order, using an editorial elapsed-day calendar.',color:'#9a553e',dayOffset:0}],plotThreads,motifs,loreCategories,lorePages,knowledgeFacts,knowledgeReveals,factions,factionMemberships,characterGoals,mapRoutes}
for(const k of ['characterMovements','locationSnapshots','itemSnapshots','travelModes','timelineRelationships','crossTimelineArtifacts','mapRegions','mapRegionSnapshots','mapAnnotations','factionRelationships','continuitySuppressions','writingLogs','sceneRevisions'])world[k]=[]
if(normalize(sceneTexts.map(x=>x.text).join('\n\n'))!==normalize(narrativeText))throw Error('Source reconstruction failed')
fs.writeFileSync(new URL('../../library/a-princess-of-mars.pwk',import.meta.url),JSON.stringify(world,null,2)+'\n')
console.log({chapters:chapters.length,events:events.length,words:sceneTexts.reduce((n,x)=>n+x.wordCount,0),characters:characters.length,locations:locationMarkers.length,maps:mapLayers.length,items:items.length,images:blobs.length,snapshots:characterSnapshots.length,sourceSha256})
