// Three to five scene events per chapter. `cut` is a reviewed paragraph index in the
// normalized Gutenberg chapter section; the final generator rejects non-increasing cuts.
const E=(title,description,location,tension,cast,items=[])=>({title,description,location,tension,cast,items})
export const chapterPlans = [
 [E('The Sealed Manuscript','Burroughs recalls Carter’s ageless presence, strange death, tomb, and instructions for the manuscript.','hudson',2,['burroughs','carter']),E('Partners in the Arizona Hills','Carter and Powell find a rich vein while prospecting beyond the reach of settled authority.','arizona-hills',2,['carter','powell']),E('Powell Rides into Danger','Carter follows Powell toward an Apache pursuit and finds his partner fallen.','arizona-hills',4,['carter','powell'],['revolvers','rifle']),E('Refuge in the Cave','Under fire, Carter carries Powell to a hidden cave and confronts an unseen presence.','arizona-cave',5,['carter','powell'],['revolvers','rifle'])],
 [E('A Body That Will Not Answer','Carter lies conscious but immobile while Apache scouts recoil from the cave.','arizona-cave',4,['carter']),E('Standing Outside Himself','He separates from his earthly body and discovers strength in a new, unclothed form.','arizona-cave',4,['carter']),E('The Call of Mars','On the ledge beneath the night sky, Carter reaches toward the red planet and loses Arizona.','arizona-cave',5,['carter'])],
 [E('Under Alien Moons','Carter wakes naked on a mossy plain and learns the startling reach of his muscles.','barsoom',3,['carter']),E('The Incubator','He enters a glass-roofed enclosure filled with eggs and newly hatched green Martians.','incubator',3,['carter']),E('First Contact','A towering warrior threatens him until Carter’s prodigious leaps change the encounter.','desert',4,['carter','tars'],['revolvers']),E('Prisoner of the Horde','Tars Tarkas accepts Carter’s surrender and carries him toward the ruined city.','desert',3,['carter','tars','lorquas'])],
 [E('The Dead City','Carter enters Korad among mounted warriors and studies the green Martian horde.','korad',2,['carter','tars','lorquas']),E('Before Lorquas Ptomel','The captive is displayed before the community’s jed and receives food and rough hospitality.','korad-plaza',3,['carter','lorquas','tars','sola','sarkoja']),E('A Leap Becomes a Spectacle','Carter turns a humiliating order into an exhibition of strength before the crowd.','korad-plaza',3,['carter','tars','sola','sarkoja','lorquas']),E('Sola’s Quarters','Sola leads Carter and his fierce guard animal into painted rooms for the night.','carter-quarters',2,['carter','sola','woola'])],
 [E('The Watch Dog','Woola guards Carter while Sola begins teaching him words and customs.','carter-quarters',2,['carter','sola','woola']),E('A City by Moonlight','Carter slips into Korad’s empty streets beneath the racing moons.','korad-plaza',2,['carter','woola']),E('Beyond the Boundary','Woola blocks Carter’s flight until kindness and command overcome the animal’s orders.','thark-outskirts',3,['carter','woola']),E('The Window Above','Carter leaps into a high window as Woola searches below.','korad',3,['carter','woola'])],
 [E('White Apes in the Ruin','Great apes attack Carter inside the building while Woola fights to reach him.','korad',5,['carter','woola']),E('Cudgel and Revolver','Carter joins Woola against the apes and uses an Earth weapon at close quarters.','korad',5,['carter','woola'],['revolvers']),E('Tars Tarkas Laughs','Tars witnesses the victory and acknowledges Carter’s courage.','korad',3,['carter','woola','tars','sola']),E('Mercy for Woola','Carter tends the wounded calot and amazes the watching warriors.','carter-quarters',2,['carter','woola','tars','sola'])],
 [E('Thought Before Speech','Sola’s lessons reveal Martian telepathy and Carter’s unusual receptiveness.','carter-quarters',2,['carter','sola']),E('The Hatching','The horde opens its communal incubator and sorts the emerging young.','incubator',3,['carter','tars','sola','sarkoja','lorquas']),E('Children of the Horde','Carter learns how green Martian children are selected, trained, and denied families.','incubator',2,['carter','sola','tars']),E('Sola’s Difference','Sola’s private conduct confirms that compassion survives within the communal system.','carter-quarters',2,['carter','sola'])],
 [E('Battle in the Sky','Carter watches green warriors fire upon a damaged red Martian fleet.','korad-plaza',4,['carter','tars','lorquas'],['rifle']),E('The Falling Craft','A crippled flyer descends as the Tharks capture its surviving crew.','korad-plaza',4,['carter','tars','sola','woola']),E('A Woman of Earthly Form','Carter sees Dejah Thoris brought into the plaza and recognizes a human figure on Mars.','korad-plaza',3,['carter','dejah','tars','sola','sarkoja','woola'])],
 [E('Weapons and Words','Carter receives arms and learns daily beside Sola and the young warriors.','carter-quarters',2,['carter','sola'],['sword','rifle','metal']),E('The Prisoner’s Fate','Sarkoja discusses the captive’s death until Sola’s anger reveals her sympathies.','carter-quarters',3,['carter','sola','sarkoja','dejah']),E('A Resolve to Help','Carter decides to enlist Sola in protecting Dejah Thoris.','carter-quarters',3,['carter','sola','woola'])],
 [E('An Audience in Korad','Dejah Thoris names herself and explains her scientific expedition before Lorquas Ptomel.','korad-plaza',3,['carter','dejah','lorquas','tars','sola','sarkoja']),E('The Challenge','Carter intervenes when a warrior strikes Dejah and accepts mortal combat.','korad-plaza',5,['carter','dejah','tars','sola','lorquas'],['sword']),E('Rank by Combat','His victories earn chieftain’s metal and a place among the Tharks.','korad-plaza',5,['carter','dejah','tars','sola'],['sword','metal']),E('Protection Claimed','Carter places Dejah under his protection and escorts her from the assembly.','carter-quarters',3,['carter','dejah','sola','woola'])],
 [E('New Quarters in Korad','Sola and Carter establish guarded quarters for Dejah among the dead city’s surviving murals.','carter-quarters',2,['carter','dejah','sola','woola']),E('Questions of Origin','Dejah presses Carter to explain his unfamiliar body, conduct, and claim to gentility.','carter-quarters',2,['carter','dejah']),E('A Man from Jasoom','Carter names Earth as his world and Dejah tests the astonishing claim against Barsoomian knowledge.','carter-quarters',3,['carter','dejah']),E('The History in the Ruins','Their exploration opens into Dejah’s account of the ancient races, drying seas, and the red Martian people.','carter-quarters',2,['carter','dejah','sola'])],
 [E('Power Without Freedom','Lorquas tells Carter that his rank does not end his captivity.','korad-plaza',3,['carter','lorquas']),E('Tars Tarkas’s Warning','Tars advises Carter about Tal Hajus and the danger attached to Dejah Thoris.','korad-plaza',3,['carter','tars']),E('A Chieftain’s Household','Carter receives quarters, possessions, and attendants taken from defeated warriors.','carter-quarters',2,['carter','sola','woola'],['metal','sword','rifle']),E('Escape Occupies His Thoughts','Comfort sharpens rather than weakens Carter’s resolve to reach Helium.','carter-quarters',2,['carter','woola'])],
 [E('Kindness and the Thoats','Carter trains his mounts without brutality and interests Tars Tarkas.','korad-plaza',2,['carter','tars','woola'],['thoat']),E('Under the Tiny Moons','Carter and Dejah speak privately as the moons race over Korad.','carter-quarters',3,['carter','dejah']),E('Words Misread','Carter declares his love without understanding the Barsoomian answer he seeks.','carter-quarters',4,['carter','dejah']),E('The Princess Withdraws','Dejah’s wounded dignity leaves Carter unable to repair what custom has obscured.','carter-quarters',4,['carter','dejah','sola'])],
 [E('Carter’s Misery','Unable to understand Dejah’s refusal, Carter turns to Sola and Tars for counsel.','carter-quarters',3,['carter','dejah','sola','tars']),E('News of Departure','The Tharks prepare to leave Korad with their captives.','korad-plaza',3,['carter','tars','sola','dejah','sarkoja']),E('Tars Grants a Favor','Tars allows Carter a measure of freedom and agrees to watch over Dejah.','korad-plaza',3,['carter','tars','dejah']),E('The Duel','Carter kills a hostile chieftain in formal combat and assumes his following.','korad-plaza',5,['carter','tars','dejah','sola'],['sword','metal'])],
 [E('After the Duel','Carter recovers from Zad’s blade, learns that Dejah wept for him, and rides onward with the horde.','desert',3,['carter','dejah','sola','tars','woola']),E('Sola Begins Her Story','At the night camp Sola tells Carter that she was secretly born of two green Martians who loved.','desert',3,['carter','sola']),E('Tars Tarkas Named','She reveals that her father is Tars Tarkas after recounting her mother’s exposure and punishment.','desert',4,['carter','sola','tars','sarkoja','tal']),E('A Secret Entrusted','Carter receives Sola’s trust and reflects on the compassion hidden within the horde.','desert',2,['carter','sola'])],
 [E('Arrival at Thark','Thirty days after Carter’s arrival, the horde enters its ancient capital.','thark-city',3,['carter','dejah','sola','tars','woola','sarkoja']),E('Sola Brings Warning','Sola reports Tal Hajus’s intentions and urges immediate flight.','carter-quarters',4,['carter','dejah','sola','woola','tal']),E('A Map Toward Helium','Dejah draws the waterways while the three fugitives choose a northern route.','carter-quarters',3,['carter','dejah','sola'],['map']),E('The Escape Begins','Carter prepares mounts and weapons as Dejah and Sola move for the southern gate.','thark-outskirts',4,['carter','dejah','sola','woola'],['thoat','rifle','sword'])],
 [E('Captured at the Gate','Carter finds Sarkoja and Zad confronting Dejah and Sola, and intervenes.','thark-outskirts',5,['carter','dejah','sola','sarkoja','woola'],['sword']),E('Flight Across the Desert','The fugitives break away from Thark and drive their exhausted thoats south.','desert',4,['carter','dejah','sola','woola'],['thoat','rifle']),E('The Pursuit Closes','A vast Warhoon force cuts them off before they can reach safety.','desert',5,['carter','dejah','sola','woola'],['rifle']),E('Carter’s Last Stand','Carter sends the women onward and turns alone against the charging warriors.','desert',5,['carter','dejah','sola','woola'],['rifle','sword'])],
 [E('A Warhoon Captive','Carter wakes under guard and learns he has fallen among another horde.','desert',4,['carter','dak']),E('Bar Comas and Dak Kova','The Warhoon rulers dispute who controls the valuable prisoner.','desert',4,['carter','bar','dak']),E('The Jeddak Falls','Dak Kova kills Bar Comas in savage personal combat and takes command.','desert',5,['carter','bar','dak']),E('Madness in Chains','After days in the Warhoon dungeon, Carter attacks a tormenting guard.','warhoon-dungeon',5,['carter','dak'])],
 [E('Kantos Kan','A new red Martian prisoner identifies himself as an officer of Helium.','warhoon-dungeon',3,['carter','kantos']),E('News of the Search','Kantos recounts Helium’s failed efforts to find Dejah Thoris.','warhoon-dungeon',3,['carter','kantos','dejah']),E('Beasts of the Arena','The prisoners endure staged slaughter before their own turn comes.','warhoon-arena',5,['carter','kantos','dak']),E('Freedom by Combat','Carter and Kantos defeat the arena’s survivors and escape after dark.','warhoon-arena',5,['carter','kantos'],['sword'])],
 [E('Woola Returns','Carter finds Woola beyond Warhoon and follows him toward the atmosphere plant.','desert',3,['carter','woola']),E('The Keeper’s Confidence','An old custodian admits Carter and reveals the factory’s purpose and secret entrance.','factory-entrance',3,['carter','keeper','woola'],['factory-key']),E('Murder in the Factory','The assistant attacks the keeper and leaves Carter locked inside.','pump-room',5,['carter','keeper','assistant','woola'],['factory-key']),E('Across the Farms','Carter escapes, travels through cultivated country, and receives aid on the road to Zodanga.','desert',3,['carter','woola'])],
 [E('At Zodanga’s Gate','Carter parts from Woola and enters the enemy city in borrowed harness.','zodanga-gate',3,['carter','woola'],['sword','metal']),E('Kantos Kan in Zodanga','Carter finds his former prison companion, who gives him a soldier’s identity and entry to the air scouts.','zodanga-barracks',3,['carter','kantos'],['sword','metal']),E('Learning to Fly','Kantos teaches Carter the controls and science of the Zodangan flyers.','zodanga-barracks',3,['carter','kantos'],['flyer','compass']),E('Service Before Than Kosis','Carter’s aerial rescue wins notice from the Zodangan jeddak.','palace-roof',4,['carter','thane'],['flyer'])],
 [E('The Princess Refuses','Hidden near the royal apartments, Carter hears Dejah reject Sab Than.','dejah-apartment',4,['carter','dejah','sab','thane']),E('Through the Palace Maze','Carter loses his way in corridors and fights guards barring the princess’s rooms.','than-palace',5,['carter'],['sword']),E('Reunion','Carter reaches Dejah and at last learns how his earlier words wounded her.','dejah-apartment',4,['carter','dejah']),E('Than Kosis Interrupts','The palace erupts; Carter escapes upward while the rulers discover the intrusion.','than-palace',5,['carter','dejah','sab','thane'])],
 [E('A Plan for Helium','Kantos proposes stealing two flyers and carrying warning to Helium.','zodanga-barracks',3,['carter','kantos'],['flyer','compass']),E('Climbing to the Hangars','The two scale the barracks and seize machines from the roof.','palace-roof',4,['carter','kantos'],['flyer']),E('Separated in the Night','Carter loses Kantos and navigation instruments while fleeing Zodangan pursuit.','barsoom',5,['carter','kantos'],['flyer']),E('Lost Above Barsoom','He flies through darkness until a familiar dead city appears below.','korad',4,['carter'],['flyer'])],
 [E('Tars Tarkas at Korad','Carter reunites with Tars and tells him of Sola, Dejah, and Zodanga.','korad',3,['carter','tars']),E('Father and Daughter','Tars accepts the truth of Sola’s birth and agrees to confront Thark.','korad',4,['carter','tars','sola']),E('The Challenge to Tal Hajus','Before the horde, Carter exposes the jeddak’s cowardice and Tars demands combat.','thark-palace',5,['carter','tars','tal','sarkoja','sola']),E('Jeddak of Thark','Tars kills Tal Hajus, assumes leadership, and summons the green hordes toward Zodanga.','thark-palace',5,['carter','tars','tal','sola','sarkoja'],['sword','metal'])],
 [E('The Wedding Procession','Carter enters Zodanga as Dejah’s forced ceremony begins.','zodanga-throne',4,['carter','dejah','sab','thane'],['wedding-ornaments']),E('The Throne Room Erupts','He denounces the marriage and fights through Zodangan officers beside Dejah.','zodanga-throne',5,['carter','dejah','sab','thane'],['sword']),E('The Tharks Break In','Tars Tarkas’s warriors storm the palace and overturn Zodangan rule.','zodanga-throne',5,['carter','dejah','tars','sab','thane'],['sword']),E('Kantos Freed','Carter finds Kantos imprisoned and brings him back to the victors.','zodanga-barracks',3,['carter','kantos','dejah','tars'])],
 [E('The Fleet Changes Colors','Captured Zodangan ships raise Helium’s banners and approach the besieged city.','lesser-helium',4,['carter','dejah','tars','kantos']),E('Alliance in the Air','Helium’s navy recognizes Dejah and coordinates an attack with the Tharks.','lesser-helium',4,['carter','dejah','tars','kantos','mors']),E('Battle for Helium','Red and green allies crush the besieging Zodangan army.','lesser-helium',5,['carter','dejah','tars','kantos','mors','sab']),E('Before Tardos Mors','Carter and Tars are welcomed in the palace and the Thark alliance is sealed.','helium-palace',3,['carter','dejah','tars','tardos','mors','kantos'])],
 [E('Nine Years of Joy','Carter recalls his life with Dejah Thoris in Helium and the hope of their child.','helium-garden',2,['carter','dejah','tardos','mors','woola']),E('The Air Is Failing','A messenger reports that the atmosphere plant has stopped and its keepers cannot be reached.','helium-palace',5,['carter','dejah','tardos','mors']),E('Across a Suffocating World','Carter races a flyer to the factory while Barsoom’s people collapse.','atmosphere-gate',5,['carter'],['flyer','factory-key']),E('The Last Door','Using the keeper’s thought, Carter opens the plant and releases the emergency controls as consciousness fails.','control-room',5,['carter','assistant'],['factory-key'])],
 [E('Earthly Flesh','Carter wakes clothed beside his unchanged body in the Arizona cave.','arizona-cave',4,['carter']),E('Ten Years of Silence','He returns to the mine, wealth, and ordinary life without learning Barsoom’s fate.','arizona-hills',2,['carter']),E('The Red Star','From his Hudson study Carter watches Mars and longs for Dejah, their child, and Woola.','hudson',4,['carter','dejah','woola'])],
]

// Reviewed against the opening sentence of every retained paragraph in pg62.txt.
// These are zero-based paragraph indices within each source section.
const reviewedCuts = [
 [0,33,42,55],[0,11,16],[0,7,14,33],[0,11,20,27],[0,8,12,16],[0,3,14,18],[0,6,12,23],
 [0,9,18],[0,10,20],[0,24,30,36],[0,12,21,31],[0,8,13,24],[0,13,22,34],[0,16,24,52],
 [0,19,38,40],[0,20,27,33],[0,10,21,24],[0,11,18,23],[0,3,14,23],[0,7,30,40],
 [0,19,27,47],[0,18,30,53],[0,18,32,38],[0,9,18,35],[0,2,8,23],[0,15,27,34],
 [0,7,18,35],[0,6,10],
]
if (reviewedCuts.length !== chapterPlans.length) throw Error('Cut ledger does not cover every chapter')
chapterPlans.forEach((plan, chapterIndex) => {
  if (reviewedCuts[chapterIndex].length !== plan.length) throw Error(`Cut count mismatch in chapter ${chapterIndex + 1}`)
  plan.forEach((event, eventIndex) => { event.cut = reviewedCuts[chapterIndex][eventIndex] })
})

export function withCuts(section, plan) {
  const paragraphs = section.text.split(/\n{2,}/)
  const result = plan.map(event => ({ ...event }))
  if (result.some((event, i) => event.cut < 0 || event.cut >= paragraphs.length || (i && event.cut <= result[i - 1].cut))) throw Error(`Invalid reviewed cuts in chapter ${section.number}`)
  return result
}
