export const maps = [
  ['barsoom',null,'Barsoom','An editorial chart of the dying planet’s southern inhabited belt, waterways, dead sea bottoms, and rival cities.'],
  ['arizona',null,'Arizona and the Hudson','The earthly frame: the Arizona hills, Carter’s cave and mine, and his later home above the Hudson.'],
  ['thark','barsoom','Thark and Korad','The ruined cities, incubator country, and desert routes used by the Thark horde.'],
  ['zodanga','barsoom','Zodanga','The walled city, palace quarter, barracks, and approaches crossed during Carter’s infiltration and assault.'],
  ['helium','barsoom','Helium','Greater and Lesser Helium, joined across the cultivated country by air and waterway.'],
  ['atmosphere','barsoom','Atmosphere Factory','An interpretive plan of the isolated factory, its outer doors, corridors, pump chamber, and control room.'],
]

export const locations = [
  ['hudson','arizona','Hudson Cottage','Carter’s quiet riverside home, study, and mysterious outward-opening tomb.',null],
  ['arizona-hills','arizona','Arizona Hills','Rugged prospecting country where Carter and Powell search for gold.',null],
  ['arizona-cave','arizona','Arizona Cave','A hidden cave with strange fumes, an ancient chamber, and a ledge above the trail.',null],
  ['barsoom','barsoom','Barsoom','The ochre desert world beneath two swift moons, sustained by waterways and manufactured air.',null],
  ['korad','barsoom','Korad','A deserted city occupied temporarily by the Tharks, its painted chambers surviving an extinct people.','thark'],
  ['incubator','thark','Community Incubator','A guarded glass enclosure where green Martian eggs hatch after years underground.',null],
  ['korad-plaza','thark','Korad Plaza','The ruined city’s broad gathering space for councils, combats, and prisoners.',null],
  ['carter-quarters','thark','Carter’s Korad Quarters','Painted rooms assigned to Carter, Sola, Woola, and later Dejah Thoris.',null],
  ['thark-city','barsoom','Thark','The ancient city from which the nomadic horde takes its name.','thark'],
  ['thark-palace','thark','Tal Hajus’s Palace','The audience hall where tribal power is enforced through fear and personal combat.',null],
  ['thark-outskirts','thark','Southern Gate and Outskirts','Ruined avenues and animal lines used in the attempted escape from Thark.',null],
  ['warhoon','barsoom','Warhoon','The hostile green Martian city where captives are chained and forced into its arena.',null],
  ['warhoon-dungeon','barsoom','Warhoon Dungeon','A dark cell where Carter meets Kantos Kan.',null],
  ['warhoon-arena','barsoom','Warhoon Arena','A rough amphitheatre of beasts, prisoners, and single combat.',null],
  ['atmosphere-gate','barsoom','Atmosphere Factory','The isolated plant that renews the planet’s air.','atmosphere'],
  ['factory-entrance','atmosphere','Outer Entrance','A massive door opened by telepathic combination.',null],
  ['pump-room','atmosphere','Pump Chamber','Twenty radium pumps can sustain Barsoom’s atmosphere.',null],
  ['control-room','atmosphere','Control Room','The innermost controls and emergency doors of the atmosphere plant.',null],
  ['zodanga-gate','barsoom','Zodanga','A prosperous, heavily defended red Martian city.','zodanga'],
  ['zodanga-barracks','zodanga','Zodangan Barracks','Air-scout quarters and hangars where Carter assumes military service.',null],
  ['than-palace','zodanga','Than Kosis’s Palace','The royal complex where Dejah Thoris is held and Sab Than presses his suit.',null],
  ['dejah-apartment','zodanga','Dejah Thoris’s Apartments','A guarded suite reached through palace corridors and service passages.',null],
  ['palace-roof','zodanga','Palace Roof','A high landing and escape point above Zodanga.',null],
  ['zodanga-throne','zodanga','Zodangan Throne Room','The ceremonial chamber interrupted by Carter and the invading Tharks.',null],
  ['helium-gate','barsoom','Helium','The twin cities and capital of the Heliumite nation.','helium'],
  ['greater-helium','helium','Greater Helium','The larger of Helium’s two linked cities and seat of Tardos Mors.',null],
  ['lesser-helium','helium','Lesser Helium','The companion city besieged by Zodangan armies.',null],
  ['helium-palace','helium','Palace of Helium','Marble courts, towers, and gardens where Carter joins Dejah Thoris’s family.',null],
  ['helium-garden','helium','Sunken Garden','A sheltered palace garden holding the royal incubator.',null],
  ['desert','barsoom','Dead Sea Bottoms','Vast moss-covered plains and ochre deserts crossed by thoat and flyer.',null],
]

export const characters = [
  ['carter','John Carter',[], 'A courtly Virginia fighting man and former Confederate officer whose apparent age never changes.','#4f6a78'],
  ['burroughs','Edgar Rice Burroughs',[], 'Carter’s younger kinsman and the custodian of his sealed manuscript.','#66594c'],
  ['powell','James K. Powell',[], 'Carter’s capable prospecting partner in Arizona.','#7b6045'],
  ['tars','Tars Tarkas',[], 'A formidable Thark warrior whose reserve differs from the open cruelty around him.','#56715d'],
  ['sola','Sola',[], 'A green Martian woman whose patience and compassion make her an exception among the Tharks.','#718764'],
  ['dejah','Dejah Thoris',[], 'The Princess of Helium, a scientist and envoy captured after an aerial expedition.','#a84e43'],
  ['woola','Woola',[], 'A many-legged calot assigned as Carter’s guard, fierce in appearance and responsive to kindness.','#8a6547'],
  ['lorquas','Lorquas Ptomel',[], 'Jed of the Thark community that first captures Carter.','#64735a'],
  ['sarkoja','Sarkoja',[], 'A senior Thark woman who resents Sola and treats suffering as entertainment.','#6f6551'],
  ['tal','Tal Hajus',[], 'Jeddak of Thark, feared by the horde he rules.','#5e644e'],
  ['bar','Bar Comas',[], 'The young jeddak of Warhoon.','#59674f'],
  ['dak','Dak Kova',[], 'Bar Comas’s ambitious older lieutenant.','#4a5848'],
  ['kantos','Kantos Kan',[], 'A naval officer of Helium captured while searching for Dejah Thoris.','#476c86'],
  ['keeper','Atmosphere Keeper',[], 'An elderly custodian entrusted with the secret that opens the atmosphere plant.','#86765b'],
  ['assistant','Assistant Keeper',[], 'The only other engineer entrusted with the factory’s operation.','#766a55'],
  ['thane','Than Kosis',[], 'Jeddak of Zodanga and father of Sab Than.','#7a4d3f'],
  ['sab','Sab Than',[], 'Prince of Zodanga and commander of its forces.','#93473f'],
  ['tardos','Tardos Mors',[], 'Jeddak of Helium and grandfather of Dejah Thoris.','#9a684b'],
  ['mors','Mors Kajak',[], 'Jed of Lesser Helium and father of Dejah Thoris.','#8a5b46'],
]

export const items = [
  ['revolvers','Carter’s Revolvers','Earth-made sidearms whose unfamiliar report and effectiveness alter several Martian encounters.','weapon'],
  ['rifle','Martian Radium Rifle','A long-range rifle whose sunlight-charged explosive projectile is deadly at extraordinary distance.','weapon'],
  ['sword','Martian Long-Sword','The principal dueling weapon through which Carter earns rank and allies.','weapon'],
  ['metal','Chieftain’s Metal','Ornaments and insignia taken in combat to record rank among the green Martians.','token'],
  ['map','Dejah Thoris’s Map','A hand-drawn map of waterways and cities used to plan the escape toward Helium.','map'],
  ['compass','Martian Compass','A directional instrument fitted to flyers and used during the night escape.','tool'],
  ['flyer','One-Man Flyer','A small aerial craft used for scouting, infiltration, and escape.','vehicle'],
  ['thoat','Thoat Tack','Harness and gear for the great eight-legged riding animals.','tool'],
  ['factory-key','Atmosphere Combination','A telepathically transmitted sequence that opens the factory doors.','secret'],
  ['wedding-ornaments','Wedding Ornaments','Ceremonial jewels and metal prepared for the Zodangan marriage rite.','token'],
]
