const E = (title, description, location, tension, states, items = []) => ({
  title, description, location, tension, states, cast: Object.keys(states), items,
})

export const sectionPlans = [
  { synopsis: 'The narrator assembles testimony and physical evidence that the Opera Ghost was a real man.', events: [
    E('A Case Reopened', 'The narrator rejects the fashionable explanations for the Chagny tragedy and reopens the Opera Ghost case.', 'opera-archives', 2, { narrator: 'Sorts witness statements and challenges the public legend with a documentary investigation.' }, ['persian-papers']),
    E('A Body Beneath the Opera', 'A skeleton found beneath the Opera appears to confirm the identity of the mysterious inhabitant.', 'third-cellar', 3, { narrator: 'Connects the newly uncovered remains to the evidence gathered throughout the inquiry.' }, ['gold-ring']),
  ]},
  { synopsis: 'During the retiring managers’ gala, frightened dancers report the ghost and a stagehand is found hanged.', events: [
    E('The Ballet Girls Bolt the Door', 'Jammes and Meg rush into Sorelli’s dressing room after seeing a skull-faced gentleman in evening dress.', 'sorelli-room', 2, { sorelli: 'Tries to steady the dancers while her own superstition makes her listen closely.', jammes: 'Locks the door and describes the death’s-head figure she has just encountered.', meg: 'Identifies the apparition as the figure her mother associates with Box Five.' }),
    E('Joseph Buquet Describes the Ghost', 'The chief scene-shifter’s earlier description gives the rumored ghost a skeletal face and yellow eyes.', 'stage-workshops', 2, { buquet: 'Warns the stage crew about the uncanny man he met below the stage.', meg: 'Repeats her mother’s rule that the ghost must never be discussed aloud.' }),
    E('A Noose in the Third Cellar', 'Buquet is found hanging during the farewell performance, though the rope itself vanishes.', 'third-cellar', 4, { buquet: 'Lies dead beneath the stage after an unexplained hanging.', sorelli: 'Receives the news amid the gala and recognizes it as more than backstage gossip.', meg: 'Connects the death with the warning she tried to enforce.' }, ['punjab-lasso']),
  ]},
  { synopsis: 'Christine Daaé astonishes the gala audience, while Raoul recognizes his childhood companion.', events: [
    E('Christine Replaces Carlotta', 'With Carlotta absent, the obscure chorus singer Christine Daaé takes the role of Margarita.', 'stage', 2, { christine: 'Steps onto the stage in an unexpected leading role and controls her fear through song.', carlotta: 'Remains away from the gala, leaving her celebrated role to an understudy.', richard: 'Judges the unfamiliar singer from the audience while preparing to assume management.', moncharmin: 'Watches the substitution with professional curiosity beside his new partner.' }),
    E('The Triumph of the New Margarita', 'Christine sings with such mastery that the audience and company greet her as a revelation.', 'auditorium', 3, { christine: 'Finishes the aria exhausted but publicly transformed from chorus girl to sensation.', raoul: 'Recognizes the voice and face of the girl he knew beside the sea.', philippe: 'Notices his younger brother’s intense response to the singer.' }),
    E('A Voice Behind the Dressing-Room Door', 'Raoul hears a commanding male voice speaking to Christine after her triumph, but finds the room empty.', 'christine-room', 3, { raoul: 'Waits outside in jealousy, then searches the empty room for Christine’s unseen visitor.', christine: 'Answers the Voice privately and leaves by a route Raoul cannot discover.' }),
  ]},
  { synopsis: 'The former managers pass a bizarre memorandum to their skeptical successors.', events: [
    E('The Farewell Supper', 'Debienne and Poligny hand the Opera over to Richard and Moncharmin after the gala.', 'managers-office', 1, { debienne: 'Uses the formal supper to transfer authority while concealing his unease.', poligny: 'Supports his partner’s guarded warnings about the building.', richard: 'Accepts control with confidence and treats talk of a ghost as an old management joke.', moncharmin: 'Studies the retiring pair and suspects an elaborate practical joke.' }),
    E('The Ghost’s Memorandum', 'The newcomers read demands reserving Box Five and paying the Opera Ghost twenty thousand francs a month.', 'managers-office', 2, { debienne: 'Insists that the memorandum records obligations the new managers should honor.', poligny: 'Refuses to explain the threats behind the strange financial arrangement.', richard: 'Laughs at the demand and resolves to expose whoever invented it.', moncharmin: 'Keeps the memorandum while looking for the trick behind its precise instructions.' }, ['ghost-memorandum']),
    E('Warnings Dismissed', 'Richard and Moncharmin decide to sell Box Five and withhold the ghost’s allowance.', 'managers-office', 3, { richard: 'Turns the warning into a test of his authority over the Opera.', moncharmin: 'Agrees to provoke the supposed ghost and observe the result.' }),
  ]},
  { synopsis: 'The new managers investigate complaints from the occupants of Box Five.', events: [
    E('A Voice in Box Five', 'The evening’s guests complain that an invisible occupant ordered them out of the reserved box.', 'box-five', 2, { richard: 'Questions the subscribers and assumes a hidden prankster has frightened them.', moncharmin: 'Examines the box for an ordinary speaker or concealed opening.' }),
    E('The Hollow Column', 'Box keeper Mme. Giry explains the ghost’s habits and points toward the great column beside the box.', 'box-five', 3, { 'mme-giry': 'Defends the unseen gentleman who leaves instructions and occasional gifts in Box Five.', richard: 'Mocks her testimony while tapping the fittings for a concealed mechanism.', moncharmin: 'Begins to suspect that the architecture itself permits the voice to travel.' }),
    E('Box Five Is Reserved Again', 'Unable to identify the speaker, the managers reluctantly leave the box empty for the next performance.', 'box-five', 2, { richard: 'Yields the box for one night while planning to catch the intruder.', moncharmin: 'Records the concession as an experiment rather than obedience.', 'mme-giry': 'Returns to her post convinced that the managers have finally understood the warning.' }),
  ]},
  { synopsis: 'Raoul follows Christine to Perros and hears the mysterious violin at her father’s grave.', events: [
    E('Childhood by the Sea', 'Raoul remembers meeting Christine and her violinist father during summers at Perros-Guirec.', 'perros-beach', 1, { raoul: 'Recalls the intimacy of childhood and the promise of the Angel of Music.', christine: 'Lives in Raoul’s memory as a fearless girl devoted to her father’s songs.', valerius: 'Preserves the memory of Christine’s father and the legends he taught her.' }),
    E('Christine at the Grave', 'Raoul finds Christine mourning alone in the churchyard on the anniversary of her father’s death.', 'perros-churchyard', 2, { christine: 'Keeps vigil at her father’s grave and waits for the music she believes he promised.', raoul: 'Approaches quietly, determined to protect her without breaking the solemn vigil.' }),
    E('The Enchanted Violin', 'A violin plays the Resurrection of Lazarus in the locked church, and Raoul glimpses a skull-like face.', 'perros-church', 4, { christine: 'Listens in religious awe, certain the Angel of Music has answered her.', raoul: 'Breaks into the church, sees the death’s head, and collapses after pursuing it.' }, ['violin']),
  ]},
  { synopsis: 'The managers occupy Box Five and discover that the invisible voice is not a theater myth.', events: [
    E('The Managers Take the Ghost’s Seats', 'Richard and Moncharmin sit in Box Five themselves during the next performance.', 'box-five', 2, { richard: 'Settles into the forbidden box determined to expose a ventriloquist.', moncharmin: 'Watches the walls and audience instead of the performance.' }),
    E('A Whisper Between Them', 'The ghost’s voice comments on the performance from an apparently empty chair between the managers.', 'box-five', 4, { richard: 'Freezes when the voice speaks within arm’s reach and no body can be found.', moncharmin: 'Tests the seat and partition while the unseen critic continues speaking.' }),
    E('Carlotta Must Be Replaced', 'The voice orders them to restore Christine as Margarita and warns of disaster if Carlotta sings.', 'box-five', 3, { richard: 'Rejects the ultimatum aloud despite the evidence of the voice.', moncharmin: 'Leaves the box shaken but unwilling to surrender management.', carlotta: 'Prepares elsewhere to reclaim her role, unaware of the threat.' }),
  ]},
  { synopsis: 'Defiance during Faust produces a croaking diva, a fatal chandelier fall, and Christine’s disappearance.', events: [
    E('Christine Hears the Angel Again', 'Christine admits to Raoul that the Voice has trained her and commands her obedience.', 'christine-room', 3, { christine: 'Confesses enough to frighten Raoul but still protects the identity of her teacher.', raoul: 'Tries to replace supernatural fear with a practical promise of help.' }),
    E('Carlotta Croaks', 'During Faust, Carlotta’s voice suddenly breaks into the croak promised by the Opera Ghost.', 'stage', 4, { carlotta: 'Forces herself through the role until an impossible croak humiliates her before the audience.', richard: 'Realizes publicly that the ghost’s warning is being fulfilled.', moncharmin: 'Looks from the stage to Box Five as the performance collapses.' }),
    E('The Chandelier Falls', 'The great chandelier crashes into the auditorium and Christine vanishes in the confusion.', 'auditorium', 5, { christine: 'Disappears from the Opera while panic fills the house.', raoul: 'Searches the crowd and backstage passages but cannot reach her.', richard: 'Confronts casualties and chaos caused by his refusal to obey.', moncharmin: 'Abandons skepticism as the auditorium erupts beneath the falling chandelier.' }, ['chandelier']),
  ]},
  { synopsis: 'Christine returns after a mysterious absence, while Raoul follows clues through Paris.', events: [
    E('Christine Returns in Silence', 'Christine reappears at the Opera but refuses to explain the fortnight she has lost.', 'christine-room', 2, { christine: 'Returns pale and guarded, bound by a promise she will not describe.', raoul: 'Demands an explanation and fears the Voice has complete control over her.' }),
    E('The Sealed Brougham', 'Raoul sees Christine enter a closed carriage that races away under mysterious orders.', 'opera-entrance', 3, { christine: 'Enters the waiting carriage because the summons leaves her afraid to refuse.', raoul: 'Follows the brougham through Paris, trying not to be seen by its driver.' }),
    E('A Trail Toward the Bois', 'The chase ends without revealing Christine’s destination or the master directing the carriage.', 'bois', 3, { raoul: 'Loses the carriage near the Bois and returns convinced that a human conspiracy surrounds her.', christine: 'Remains hidden from Raoul while carrying the secret of her absence.' }),
  ]},
  { synopsis: 'At the masked ball, Erik appears as the Red Death and Christine’s engagement ring disappears.', events: [
    E('A Secret Engagement', 'Christine agrees to wear Raoul’s ring while insisting their engagement remain temporary and hidden.', 'grand-staircase', 2, { christine: 'Accepts the ring but treats happiness as something that can last only briefly.', raoul: 'Believes the secret promise will free Christine from the Voice.' }, ['engagement-ring']),
    E('The Red Death Descends', 'A scarlet figure with a skull mask crosses the grand staircase declaring that death walks among the guests.', 'grand-staircase', 4, { erik: 'Enters the masquerade as the Red Death to display his power over Christine and the Opera.', christine: 'Recognizes the figure and hides her terror from Raoul.', raoul: 'Pursues the masked stranger through the crowd despite Christine’s warning.' }, ['red-death-costume']),
    E('The Ring Is Gone', 'Christine discovers that Raoul’s ring has been taken after Erik confronts her.', 'masked-foyer', 4, { christine: 'Realizes that Erik knows of the engagement and fears the punishment he threatened.', raoul: 'Sees her panic and understands that the secret promise has been discovered.', erik: 'Withdraws with the ring as proof that no promise at the Opera escapes him.' }, ['engagement-ring']),
  ]},
  { synopsis: 'Christine tells Raoul that the Voice belongs to a living man called Erik.', events: [
    E('Three Knocks at the Mirror', 'Christine prepares to answer the Voice after a coded summons in her dressing room.', 'christine-room', 3, { christine: 'Obeys the familiar signal while trying to keep Raoul away from danger.', raoul: 'Hides nearby and watches the mirror for the route used by her unseen teacher.' }),
    E('The Man Behind the Angel', 'Christine admits that the Angel of Music is a man named Erik who carried her below the Opera.', 'christine-room', 4, { christine: 'Names Erik at last and distinguishes the genius she heard from the jailer she came to fear.', raoul: 'Listens with jealousy giving way to alarm at the hidden man’s reach.' }),
    E('One Month of Freedom', 'Christine says Erik released her for a month on condition that she never love another man.', 'christine-room', 4, { christine: 'Counts the remaining days of borrowed freedom and begs Raoul not to provoke Erik.', raoul: 'Resolves to remove her from Paris before the promised return.', erik: 'Listens from the hidden passage and learns exactly what the lovers intend.' }),
  ]},
  { synopsis: 'Raoul and Christine explore the stage heights while planning escape.', events: [
    E('Across the Trap-Doors', 'Christine leads Raoul through backstage passages where any opening may belong to Erik.', 'stage', 3, { christine: 'Tests each shadow and trap with the caution learned during her captivity.', raoul: 'Follows her route while searching for a solid explanation of Erik’s movements.' }),
    E('Up Through the Fly Tower', 'They climb ladders and galleries above the scenery to escape listeners below.', 'fly-tower', 3, { christine: 'Chooses the dangerous height because she believes Erik rules the lower passages.', raoul: 'Keeps close behind her and begins to grasp the scale of the building’s hidden geography.' }),
    E('A Promise Above the Stage', 'Suspended over the dark stage, the lovers agree to flee after Christine’s next performance.', 'fly-tower', 4, { christine: 'Promises to leave after singing once more, torn between fear and pity.', raoul: 'Accepts the delay while insisting that their departure must be final.' }),
  ]},
  { synopsis: 'On the roof, Christine recounts Erik’s underground house and his unmasked face.', events: [
    E('Beneath Apollo’s Lyre', 'Christine and Raoul reach the roof beside Apollo’s bronze lyre, believing themselves beyond Erik’s hearing.', 'apollo-roof', 2, { christine: 'Uses the open air to speak more freely than she can inside the Opera.', raoul: 'Guards the stair and asks for the whole truth of her disappearance.' }),
    E('The House on the Lake', 'Christine describes crossing the underground lake and waking in Erik’s furnished house.', 'apollo-roof', 4, { christine: 'Relives the wonder of Erik’s music and the terror of being confined below ground.', raoul: 'Hears how carefully Erik mixed hospitality, art, and imprisonment.', erik: 'Listens unseen behind Apollo’s statue as his private world is described.' }),
    E('The Mask Torn Away', 'Christine recounts removing Erik’s mask and seeing the living death’s head beneath it.', 'apollo-roof', 5, { christine: 'Admits that curiosity exposed Erik’s face and changed devotion into horror and pity.', raoul: 'Promises escape as he understands why Erik will not release her.', erik: 'Clings to the statue above them, wounded by the retelling of his unmasking.' }, ['black-mask']),
  ]},
  { synopsis: 'The managers attempt to deliver the ghost’s allowance and are manipulated by his trap-door network.', events: [
    E('Twenty Thousand Francs Prepared', 'Richard and Moncharmin place the ghost’s monthly allowance in an envelope under close observation.', 'managers-office', 2, { richard: 'Counts the notes personally and plans to turn payment into a trap.', moncharmin: 'Records every movement of the envelope so neither partner can accuse the other.' }, ['money-envelope']),
    E('Mme. Giry Carries the Envelope', 'Following the memorandum, Mme. Giry takes the sealed money toward Box Five.', 'box-five', 3, { 'mme-giry': 'Follows the ghost’s delivery ritual exactly, trusting the instructions she has received.', richard: 'Shadows the box keeper and watches for an accomplice.', moncharmin: 'Guards the alternative exits while expecting a conventional theft.' }, ['money-envelope']),
    E('The Trap-Door Lover Wins', 'The envelope disappears through the Opera’s hidden mechanisms without revealing the thief.', 'managers-office', 4, { richard: 'Returns furious that the money vanished inside rooms he controls.', moncharmin: 'Suspects his partner because no outsider appears to have touched the envelope.', erik: 'Uses the building’s concealed routes to collect the allowance without showing himself.' }, ['money-envelope']),
  ]},
  { synopsis: 'Richard and Moncharmin pin the replacement banknotes inside a coat pocket.', events: [
    E('Partners Suspect Each Other', 'Each manager privately wonders whether the other invented the ghost to steal the allowance.', 'managers-office', 3, { richard: 'Challenges Moncharmin’s account while hiding how deeply the theft embarrassed him.', moncharmin: 'Answers each accusation with an equally detailed suspicion of Richard.' }),
    E('The Safety-Pin Test', 'They fasten the replacement notes into Richard’s inside pocket with a safety-pin.', 'managers-office', 2, { richard: 'Wears the sealed pocket and keeps one hand over it throughout the experiment.', moncharmin: 'Checks the pin and notes before they leave the office.' }, ['money-envelope', 'safety-pin']),
    E('An Evening Under Guard', 'The managers sit through the performance without separating or allowing anyone near the coat.', 'auditorium', 3, { richard: 'Endures the opera with his hand pressed over the supposedly secure pocket.', moncharmin: 'Watches his partner more closely than the stage, waiting for the trick to occur.' }, ['safety-pin']),
  ]},
  { synopsis: 'Christine is abducted from the stage during Faust.', events: [
    E('The Final Performance', 'Christine sings Margarita once more before the planned escape with Raoul.', 'stage', 3, { christine: 'Sings under the double pressure of her promise to Raoul and Erik’s expected return.', raoul: 'Watches from the house, ready to take Christine away as soon as the curtain falls.', erik: 'Waits within the stage machinery for the moment he has chosen.' }),
    E('The Lights Go Out', 'The stage is plunged into darkness during the prison scene of Faust.', 'stage', 4, { christine: 'Loses sight of the company as the darkness closes around her.', raoul: 'Leaves his seat and forces his way toward the stage.', piangi: 'Continues the scene until the blackout breaks the performance apart.' }),
    E('Christine Vanishes', 'When the light returns, Christine has disappeared through a trap-door in full view of the company.', 'stage-trapdoor', 5, { christine: 'Is pulled below the stage before she can reach Raoul.', raoul: 'Finds only confused performers and an empty place where Christine stood.', erik: 'Carries Christine into the lower passages before pursuit can organize.' }),
  ]},
  { synopsis: 'Mme. Giry explains the ghost’s salary and her hopes for Meg.', events: [
    E('Mme. Giry Is Questioned', 'The managers summon the Box Five attendant after Christine’s disappearance and the missing allowance.', 'managers-office', 3, { 'mme-giry': 'Answers with offended loyalty to the ghost and insists she merely follows written orders.', richard: 'Presses her for the route of the money and the identity of her correspondent.', moncharmin: 'Compares her account with the memorandum and the vanished envelope.' }),
    E('Letters from O.G.', 'Mme. Giry produces notes that predict advancement for Meg and specify how the allowance must be handled.', 'managers-office', 3, { 'mme-giry': 'Treats the letters as proof that the ghost protects her daughter’s career.', meg: 'Remains away from the interrogation while her ambitions become part of her mother’s testimony.', richard: 'Reads the promises as bait used to secure the box keeper’s cooperation.', moncharmin: 'Recognizes that the handwriting matches the management memorandum.' }, ['ghost-letters']),
    E('The Empress Prophecy', 'Her faith in a prophecy that Meg will become an empress convinces the managers she can be manipulated.', 'managers-office', 2, { 'mme-giry': 'Defends the prophecy with absolute seriousness and refuses to call the ghost a criminal.', richard: 'Dismisses her from service in anger at what he considers absurd complicity.', moncharmin: 'Allows the dismissal but keeps the letters as evidence.' }),
  ]},
  { synopsis: 'The safety-pin remains closed, yet the banknotes disappear from Richard’s pocket.', events: [
    E('The Pocket Still Sealed', 'After the performance, Moncharmin confirms that the safety-pin has never opened.', 'managers-office', 3, { richard: 'Presents the untouched pin with relief, expecting the money to remain beneath it.', moncharmin: 'Examines the fastening before allowing Richard to reach inside.' }, ['safety-pin']),
    E('The Notes Are Gone', 'The managers discover that the twenty thousand francs have vanished from the sealed pocket.', 'managers-office', 4, { richard: 'Turns the empty pocket inside out and can no longer accuse only an outside accomplice.', moncharmin: 'Repeats each safeguard and finds no moment when the theft should have been possible.', erik: 'Removes the notes through the floor trap beneath the office chair.' }, ['money-envelope', 'safety-pin']),
    E('A Hand Beneath the Floor', 'Their quarrel ends without discovering the tiny trap-door through which Erik reached the coat.', 'managers-office', 4, { richard: 'Accuses his partner while standing directly above the mechanism that defeated them.', moncharmin: 'Refuses responsibility and demands that the police be told at last.', erik: 'Retreats through the hidden passage with the stolen allowance.' }),
  ]},
  { synopsis: 'Police confusion gives way to the Persian’s offer of a route into Erik’s domain.', events: [
    E('The Commissary Arrives', 'Mifroid investigates Christine’s disappearance while managers, performers, and Raoul offer conflicting accounts.', 'managers-office', 3, { mifroid: 'Separates testimony from theater superstition and treats the disappearance as a physical abduction.', richard: 'Reports the blackout and trap-door while avoiding the humiliating money story.', moncharmin: 'Adds details that implicate the Opera Ghost despite the commissary’s skepticism.', raoul: 'Insists that a man called Erik has taken Christine below the Opera.' }),
    E('Philippe Confronts Raoul', 'Count Philippe tries to restrain his brother from pursuing a scandalous and apparently impossible story.', 'opera-entrance', 3, { philippe: 'Attempts to protect the family name and keep Raoul from throwing himself into danger.', raoul: 'Rejects his brother’s authority because every delay leaves Christine captive.' }),
    E('The Persian Steps Forward', 'A mysterious Persian tells Raoul that he knows Erik and can lead a rescue.', 'opera-entrance', 4, { persian: 'Reveals enough knowledge of Erik to make Raoul follow him without alerting the police.', raoul: 'Accepts help from the one man who treats the underground danger as real.', mifroid: 'Continues the official search without understanding the route the rescuers will take.' }),
  ]},
  { synopsis: 'At his flat, the Persian equips Raoul and explains the danger of Erik’s weapons.', events: [
    E('A Warning About Erik', 'The Persian identifies Erik as a genius of traps, voices, and the Punjab lasso.', 'persian-flat', 3, { persian: 'Explains the adversary’s habits from long and dangerous experience.', raoul: 'Forces himself to listen while urgency tempts him to return to the Opera unprepared.' }, ['punjab-lasso']),
    E('Pistols at Eye Level', 'The Persian instructs Raoul to keep a hand raised before his eyes so the lasso cannot close around his throat.', 'persian-flat', 3, { persian: 'Demonstrates the defensive posture and checks both pistols before departure.', raoul: 'Practices the awkward guard because Christine’s rescue depends on surviving the descent.' }, ['pistols']),
    E('Back to the Opera', 'Raoul and the Persian hurry through the sleeping city toward the stage door.', 'opera-entrance', 4, { persian: 'Chooses a covert entrance and leads Raoul away from the official search.', raoul: 'Returns armed and focused, surrendering direction to the Persian.' }, ['pistols']),
  ]},
  { synopsis: 'The rescuers descend through the Opera cellars and evade strange guardians.', events: [
    E('Through the Trap-Door', 'The Persian opens a concealed route beneath the stage and begins the descent with Raoul.', 'stage-trapdoor', 4, { persian: 'Tests the opening for Erik’s countertraps before lowering himself into darkness.', raoul: 'Follows with one hand protecting his throat and the other holding a pistol.' }, ['pistols']),
    E('The Rat-Catcher’s Flame', 'A moving fiery head in the cellars resolves into a rat-catcher carrying his lamp at waist level.', 'fifth-cellar', 3, { persian: 'Recognizes an ordinary workman before Raoul wastes a shot.', raoul: 'Masters his panic when the apparent monster becomes a man at work.' }),
    E('The Silent Man in the Felt Hat', 'They avoid a dangerous figure and continue toward the underground lake.', 'lake-shore', 4, { persian: 'Diverts the patrol without revealing the purpose of the descent.', raoul: 'Waits motionless until the path toward the water is clear.' }),
  ]},
  { synopsis: 'The Persian recalls Erik’s past and leads the crossing toward the house on the lake.', events: [
    E('The Daroga Remembers Persia', 'The Persian recalls supervising Erik in Mazenderan, where ingenious palaces concealed political murders.', 'lake-shore', 3, { persian: 'Measures the present rescue against the lethal architecture he saw Erik create in Persia.', raoul: 'Learns that every wall ahead may have been designed as a weapon.', erik: 'Exists in the account as the brilliant captive architect once protected by the daroga.' }),
    E('A Boat Across the Black Water', 'The rescuers cross the underground lake toward the light of Erik’s house.', 'underground-lake', 4, { persian: 'Rows by remembered bearings while listening for movement beneath the water.', raoul: 'Watches the lit windows ahead and believes Christine is inside.' }),
    E('The Wrong Entrance', 'Instead of reaching the house, they pass through a concealed panel into a mirrored chamber.', 'torture-entrance', 5, { persian: 'Realizes too late that Erik has guided them into the torture chamber.', raoul: 'Searches the seamless wall for the door that has closed behind them.', erik: 'Seals the chamber remotely and returns his attention to Christine.' }),
  ]},
  { synopsis: 'Raoul and the Persian discover that the mirrored room is a mechanical torture chamber.', events: [
    E('A Forest Made of Mirrors', 'Reflections transform one iron tree into an endless hot forest around the prisoners.', 'mirror-room', 4, { persian: 'Identifies the chamber from Erik’s Persian demonstrations and searches for its control.', raoul: 'Strikes the mirrors until he understands that breaking them will not reveal an exit.' }),
    E('Voices Through the Wall', 'The prisoners hear Erik demanding that Christine choose marriage while she pleads for Raoul.', 'mirror-room', 5, { raoul: 'Calls to Christine through the wall and reveals that he is alive but trapped.', persian: 'Stops Raoul from wasting ammunition and listens for clues to Erik’s mechanism.', christine: 'Hears Raoul’s voice and refuses to pretend that her choice concerns only herself.', erik: 'Uses the prisoners’ presence to intensify the ultimatum.' }),
    E('The Iron Tree', 'The Persian locates the heated iron structure but cannot stop the rising temperature.', 'iron-tree', 5, { persian: 'Tests the trunk and branches for a release while the metal grows too hot to touch.', raoul: 'Conserves strength and searches the floor for air or water.' }),
  ]},
  { synopsis: 'Heat, false landscapes, and thirst begin to break the trapped rescuers.', events: [
    E('The Mechanical Jungle', 'Erik cycles the mirrors through sunlit forest and desert illusions while the chamber heats.', 'mirror-room', 5, { persian: 'Names each illusion and keeps Raoul focused on mechanisms rather than hallucination.', raoul: 'Endures the false jungle while answering Christine whenever her voice reaches him.', erik: 'Operates the chamber to exhaust both men without entering it.' }),
    E('A Lasso in the Dark', 'A rope drops into the chamber as another reminder of Erik’s power over the prisoners.', 'mirror-room', 5, { persian: 'Recognizes the Punjab lasso and pulls Raoul clear before it can tighten.', raoul: 'Raises his guarded hand in time and cuts at the rope.' }, ['punjab-lasso']),
    E('Thirst', 'The men discover that the apparent water in the mirrored landscape cannot be reached.', 'mirror-room', 5, { persian: 'Feels along the floor for plumbing that must serve the chamber.', raoul: 'Weakens from heat but continues calling Christine’s name.' }),
  ]},
  { synopsis: 'A hidden trap leads the prisoners above barrels of gunpowder wired to the Opera.', events: [
    E('The Trap in the Floor', 'Raoul and the Persian open a low hatch that appears to offer escape from the torture chamber.', 'mirror-room', 4, { persian: 'Forces the floor panel while suspecting that any easy exit is another design of Erik’s.', raoul: 'Drops through first because the heat leaves no safer choice.' }),
    E('Barrels Below', 'The chamber beneath is packed with gunpowder barrels connected by wires.', 'powder-cellar', 5, { persian: 'Recognizes a demolition system capable of destroying the Opera above.', raoul: 'Understands that Christine’s decision now threatens everyone in the theater.', erik: 'Keeps the explosives ready as the final enforcement of his marriage demand.' }, ['gunpowder-barrels']),
    E('The Wire to the House', 'The rescuers trace the ignition lines toward the mechanism controlled from Erik’s drawing room.', 'powder-cellar', 5, { persian: 'Follows the wires and deduces the choice Erik has placed before Christine.', raoul: 'Listens for her answer while trapped among the barrels.' }, ['electric-wire']),
  ]},
  { synopsis: 'Christine must turn either the scorpion for marriage or the grasshopper for destruction.', events: [
    E('The Two Figures', 'Erik shows Christine a scorpion and grasshopper mounted beside the mechanism in his drawing room.', 'lake-drawing-room', 5, { erik: 'Explains the choice with terrible calm: marriage under the scorpion or explosion under the grasshopper.', christine: 'Studies the mechanism while listening for any sign that Raoul still lives.' }, ['scorpion-grasshopper']),
    E('Christine Turns the Scorpion', 'To save Raoul, the Persian, and the Opera, Christine chooses marriage.', 'lake-drawing-room', 5, { christine: 'Turns the scorpion and sacrifices her own freedom to prevent the explosion.', erik: 'Accepts the signal as a binding promise and releases the flood mechanism instead.' }, ['scorpion-grasshopper']),
    E('Water in the Powder Cellar', 'Water rushes around the prisoners and the barrels as the explosive threat is neutralized.', 'powder-cellar', 5, { raoul: 'Struggles to keep his head above the rising water as the barrels begin to float.', persian: 'Guides Raoul toward the opening created by the flood.', erik: 'Allows the water to extinguish the powder and prepares to recover the prisoners.' }),
  ]},
  { synopsis: 'Christine’s compassion transforms Erik’s final decisions.', events: [
    E('A Kiss on Erik’s Forehead', 'Christine kisses Erik without recoiling, giving him the first freely offered human tenderness of his life.', 'lake-drawing-room', 5, { christine: 'Touches and kisses Erik out of compassion while still holding to the promise that saved Raoul.', erik: 'Breaks down because she treats him as a human being rather than a monster.' }),
    E('Raoul Is Released', 'Erik frees Raoul and the Persian and permits Christine to leave with the man she loves.', 'lake-house', 4, { erik: 'Renounces possession of Christine and opens the way out of his house.', christine: 'Rejoins Raoul while promising to return Erik’s ring after his death.', raoul: 'Leaves captivity alive and accepts Christine’s compassion toward their captor.', persian: 'Witnesses Erik choose mercy over the power of his traps.' }, ['gold-ring']),
    E('Erik’s Last Visit', 'Dying of grief, Erik visits the Persian, recounts the farewell, and asks that his death be announced.', 'persian-flat', 4, { erik: 'Entrusts the truth, his papers, and the notice of his death to the only witness who understands him.', persian: 'Receives Erik’s confession and agrees to inform Christine when the end comes.' }, ['persian-papers', 'gold-ring']),
  ]},
  { synopsis: 'The narrator weighs the evidence, reconstructs Erik’s life, and identifies his skeleton.', events: [
    E('Evidence in the Opera', 'The narrator verifies the hollow column, trap-doors, passages, and documents behind the legend.', 'opera-archives', 2, { narrator: 'Tests the Persian’s account against the surviving architecture and witness records.', persian: 'Guides the inquiry through testimony and papers preserved after Erik’s death.' }, ['persian-papers', 'ghost-memorandum']),
    E('The Life of Erik', 'The investigation traces Erik from fairs and Persian palaces to his hidden work beneath the Paris Opera.', 'opera-archives', 3, { narrator: 'Reconstructs a life in which architectural genius, exclusion, and violence became inseparable.', erik: 'Appears in the record as a builder who created his final refuge inside the Opera.' }),
    E('The Ring on the Skeleton', 'A plain gold ring identifies the remains near the underground well as Erik’s.', 'little-well', 3, { narrator: 'Closes the case by matching Christine’s promised ring to the body beneath the Opera.', erik: 'Lies at last in the hidden ground beside the place where he first carried Christine below.' }, ['gold-ring']),
  ]},
]

if (sectionPlans.length !== 28) throw new Error(`Expected 28 section plans, found ${sectionPlans.length}`)
