import fs from 'node:fs'
import { maps as mapDefs, locations as locationDefs, characters as characterDefs, items as itemDefs } from './world-ledger.mjs'
import { sourceSections, narrativeText, sourceEdition, sourceUrl } from './source-text.mjs'
import { sectionPlans } from './story-ledger.mjs'
const W='turn-of-the-screw-world', T='turn-of-the-screw-timeline', now=Date.UTC(2026,8,15)
const stamp={worldId:W,createdAt:now,updatedAt:now}
const ref=(kind,key)=>`screw-${kind}-${key}`
const words=s=>(s.match(/\S+/g)||[]).length
const selected={'map-bly-estate':'map-bly-estate-v2','item-manuscript':'item-manuscript-v2','item-flora-boat':'item-flora-boat-v2','location-tower-bedroom':'location-tower-bedroom-v2'}
const coordinates={harley:[1010,556],'coach-inn':[1080,640],'frame-house':[760,570],'coach-road':[1120,660],'bly-gateway':[1100,690],'manor-gateway':[750,799],'front-drive':[750,599],'east-lawn':[1050,599],lake:[335,584],'lake-bank':[490,594],'far-bank':[200,594],mooring:[450,519],'lake-gate':[140,574],'church-path':[1140,369],church:[1370,279],churchyard:[1330,184],terrace:[750,719],garden:[750,374],hall:[760,424],'drawing-room':[440,414],'dining-room':[1160,424],window:[1190,274],'service-wing':[130,604],'housekeeper-room':[480,734],'main-stair':[770,774],'governess-room':[430,364],'miles-room':[1110,364],schoolroom:[1100,714],'upper-corridor':[760,529],'tower-stair':[370,864],'tower-bedroom':[420,704],'old-tower':[250,809],'new-tower':[1290,809],'roof-walk':[760,779]}
const blobs=[]
function image(key){const filename=selected[key]||key;const url=`library/the-turn-of-the-screw/art/${filename}.png`;const disk=new URL(`../../${url}`,import.meta.url);if(!fs.existsSync(disk))throw Error(`Missing ${url}`);const b=fs.readFileSync(disk);if(b.toString('hex',0,8)!=='89504e470d0a1a0a')throw Error('Not PNG');blobs.push({...stamp,id:ref('image',key),mimeType:'image/png',url});return {id:ref('image',key),width:b.readUInt32BE(16),height:b.readUInt32BE(20)}}
const mapLayers=mapDefs.map(([key,parent,name,description],i)=>{const art=image(`map-${key}`);return {...stamp,id:ref('map',key),name,description,parentMapId:parent?ref('map',parent):null,imageId:art.id,imageWidth:art.width,imageHeight:art.height,scalePixelsPerUnit:null,scaleUnit:null,levelGroupId:null,levelIndex:i,levelLabel:null}})
const locationMarkers=locationDefs.map(([key,map,name,description,,,child])=>({...stamp,id:ref('loc',key),name,description:key==='old-tower'?'A crenellated tower rising above the house and lawn.':key==='manor-gateway'?'A handsome, many-windowed country house with two towers and a terrace.':description,mapLayerId:ref('map',map),linkedMapLayerId:child?ref('map',child):null,x:coordinates[key][0],y:coordinates[key][1],iconType:child?'building':'pin',imageId:image(`location-${key}`).id,tags:[],factionId:null}))
const characters=characterDefs.map(([key,name,aliases,description,color])=>({...stamp,id:ref('char',key),name,aliases,description,color,portraitImageId:image(`character-${key}`).id,isAlive:!['quint','jessel'].includes(key),birthDate:null,tags:[]}))
const items=itemDefs.map(([key,name,description,iconType])=>({...stamp,id:ref('item',key),name,description:key==='manuscript'?'A thin red, gilt-edged album containing the governess’s account in faded ink.':description,iconType,imageId:image(`item-${key}`).id,tags:[]}))
const chapters=[],events=[],sceneTexts=[],characterSnapshots=[],itemPlacements=[]
let sortOrder=0,previousDay=null
const threads=[['sightings','The Apparitions','Reported sights and contradictory testimony complicate the governess’s account.'],['school','Why Miles Was Dismissed','The school’s unexplained letter remains a question the governess cannot resolve.'],['duty','Responsibility and Isolation','The guardian’s prohibition leaves the governess without an easy appeal.'],['children','The Children’s Silence','Affection, privacy, and adult suspicion compete in interpreting the children.'],['manuscript','The Preserved Account','Douglas’s introduction frames a testimony whose authority the reader must assess.']]
const motifs=[['windows','Windows and Watching','Glass, blinds, and sightlines make seeing different from knowing.'],['silence','Silence and Speech','Unspoken questions and incomplete answers shape the mystery.'],['light','Light and Darkness','Candles, daylight, and night vigils mark changing confidence.']]
sourceSections.forEach((s,si)=>{const plan=sectionPlans[si];if(!plan)throw Error(`Missing chapter ${si}`);const paragraphs=s.text.split(/\n{2,}/);const chapterId=ref('chapter',si+1);chapters.push({...stamp,id:chapterId,timelineId:T,number:si+1,title:s.title,synopsis:plan.map(e=>e.description).join(' '),notes:`Original heading: ${s.sourceHeading}`,wordGoal:words(s.text)});plan.forEach((e,ei)=>{if(e.start<0||e.start>=paragraphs.length||ei&&e.start<=plan[ei-1].start)throw Error('Invalid semantic boundary');const eventId=ref('event',`${si+1}-${ei+1}`);const cast=Object.keys(e.states);const threadKeys=si===0?['manuscript','duty']:['duty','children',...(/school|letter|dismiss/i.test(e.title+' '+e.description)?['school']:[]),...(/Quint|Jessel|figure|apparition|sighting|watcher|woman across/i.test(e.title+' '+e.description)?['sightings']:[])];const flashback=si===0||si===11&&ei===1;events.push({...stamp,id:eventId,chapterId,timelineId:T,title:e.title,description:e.description,locationMarkerId:ref('loc',e.location),involvedCharacterIds:cast.map(k=>ref('char',k)),mentionedCharacterIds:[],involvedItemIds:e.items.map(k=>ref('item',k)),threadIds:threadKeys.map(k=>ref('thread',k)),motifIds:motifs.filter(([k])=>k==='silence'||k==='windows'&&/window|watch|sight/i.test(e.description)||k==='light'&&/night|candle|dawn|daylight/i.test(e.description)).map(([k])=>ref('motif',k)),sortOrder:sortOrder++,travelDays:previousDay===null?0:Math.max(0,e.day-previousDay),inWorldTime:151+e.day,tension:e.tension,tags:[],structureBeat:null,status:'complete',povCharacterId:si?ref('char','governess'):null,isFlashback:flashback});previousDay=e.day;const text=paragraphs.slice(e.start,plan[ei+1]?.start??paragraphs.length).join('\n\n');sceneTexts.push({...stamp,id:ref('scene',`${si+1}-${ei+1}`),eventId,text,wordCount:words(text)});cast.forEach((key,i)=>{const place=e.positions[key]||e.location;const loc=locationMarkers.find(l=>l.id===ref('loc',place));characterSnapshots.push({...stamp,id:ref('snapshot',`${si+1}-${ei+1}-${key}`),characterId:ref('char',key),eventId,isAlive:!['quint','jessel'].includes(key)&&!(si===24&&ei===2&&key==='miles'),currentLocationMarkerId:loc.id,currentMapLayerId:loc.mapLayerId,inventoryItemIds:[],inventoryNotes:'',travelModeId:null,sortKey:i,statusNotes:e.states[key]})});e.items.forEach((key,i)=>itemPlacements.push({...stamp,id:ref('placement',`${si+1}-${ei+1}-${key}`),itemId:ref('item',key),eventId,locationMarkerId:ref('loc',e.location),sortKey:i,notes:`Associated with ${e.title}.`}))})})
const event=(chapter,beat=1)=>ref('event',`${chapter+1}-${beat}`)
const relationshipDefs=[['governess','flora','Governess and pupil','mixed','Initial affection is tested by incompatible accounts of what the child sees.'],['governess','miles','Governess and pupil','mixed','Her protective responsibility conflicts with his requests for privacy and school.'],['governess','mrs-grose','Household confidantes','positive','They share responsibility but do not share every perception or inference.'],['miles','flora','Brother and sister','positive','The children share games, companionship, and a coordinated midnight trick.'],['mrs-grose','flora','Housekeeper and child','positive','Mrs. Grose comforts Flora and finally takes her away from Bly.'],['mrs-grose','miles','Housekeeper and child','positive','She defends his character while recalling difficult former associations.'],['uncle','miles','Guardian and nephew','mixed','The uncle provides for Miles while delegating daily responsibility.'],['uncle','flora','Guardian and niece','mixed','The uncle provides for Flora while remaining absent from Bly.'],['uncle','governess','Employer and employee','mixed','His condition of complete silence isolates her in the new appointment.'],['quint','jessel','Former associates','mixed','Mrs. Grose recalls an improper association across a difference in rank.'],['quint','miles','Valet and former companion','mixed','Mrs. Grose remembers the boy spending time with Quint and denying it.'],['jessel','flora','Former governess and pupil','mixed','Jessel taught Flora before the new appointment.'],['douglas','governess','Former acquaintance and custodian','positive','Douglas knew her later as his sister’s governess and preserved her manuscript.'],['douglas','frame-narrator','Reader and listener','positive','Douglas entrusts the account to a sympathetic listener.']]
const relationships=relationshipDefs.map(([a,b,label,sentiment,description],i)=>({...stamp,id:ref('relationship',i+1),characterAId:ref('char',a),characterBId:ref('char',b),label,sentiment,description,strength:5,isBidirectional:true,startEventId:event(['quint','jessel'].includes(a)?a==='quint'&&b==='jessel'?7:8:0)}))
const relationshipSnapshots=[['governess','flora',20,'Rejected protector','negative','Flora asks Mrs. Grose to take her away from the governess.'],['governess','mrs-grose',21,'Allies arranging separation','positive','They agree Mrs. Grose will take Flora to London while the governess remains with Miles.'],['governess','miles',24,'Confession under pressure','mixed','Miles admits the letter theft while the governess holds him and questions him.']].map(([a,b,c,label,sentiment,description],i)=>({...stamp,id:ref('relationship-snapshot',i+1),relationshipId:relationships.find(r=>r.characterAId===ref('char',a)&&r.characterBId===ref('char',b)).id,eventId:event(c),label,sentiment,description,strength:5,isActive:true,sortKey:i*100}))
const loreCategories=[{id:ref('lore-category','source'),worldId:W,name:'Source and Interpretation',color:'#82715f',sortOrder:0},{id:ref('lore-category','household'),worldId:W,name:'Bly and Its Household',color:'#59645b',sortOrder:1}]
const loreDefs=[['edition','source','Source Edition',`Scene drafts reproduce every narrative word of ${sourceEdition}. ${sourceUrl}. The Project Gutenberg license and contents list are not part of the story. The text is public domain in the United States; readers must check their jurisdiction.`,0],['structure','source','The Frame and the Manuscript','The unnumbered fireside opening is given the editorial chapter title The Fireside Manuscript. All twenty-four Roman chapter headings are preserved. Scene cuts use reviewed paragraph boundaries and preserve the entire text in order.',0],['calendar','source','Editorial Calendar','The account begins in June and ends in November, without specifying a year or most dates. 1850 is a neutral editorial anchor, not a claimed historical date. Relative calendar placements are approximate. The Christmas frame is placed forty years later for display only. Reading order is not always chronological: the interview and Miles’s bedroom explanation are remembered passages.',0],['maps','source','Interpreted Geography and Plans','Bly is fictional and located only generally in Essex. Its estate and interior plans are original interpretive drawings, not historical surveys. The coach inn, road, and unspecified Christmas house have indicative positions only; their exact sites are unknown. Map coordinates use distance from the bottom edge.',0],['ambiguity','source','Reported Sight Is Not Confirmed Knowledge','Apparition snapshots represent the governess’s perceived presence. They do not establish that other characters see the figures, that the children are possessed, or what caused the final death.',0],['guardian','household','The Guardian’s Condition','The children’s uncle delegates their care on the express condition that he never be troubled about them.',0],['staff','household','The Former Servants','Mrs. Grose identifies the described figures as the dead valet Peter Quint and former governess Miss Jessel; her account does not explain Jessel’s cause of death.',7]]
const lorePages=loreDefs.map(([key,cat,title,body,c])=>({...stamp,id:ref('lore',key),categoryId:ref('lore-category',cat),title,body,visibleFromEventId:event(c),tags:[],coverImageId:null,linkedEntityIds:[]}))
const factDefs=[['dismissal','Miles Cannot Return to School','The headmaster refuses to readmit Miles without giving particulars.',2,['governess','mrs-grose']],['quint','The Stranger Matches Peter Quint','Mrs. Grose identifies the description as that of the deceased valet.',5,['governess','mrs-grose']],['jessel','The Woman Matches Miss Jessel','Mrs. Grose identifies the described woman as the former governess.',7,['governess','mrs-grose']],['trick','The Midnight Outing Was Arranged','Miles says he arranged Flora’s window signal to make his governess think him bad.',11,['governess','miles']],['contradiction','The Lake Sighting Is Not Shared','Mrs. Grose and Flora deny seeing the woman the governess perceives across the lake.',20,['governess','mrs-grose','flora']],['letter','Miles Took and Burned the Letter','Miles admits reading the letter and burning it.',24,['governess','miles']]]
const knowledgeFacts=factDefs.map(([key,title,description,c])=>({...stamp,id:ref('fact',key),title,description,readerLearnsAtEventId:event(c,c===5?2:c===11?2:1),originEventId:event(c,c===5?2:c===11?2:1),tags:[]}))
const knowledgeReveals=factDefs.flatMap(([key,,,c,cast])=>cast.map(who=>({...stamp,id:ref('reveal',`${key}-${who}`),factId:ref('fact',key),characterId:ref('char',who),eventId:knowledgeFacts.find(f=>f.id===ref('fact',key)).readerLearnsAtEventId,note:'Direct testimony or experience in this scene.'})))
const factions=[{...stamp,id:ref('faction','household'),name:'Bly Household',description:'The children and adults whose daily lives and duties are centered on Bly.',color:'#65705c',tags:[],coverImageId:null}]
const factionMemberships=['governess','mrs-grose','miles','flora','luke'].map((k,i)=>({...stamp,id:ref('membership',k),factionId:factions[0].id,characterId:ref('char',k),role:k==='governess'?'Governess':k==='mrs-grose'?'Housekeeper':k==='luke'?'Servant':'Child',startEventId:event(1),endEventId:k==='flora'||k==='mrs-grose'?event(22):null,notes:''}))
const characterGoals=[['governess','Protect the children and fulfill her charge',1],['miles','Return to school and gain privacy and freedom',14],['mrs-grose','Keep the children safe while supporting their governess',1],['douglas','Share the preserved manuscript with sympathetic listeners',0]].map(([k,text,c],i)=>({...stamp,id:ref('goal',i+1),characterId:ref('char',k),type:'primary',text,startEventId:event(c),endEventId:null}))
const mapRoutes=[['church','The Walk to Church',['front-drive','church-path','churchyard','church']],['lake','The Search Around the Lake',['mooring','lake-bank','far-bank','lake-gate']]].map(([key,name,waypoints])=>({...stamp,id:ref('route',key),mapLayerId:ref('map','bly-estate'),name,routeType:'foot',waypoints:waypoints.map(k=>ref('loc',k)),color:'#746952',notes:'Schematic reading aid; no measured distance or surveyed track is claimed.'}))
const cover=image('world').id
const world={version:18,type:'world',exportedAt:now,world:{...stamp,id:W,name:'The Turn of the Screw',description:'A young governess takes charge of two children at a secluded English estate. Her reports of uncanny watchers draw affection, duty, and suspicion into a haunting mystery whose testimony refuses easy certainty.',coverImageId:cover,theme:'theme-gothic',readingMode:true,continuityStaleThreshold:5,wordTarget:words(narrativeText),calendar:{startYear:1850,yearSuffix:' (editorial)',months:[['January',31],['February',28],['March',31],['April',30],['May',31],['June',30],['July',31],['August',31],['September',30],['October',31],['November',30],['December',31]].map(([name,days])=>({name,days}))}},mapLayers,locationMarkers,characters,items,characterSnapshots,itemPlacements,chapters,events,sceneTexts,blobs,relationships,relationshipSnapshots,timelines:[{...stamp,id:T,name:'The Bly Manuscript',description:'Reading order with the fireside frame and remembered passages marked explicitly.',color:'#756457',dayOffset:0}],plotThreads:threads.map(([key,name,description])=>({...stamp,id:ref('thread',key),name,description,color:'#756457',status:'complete',tags:[]})),motifs:motifs.map(([key,name,description])=>({...stamp,id:ref('motif',key),name,description,color:'#756457',tags:[]})),loreCategories,lorePages,knowledgeFacts,knowledgeReveals,factions,factionMemberships,characterGoals,mapRoutes}
for(const key of ['characterMovements','locationSnapshots','itemSnapshots','travelModes','timelineRelationships','crossTimelineArtifacts','mapRegions','mapRegionSnapshots','mapAnnotations','factionRelationships','continuitySuppressions','writingLogs','sceneRevisions'])world[key]=[]
const normalize=s=>s.replace(/\s+/g,' ').trim()
if(normalize(sceneTexts.map(s=>s.text).join('\n\n'))!==normalize(narrativeText))throw Error('Source-word reconstruction failed')
fs.writeFileSync(new URL('../../library/the-turn-of-the-screw.pwk',import.meta.url),JSON.stringify(world,null,2)+'\n')
console.log({chapters:chapters.length,events:events.length,words:sceneTexts.reduce((n,s)=>n+s.wordCount,0),maps:mapLayers.length,locations:locationMarkers.length,images:blobs.length})
