export const maps = [
  ['england',null,'England and the Road to Bly','Southern England linking the Harley Street appointment to the remote country estate.',1600,1000],
  ['bly-estate','england','Bly Estate','The manor, lawns, lake, church path, gardens, and enclosing woods.',1500,1100],
  ['bly-ground','bly-estate','Bly Manor — Ground Floor','The hall, dining room, drawing room, schoolroom stair, and service wing.',1500,1100],
  ['bly-upper','bly-ground','Bly Manor — Upper Floor','The governess’s room, children’s rooms, schoolroom, corridors, and tower stair.',1500,1100],
  ['bly-tower','bly-upper','Bly Tower and Roof','The old and new towers, battlements, roof walk, and commanding sightlines.',1400,1000],
]

export const locations = [
  ['harley','england','Harley Street House','The children’s uncle maintains an elegant London home and receives the young governess there.',1260,350],
  ['coach-inn','england','Coach Stopping Place','A country inn where the coach stops and onward carriages meet arriving passengers.',880,480],
  ['frame-house','england','The Christmas Country House','An unnamed English country house where guests gather around the hall fire at Christmas.',680,670],
  ['coach-road','england','Road to Bly','A long evening drive passes through a mild, fragrant countryside toward the estate.',610,560],
  ['bly-gateway','england','Bly, Essex','A secluded Essex country estate with a large house, gardens, and ornamental water.',430,610,'bly-estate'],
  ['manor-gateway','bly-estate','Bly Manor','A handsome, many-windowed house whose apparent comfort gradually acquires a watchful quality.',760,650,'bly-ground'],
  ['front-drive','bly-estate','Front Drive','The curving approach where Flora and Mrs. Grose welcome the governess.',770,510],
  ['east-lawn','bly-estate','East Lawn','Open turf beneath the house and tower, exposed to distant watching figures.',1040,650],
  ['lake','bly-estate','The Lake','A still ornamental water bordered by reeds, trees, and an opposite bank.',360,370],
  ['lake-bank','bly-estate','Near Lake Bank','A sheltered place where Flora plays beside the water.',470,420],
  ['far-bank','bly-estate','Far Lake Bank','The opposite margin, visible across the water yet difficult to reach unnoticed.',245,350],
  ['mooring','bly-estate','Boat Mooring','A landing place half a mile from the house, used for the lake’s flat-bottomed rowing boat.',460,330],
  ['lake-gate','bly-estate','Lakeside Fence Gate','A gate in a fence that descends to the water beside a sheltered landing on the opposite shore.',230,420],
  ['church-path','bly-estate','Church Path','The Sunday route from Bly toward the village, screened in places by trees and walls.',1160,410],
  ['church','bly-estate','Village Church','A parish church about twenty minutes’ walk from Bly, with a churchyard beside the approach.',1320,300],
  ['churchyard','bly-estate','Churchyard','Old thick graves and a low table tomb stand beside the path from the gate to the church.',1270,300],
  ['terrace','bly-estate','Manor Terrace','An outdoor terrace alongside the dining-room windows, overlooking the lawn.',900,600],
  ['garden','bly-estate','Garden and Shrubbery','Formal walks and dense planting provide both play space and concealment.',620,270],
  ['hall','bly-ground','Entrance Hall','The bright central hall joins the public rooms, stairs, and front door.',750,190],
  ['drawing-room','bly-ground','Drawing Room','A comfortable room of conversation, letters, and uneasy confidences.',480,560],
  ['dining-room','bly-ground','Dining Room','The household’s dining room has windows opening visually onto the terrace.',1010,560],
  ['window','bly-ground','Dining-Room Window','A broad pane through which the interior and terrace confront one another.',1170,590],
  ['service-wing','bly-ground','Service Wing','Mrs. Grose and the household staff keep Bly’s ordinary routines working.',260,350],
  ['housekeeper-room','bly-ground',"Mrs. Grose’s Room",'A swept and orderly room with a hearth and a sofa, close to the household’s working quarters.',280,540],
  ['main-stair','bly-ground','Main Staircase','The stair connects the reassuring public floor to the dark upper corridors.',750,780,'bly-upper'],
  ['governess-room','bly-upper',"The Governess’s Room",'A large bedroom with a state bed, a full-length mirror, and a smaller curtained bed for Flora.',390,620],
  ['miles-room','bly-upper',"Miles’s Room",'The boy’s room becomes a place for private questions after the house is quiet.',1040,600],
  ['schoolroom','bly-upper','Schoolroom','Books, lessons, sewing, and the children’s performances fill this upper room.',690,340],
  ['upper-corridor','bly-upper','Upper Corridor','A long passage of doors, windows, and candlelit pauses.',760,510],
  ['tower-stair','bly-upper','Tower Stair','A narrow stair rises toward the roof and old battlements.',1250,760,'bly-tower'],
  ['tower-bedroom','bly-upper','Old Tower Bedroom','A spacious, long-unused square bedroom in the old tower, with shuttered windows above the garden.',1250,580],
  ['old-tower','bly-tower','Old Tower','A crenellated tower from which a distant man first watches the governess.',420,560],
  ['new-tower','bly-tower','New Tower','The companion tower and roofline frame views across the estate.',980,560],
  ['roof-walk','bly-tower','Roof Walk','A high stone walk links the towers above the lawns.',700,430],
]

export const characters = [
  ['governess','The Governess',[],'A young clergyman’s daughter accepting her first post, intelligent and intensely responsible for the children entrusted to her.','#a99786'],
  ['miles','Miles',[],'A charming and self-possessed schoolboy whose unexplained dismissal shadows his return to Bly.','#6f8091'],
  ['flora','Flora',[],'Miles’s younger sister, outwardly candid, imaginative, and accomplished at directing adult attention.','#b59a9e'],
  ['mrs-grose','Mrs. Grose',[],'The warm-hearted housekeeper, loyal to the children and the governess despite fear and incomplete knowledge.','#8b735c'],
  ['quint','Peter Quint',[],'The late master’s valet, remembered for presumption, freedom within Bly, and a troubling intimacy with Miles.','#594f48'],
  ['jessel','Miss Jessel',[],'The children’s former governess, whose unhappy position and death remain bound to Bly.','#5e5b68'],
  ['uncle','The Children’s Uncle',[],'A fashionable London bachelor who provides generously on condition that he never be troubled about Bly.','#665b52'],
  ['douglas','Douglas',[],'A fireside guest who preserves and reads the governess’s manuscript years after her death.','#586879'],
  ['frame-narrator','The Fireside Narrator',[],'A listener who records Douglas’s introduction and transmits the manuscript.','#766f66'],
  ['luke','Luke',[],'A Bly servant consulted when Miles’s missing letter becomes important.','#756a5c'],
]

export const items = [
  ['manuscript',"The Governess’s Manuscript",'A faded handwritten account kept under lock by Douglas and read aloud at Christmas.','book'],
  ['uncle-letter',"The Uncle’s Enclosing Letter",'A letter enclosing the headmaster’s sealed communication and asking the governess to deal with it.','letter'],
  ['school-letter',"The School’s Letter",'A sealed communication announcing that Miles cannot return to school.','letter'],
  ['miles-letter',"The Governess’s Letter to Harley Street",'A letter finally written to break the uncle’s rule of silence.','letter'],
  ['candle',"The Governess’s Candle",'A bedroom candle whose light, absence, and sudden extinction measure the night’s uncertainty.','light'],
  ['flora-boat',"Flora’s Toy Boat",'A flat piece of wood with a hole, fitted with another piece as a mast beside the lake.','toy'],
  ['school-books','Lesson Books','The ordinary instruments of lessons, recitation, diversion, and concealment.','book'],
  ['gloves',"The Governess’s Gloves",'Gloves repaired during tea and left on a chair in the dining room before a proposed church visit.','clothing'],
  ['miles-hat',"Miles’s Outdoor Hat",'The boy’s hat, brought into the dining room after a walk and twirled as he asks to go outside again.','clothing'],
  ['rowing-boat','The Lake Boat','An old flat-bottomed boat with a pair of short thick oars, kept at a mooring on the lake.','vehicle'],
  ['amelia',"Fielding’s Amelia",'An eighteenth-century novel from Bly’s collection, read by the governess beside her bedroom candles.','book'],
]
