import fs from 'node:fs';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
const require=createRequire('F:/Projects/WorldBreaker/PlotWeave-cthulhu-qa/package.json'),{chromium}=require('playwright'),qa=new URL('./qa/',import.meta.url);fs.mkdirSync(qa,{recursive:true})
const path=n=>fileURLToPath(new URL(`./qa/${n}`,import.meta.url)),browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],checks=[],views={}
page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});page.on('pageerror',e=>errors.push(`page: ${e.message}`));const assert=(v,l)=>{if(!v)throw Error(l);checks.push(l)},body=async()=>(await page.locator('body').innerText()).replace(/\s+/g,' '),shot=n=>page.screenshot({path:path(n),fullPage:true})
async function visit(name,file,need=[]){await page.getByRole('link',{name,exact:true}).click();await page.waitForTimeout(700);const t=await body();for(const x of need)assert(t.includes(x),`${name} contains ${x}`);views[name]=t.slice(0,5000);await shot(file);return t}
async function images(label){const a=await page.locator('img').evaluateAll(xs=>xs.map(x=>({src:x.src,ok:x.complete&&x.naturalWidth>0})));assert(!a.some(x=>!x.ok),`${label}: all ${a.length} visible images load`);return a.length}
await page.goto('http://127.0.0.1:5175/',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Library'}).click();await page.getByRole('textbox',{name:/Search the library/}).fill('Carmilla');const card=page.getByRole('listitem').filter({hasText:'Carmilla'});const ct=await card.innerText();assert(ct.includes('16 characters · 17 chapters · 67 scenes · 22 locations'),'Library card counts are canonical');assert(ct.includes('53 original generated illustrations'),'Library notice records generated art');await shot('library-dialog.png');await card.getByRole('button',{name:/Download/}).click();await page.waitForURL(/carmilla-world/,{timeout:30000});await page.waitForFunction(()=>document.body.innerText.includes('Reading mode is on'),null,{timeout:60000});await page.waitForTimeout(1000)
const opening=await body();assert(opening.includes('17 Timeline chapters')&&opening.includes('1 scene'),'Opening dashboard shows one revealed scene');await shot('opening-dashboard.png')
await visit('Characters','opening-characters.png',['The Editor']);await images('Opening characters');const om=await visit('Maps','opening-maps.png',['Hesselius']);assert(!om.includes('Karnstein Ruins MAP'),'Future ruins layer is hidden at opening');await images('Opening map');await visit('Items','opening-items.png',['Laura’s Narrative']);await visit('Calendar','opening-calendar.png',['Calendar']);await visit('Lore','opening-lore.png',['Source Edition','Narrative Time','Text, Maps, and Illustrations']);await visit('Factions','opening-factions.png',['Factions']);await visit('Knowledge','opening-knowledge.png',['Knowledge'])
for(let i=0;i<66;i++){await page.getByRole('button',{name:'Next moment'}).click();await page.waitForTimeout(35)}await page.waitForFunction(()=>document.body.innerText.includes('Italy and After'));await page.waitForTimeout(700)
await visit('Dashboard','final-dashboard.png',['17 Timeline chapters','67 scenes','16 Characters','12 Items']);await visit('Timeline','final-timeline.png',['An Early Fright','Ordeal and Execution','Conclusion']);const fc=await visit('Characters','final-characters.png',['Characters 16','Laura','Carmilla','Baron Vordenburg']);assert(await images('Final characters')>=16,'All portraits render');await visit('Items','final-items.png',['Items 12','Portrait of Mircalla','Vordenburg Papers']);assert(await images('Final items')>=12,'All item art renders');await visit('Relations','final-relations.png',['Laura','Carmilla']);await visit('Arc','final-arc.png',['Character Arc','Laura']);await visit('Lore','final-lore.png',['Karnstein','The Oupire']);await visit('Factions','final-factions.png',['The Schloss Household','The Investigators']);await visit('Knowledge','final-knowledge.png',['Carmilla, Millarca, and Mircalla are one person'])
await visit('Maps','final-reading-maps.png',['Maps']);await images('Final reading map');await visit('Settings','settings.png',['Reading mode']);const off=page.getByRole('button',{name:'Turn off reading mode'});assert(await off.count()===1,'Reading-mode control exists');await off.evaluate(e=>e.click());await page.waitForTimeout(600);assert(await page.getByRole('button',{name:'Turn on reading mode'}).count()===1,'Reading mode turns off')
await visit('Maps','final-maps.png',['Maps']);const layers=['Southern Styria','The Schloss Grounds','Inside the Schloss','Karnstein Ruins'],mapImages={};for(const n of layers){await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(600);await page.getByRole('button',{name:n,exact:true}).click({force:true});await page.waitForTimeout(600);const characters=page.getByRole('button',{name:'Characters',exact:true});assert(await characters.count()===1,`Map character toggle exists: ${n}`);await characters.click();await page.waitForTimeout(300);mapImages[n]=await images(`Map ${n}`);checks.push(`Map layer selected without character-pin occlusion: ${n}`);await shot(`map-${n.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-')}.png`)}
for(const view of ['manuscript','corkboard','structure']){await page.goto(`http://127.0.0.1:5175/#/worlds/carmilla-world/${view}`);await page.waitForTimeout(800);const t=await body();assert(t.toLowerCase().includes(view),`${view} renders with reading mode off`);if(view==='manuscript')assert(t.includes('An Early Fright')&&t.includes('Ordeal and Execution'),'Complete manuscript renders');await shot(`${view}.png`)}
assert(errors.length===0,'No browser console or page errors');const results={appCommit:'9295d4a',source:'Library UI download',checks,views,mapImages,consoleErrors:errors};fs.writeFileSync(path('app-results.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify({checks:checks.length,mapImages,consoleErrors:errors},null,2));await browser.close()
