import fs from 'node:fs';import path from 'node:path';import {countWords,narrativeText,sourceEdition,sourceUrl,sourceFileSha256} from './source-text.mjs'
const root=path.resolve(import.meta.dirname,'../..'),m=JSON.parse(fs.readFileSync(new URL('./manuscript.json',import.meta.url))),W='carmilla-world',T='carmilla-timeline',now=Date.UTC(2026,8,22),stamp={worldId:W,createdAt:now,updatedAt:now},id=(k,x)=>`carmilla-${k}-${x}`,blobs=[],imageCache=new Map
function image(kind,key,file){const iid=id('image',`${kind}-${key}`);if(imageCache.has(iid))return imageCache.get(iid);const rel=`library/carmilla/${file??`art/${kind}/${key}.png`}`,p=path.join(root,rel);if(!fs.existsSync(p))throw Error(`Missing ${rel}`);const b=fs.readFileSync(p),out={id:iid,width:b.readUInt32BE(16),height:b.readUInt32BE(20)};blobs.push({...stamp,id:iid,mimeType:'image/png',url:rel});imageCache.set(iid,out);return out}
const mapDefs=[['styria',null,'Southern Styria','The forested district between Gratz, the two inhabited schlosses, and ruined Karnstein.'],['schloss-grounds','styria','The Schloss Grounds','Laura’s moated home, its walks, bridges, chapel, and forest approaches.'],['schloss-interior','schloss-grounds','Inside the Schloss','The principal rooms in which the household lives and watches through the summer.'],['karnstein-ruins','styria','Karnstein Ruins','The abandoned village, roofless chapel, cemetery, and ruined ancestral seat.']]
const mapLayers=mapDefs.map(([k,p,name,description],i)=>{const a=image('map',k,`maps/${k}.png`);return{...stamp,id:id('map',k),name,description,parentMapId:p?id('map',p):null,imageId:a.id,imageWidth:a.width,imageHeight:a.height,scalePixelsPerUnit:null,scaleUnit:null,levelGroupId:null,levelIndex:i,levelLabel:null}})
// PlotWeave's CRS.Simple maps have a bottom-left origin. Each coordinate below
// is anchored to the matching painted estate, room, road, or ruin.
const locDefs=[
['hesselius-study','styria','Hesselius’s Study','A scholar’s papers preserve the case in a frame outside Laura’s own recollection.',null,1435,570],['schloss','styria','Laura’s Schloss','A secluded English household established in a Styrian castle amid miles of forest.','schloss-grounds',835,630],['spielsdorf-schloss','styria','Spielsdorf’s Schloss','The General’s country home, twenty miles from Laura’s family.',null,315,525],['forest-road','styria','Forest Road','The winding western road between isolated estates and Karnstein.',null,520,650],['drunstall-turn','styria','Drunstall Turning','A fork where the travelers meet the General and continue toward the ruins.',null,570,430],['ruined-village','styria','Karnstein','An abandoned village beneath a ruined chateau, three miles west of Laura’s home.','karnstein-ruins',210,850],
['lime-walk','schloss-grounds','Lime-Tree Walk','A shaded avenue used for summer conversation and quiet observation.',null,445,334],['drawbridge','schloss-grounds','Drawbridge','The fixed bridge crossing the swan-filled moat before the castle gate.',null,445,559],['courtyard','schloss-grounds','Courtyard','The enclosed court where travelers, servants, and itinerant performers arrive.',null,450,694],['great-hall','schloss-grounds','Schloss Interior','The inhabited rooms beyond the castle gate.','schloss-interior',450,814],
['great-hall','schloss-interior','Great Hall','An oak-paneled hall where restored family portraits are unpacked.',null,750,534],['drawing-room','schloss-interior','Drawing Room','A crimson-furnished evening room for the small household.',null,335,344],['library','schloss-interior','Library','The room used for private medical and family consultations.',null,1100,354],['carmilla-room','schloss-interior','Carmilla’s Room','A stately guest chamber with doors that can be locked from within.',null,1260,734],['laura-room','schloss-interior','Laura’s Room','Laura’s candlelit chamber, kept locked during the district’s illness.',null,310,789],['nursery','schloss-interior','Nursery','The steep-roofed upper room remembered from Laura’s sixth year.',null,990,769],
['ruined-village','karnstein-ruins','Ruined Village','Roofless homes and empty lanes left after the old depopulation.',null,490,529],['karnstein-chapel','karnstein-ruins','Karnstein Chapel','A roofless Gothic church containing the family monuments.',null,810,709],['hidden-tomb','karnstein-ruins','Mircalla’s Hidden Tomb','A monument concealed by vegetation and altered masonry.',null,1380,814],['masquerade-hall','styria','Grand Duke’s Masquerade','A distant ceremonial hall recalled in the General’s embedded account.',null,1400,530],['bertha-room','styria','Bertha’s Room','The ward’s sickroom and its adjoining dark dressing room.',null,315,525],['italy','styria','Italy','The southern journey taken after Laura’s ordeal.',null,1400,100]
]
const artLoc=new Set(['hesselius-study','schloss','nursery','lime-walk','drawbridge','courtyard','great-hall','drawing-room','carmilla-room','laura-room','library','forest-road','drunstall-turn','masquerade-hall','spielsdorf-schloss','bertha-room','ruined-village','karnstein-chapel','hidden-tomb','italy'])
const seen=new Map;const locationMarkers=locDefs.map(([k,map,name,description,link,x,y])=>{const n=(seen.get(k)||0)+1;seen.set(k,n);return{...stamp,id:id('loc',n>1?`${k}-${map}`:k),name,description,mapLayerId:id('map',map),linkedMapLayerId:link?id('map',link):null,x,y,iconType:link?'building':'landmark',imageId:artLoc.has(k)?image('locations',k).id:null,tags:[],factionId:null}})
const locBy=(key)=>locationMarkers.find(x=>x.id===id('loc',key))??locationMarkers.find(x=>x.id.startsWith(id('loc',key)))
const charDefs=[['editor','The Editor',[],'The careful publisher who presents a strange medical case.'],['laura','Laura',[],'An English young woman raised in an isolated Styrian schloss.'],['carmilla','Carmilla',[],'A beautiful young traveler entrusted to Laura’s household after a carriage accident.'],['father','Laura’s Father',[],'A kindly retired English officer living with his daughter in Styria.'],['perrodon','Madame Perrodon',[],'Laura’s warm-hearted Swiss governess and longtime companion.'],['lafontaine','Mademoiselle De Lafontaine',[],'Laura’s lively finishing governess.'],['spielsdorf','General Spielsdorf',[],'An old family friend recently altered by grief.'],['bertha','Bertha Rheinfeldt',[],'The General’s beloved young ward.'],['countess','The Countess',[],'Carmilla’s imposing and secretive mother.'],['vordenburg','Baron Vordenburg',[],'An antiquarian whose family papers concern Karnstein.'],['gratz-doctor','The Physician from Gratz',[],'A learned doctor consulted in a baffling illness.'],['doctor','The Doctor',[],'The district physician who attends Laura’s household.'],['priest','The Priest',[],'An elderly clergyman called to comfort and protect the household.'],['woodman','The Woodman',[],'An old forest worker who remembers Karnstein traditions.'],['mountebank','The Mountebank',[],'A traveling musician and seller of charms.'],['pale-man','The Pale Gentleman',[],'A formal messenger who interrupts the masquerade.']]
const characters=charDefs.map(([k,name,aliases,description],i)=>({...stamp,id:id('char',k),name,aliases,description,color:['#7d655d','#8c6b72','#504654'][i%3],portraitImageId:image('characters',k).id,isAlive:true,birthDate:null,tags:[]}))
const itemDefs=[['mircalla-portrait','Portrait of Mircalla','A restored ancestral portrait dated 1698.'],['amulets','Vellum Amulets','Two perfumed charms sold as protection against the oupire.'],['spielsdorf-letter','Spielsdorf’s Letter','The General’s grief-stricken letter postponing his visit.'],['vordenburg-papers','Vordenburg Papers','Old journals and plans concerning Karnstein monuments.'],['carriage','Traveling Carriage','The noble traveling carriage overturned before the schloss.'],['tooth-tools','Steel Instruments','The mountebank’s case of small steel tools.'],['masks','Masquerade Masks','Masks worn at the Grand Duke’s ball.'],['physician-note','Physician’s Note','The written diagnosis entrusted to General Spielsdorf.'],['sword','The General’s Sword','Spielsdorf’s sword, carried during his watch and journey.'],['woodman-axe','Woodman’s Axe','The old forester’s working axe.'],['commission-report','Commission Report','The official record of proceedings at Karnstein.'],['case-manuscript','Laura’s Narrative','The written case later preserved among Hesselius’s papers.']]
const items=itemDefs.map(([k,name,description])=>({...stamp,id:id('item',k),name,description,iconType:'artifact',imageId:image('items',k).id,tags:[]}))
const castIds=new Set(charDefs.map(x=>x[0])),itemIds=new Set(itemDefs.map(x=>x[0]));let prev=0
const chapters=m.chapters.map(c=>({...stamp,id:c.id,timelineId:T,number:c.number+1,title:c.title,synopsis:m.events.filter(e=>e.chapterId===c.id).map(e=>e.description).join(' '),notes:`Authorial heading: ${c.sourceHeading}`,wordGoal:c.wordCount}))
const events=m.events.map((e,i)=>{const loc=locBy(e.location)??locBy('schloss'),out={...stamp,id:e.id,chapterId:e.chapterId,timelineId:T,title:e.title,description:e.description,locationMarkerId:loc.id,involvedCharacterIds:e.cast.filter(x=>castIds.has(x)).map(x=>id('char',x)),mentionedCharacterIds:[],involvedItemIds:e.items.filter(x=>itemIds.has(x)).map(x=>id('item',x)),threadIds:[id('thread',i<24?'guest':i<43?'illness':'karnstein')],motifIds:[id('motif',/dream|night|moon|sleep/i.test(e.title+e.description)?'night':'doubling')],sortOrder:i,travelDays:i-prev,inWorldTime:i,tension:e.tension,tags:[],structureBeat:null,status:'complete',povCharacterId:id('char',e.cast.includes('spielsdorf')&&!e.cast.includes('laura')?'spielsdorf':'laura'),isFlashback:e.location==='masquerade-hall'||e.location==='bertha-room'};prev=i;return out})
const sceneTexts=m.sceneTexts.map(s=>({...stamp,...s}));const characterSnapshots=[];for(const e of events){const loc=locationMarkers.find(x=>x.id===e.locationMarkerId);e.involvedCharacterIds.forEach((cid,j)=>characterSnapshots.push({...stamp,id:id('snapshot',`${e.id}-${j}`),characterId:cid,eventId:e.id,isAlive:true,currentLocationMarkerId:loc.id,currentMapLayerId:loc.mapLayerId,inventoryItemIds:j?[]:e.involvedItemIds,inventoryNotes:'',travelModeId:null,sortKey:e.sortOrder+j/100,statusNotes:`${characters.find(c=>c.id===cid).name} is physically present and acts from a distinct position during “${e.title}”.`}))}
const ev=n=>events[n]?.id??events[0].id
const timelines=[{...stamp,id:T,name:'Laura’s Narrative',description:'The prologue and sixteen chapters in reading order, with embedded recollections marked as flashbacks.',color:'#6e4b55',dayOffset:0}]
const plotThreads=[['guest','The Unexpected Guest','An accident brings a secretive young traveler into an isolated household.'],['illness','The District Illness','Deaths, dreams, and bodily weakness disturb the summer’s apparent calm.'],['karnstein','The Karnstein Inheritance','Family portraits, ruins, and old testimony draw the inquiry westward.']].map(([k,name,description])=>({...stamp,id:id('thread',k),name,description,color:'#6e4b55',status:'complete',tags:[]}))
const motifs=[['night','Night and Thresholds','Moonlight, locked doors, dreams, and crossings blur safety and danger.'],['doubling','Likeness and Doubling','Faces, names, memories, and repeated stories resist a single stable identity.']].map(([k,name,description])=>({...stamp,id:id('motif',k),name,description,color:'#596b5d',tags:[]}))
const relationships=[['laura','father','Daughter and father','positive',ev(1)],['laura','carmilla','Host and guest','mixed',ev(7)],['spielsdorf','bertha','Guardian and ward','positive',ev(3)],['spielsdorf','carmilla','Guardian and guest','mixed',ev(43)]].map(([a,b,label,sentiment,startEventId],i)=>({...stamp,id:id('relationship',i),characterAId:id('char',a),characterBId:id('char',b),label,sentiment,description:`${label} within the events as first understood.`,strength:6,isBidirectional:true,startEventId}))
const loreCategories=[{...stamp,id:id('lore-category','edition'),name:'Edition and Reading',color:'#76525c',sortOrder:0},{...stamp,id:id('lore-category','world'),name:'Styria and Karnstein',color:'#586857',sortOrder:1}]
const lorePages=[['source','edition','Source Edition',`Scene drafts reproduce ${sourceEdition}. Source: ${sourceUrl}. SHA-256: ${sourceFileSha256}. Project Gutenberg packaging, licence, contents list, and publisher advertisements are excluded; the prologue, all sixteen authorial headings, and complete narrative prose are retained. Original English; no translator. First published in 1872 and public domain in the United States.`,ev(0)],['calendar','edition','Narrative Time','The calendar follows reading order because Laura’s account gives relative summer intervals but no complete civil dates. Embedded recollections are marked as flashbacks.',ev(0)],['art','edition','Text, Maps, and Illustrations','The cover, portraits, objects, locations, and interpretive maps are original generated artwork in a restrained nineteenth-century engraved-and-oil style. Maps are reading aids rather than surveyed claims.',ev(0)],['karnstein','world','Karnstein','A ruined village and chateau stand three miles west of Laura’s home, associated with her mother’s extinct family.',ev(1)],['oupire','world','The Oupire','Local people use this word for a feared nocturnal cause of wasting illness.',ev(17)]].map(([k,c,title,body,visibleFromEventId])=>({...stamp,id:id('lore',k),categoryId:id('lore-category',c),title,body,visibleFromEventId,tags:[],coverImageId:null,linkedEntityIds:[]}))
const factDefs=[['likeness','The restored portrait resembles Carmilla','The portrait named Mircalla bears Carmilla’s remarkable likeness.',ev(19)],['mark','Laura bears a blue mark','The physician finds a small discolored spot below Laura’s throat.',ev(37)],['names','Carmilla, Millarca, and Mircalla are one person','Spielsdorf identifies the three names after the chapel encounter.',ev(59)],['tomb','Vordenburg can locate Mircalla’s tomb','His inherited papers preserve the monument’s concealed position.',ev(60)]]
const knowledgeFacts=factDefs.map(([k,title,description,at])=>({...stamp,id:id('fact',k),title,description,readerLearnsAtEventId:at,originEventId:at,tags:[]})),knowledgeReveals=factDefs.flatMap(([k,,,at])=>[{...stamp,id:id('reveal',k),factId:id('fact',k),characterId:id('char','laura'),eventId:at,note:'Learned through direct observation or testimony.'}])
const factions=[['household','The Schloss Household','Laura’s small multilingual household and its servants.'],['karnsteins','House of Karnstein','The extinct noble family connected to the ruined western estate.'],['investigators','The Investigators','Those who compare medicine, testimony, archives, and local tradition.']].map(([k,name,description])=>({...stamp,id:id('faction',k),name,description,color:'#65535b',tags:[],coverImageId:null}))
const factionMemberships=[['household','laura','Daughter'],['household','father','Head of household'],['household','perrodon','Governess'],['household','lafontaine','Governess'],['investigators','spielsdorf','Witness'],['investigators','vordenburg','Antiquarian']].map(([f,c,role],i)=>({...stamp,id:id('membership',i),factionId:id('faction',f),characterId:id('char',c),role,startEventId:ev(0),endEventId:null,notes:''}))
const characterGoals=[['laura','Understand the guest whose presence feels both familiar and strange',ev(7),ev(59)],['father','Protect Laura while discovering the cause of her decline',ev(36),ev(63)],['spielsdorf','Complete the inquiry that brought him to Karnstein',ev(41),ev(63)]].map(([c,text,startEventId,endEventId],i)=>({...stamp,id:id('goal',i),characterId:id('char',c),type:'primary',text,startEventId,endEventId}))
const mapRoutes=[['western-road','Road to Karnstein','styria',['schloss','drunstall-turn','ruined-village']],['grounds','Schloss Walk','schloss-grounds',['great-hall','drawbridge','lime-walk']],['ruins','Ruins Inquiry','karnstein-ruins',['ruined-village-karnstein-ruins','karnstein-chapel','hidden-tomb']]].map(([k,name,map,pts])=>({...stamp,id:id('route',k),mapLayerId:id('map',map),name,routeType:'road',waypoints:pts.map(x=>locBy(x).id),color:'#7d5d58',notes:'Interpretive route based on narrated movement.'}))
const itemPlacements=events.flatMap(e=>e.involvedItemIds.map((iid,i)=>({...stamp,id:id('placement',`${e.id}-${i}`),itemId:iid,eventId:e.id,locationMarkerId:e.locationMarkerId,sortKey:i,notes:`Present during “${e.title}”.`})))
const cover=image('world','cover','art/world.png').id
const world={version:18,type:'world',exportedAt:now,world:{...stamp,id:W,name:'Carmilla',description:'In an isolated Styrian schloss, a lonely young woman receives a beautiful and secretive guest whose arrival unsettles memory, affection, and the boundaries of ordinary illness.',coverImageId:cover,theme:'theme-gothic',readingMode:true,continuityStaleThreshold:5,wordTarget:countWords(narrativeText),calendar:{startYear:1870,yearSuffix:'',months:[{name:'Summer',days:100}]}},mapLayers,locationMarkers,characters,items,characterSnapshots,itemPlacements,chapters,events,sceneTexts,blobs,relationships,relationshipSnapshots:[],timelines,plotThreads,motifs,loreCategories,lorePages,knowledgeFacts,knowledgeReveals,factions,factionMemberships,characterGoals,mapRoutes,characterMovements:[],continuitySuppressions:[],crossTimelineArtifacts:[],factionRelationships:[],itemSnapshots:[],locationSnapshots:[],mapAnnotations:[],mapRegionSnapshots:[],mapRegions:[],sceneRevisions:[],timelineRelationships:[],travelModes:[],writingLogs:[]}
fs.writeFileSync(path.join(root,'library/carmilla.pwk'),JSON.stringify(world));console.log({chapters:chapters.length,events:events.length,characters:characters.length,locations:locationMarkers.length,maps:mapLayers.length,items:items.length,images:blobs.length})
