import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {narrativeText,normalize,countWords} from './source-text.mjs'
const root=path.resolve(import.meta.dirname,'../..'),d=JSON.parse(fs.readFileSync(path.join(root,'library/carmilla.pwk'),'utf8')),fail=m=>{throw Error(m)},uniq=a=>new Set(a).size===a.length
if(d.chapters.length!==17||d.events.length!==67||d.sceneTexts.length!==67)fail('Unexpected manuscript counts')
if(normalize(d.sceneTexts.map(s=>s.text).join('\n\n'))!==normalize(narrativeText))fail('Prose reconstruction failed')
if(d.sceneTexts.reduce((n,s)=>n+s.wordCount,0)!==countWords(narrativeText))fail('Word count mismatch')
const snaps=Map.groupBy(d.characterSnapshots,s=>s.eventId);for(const e of d.events){const a=(snaps.get(e.id)||[]).map(x=>x.characterId).sort(),b=[...e.involvedCharacterIds].sort();if(JSON.stringify(a)!==JSON.stringify(b)||!uniq(a))fail(`Snapshot mismatch ${e.title}`);if(!uniq((snaps.get(e.id)||[]).map(x=>x.statusNotes)))fail(`Duplicate status ${e.title}`)}
const layers=new Map(d.mapLayers.map(x=>[x.id,x]));for(const m of d.locationMarkers){const l=layers.get(m.mapLayerId);if(!l||m.x<0||m.y<0||m.x>l.imageWidth||m.y>l.imageHeight)fail(`Bad marker ${m.name}`)}for(const l of d.mapLayers.filter(x=>x.parentMapId)){const g=d.locationMarkers.filter(x=>x.linkedMapLayerId===l.id);if(g.length!==1||g[0].mapLayerId!==l.parentMapId)fail(`Bad gateway ${l.name}`)}
const landmarkAnchors=[[1435,570],[835,630],[315,525],[520,650],[570,430],[210,850],[445,334],[445,559],[450,694],[450,814],[750,534],[335,344],[1100,354],[1260,734],[310,789],[990,769],[490,529],[810,709],[1380,814],[1400,530],[315,525],[1400,100]]
for(const [i,m] of d.locationMarkers.entries()){const [x,y]=landmarkAnchors[i]??[];if(m.x!==x||m.y!==y)fail(`Marker is not on its illustrated landmark: ${m.name}`)}
const hashes=[];for(const b of d.blobs){const p=path.join(root,b.url.replaceAll('/',path.sep));if(!fs.existsSync(p))fail(`Missing ${b.url}`);hashes.push(crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex'))}if(!uniq(hashes)||d.blobs.length!==49)fail('Artwork missing or duplicated')
console.log(JSON.stringify({chapters:d.chapters.length,events:d.events.length,words:countWords(narrativeText),characters:d.characters.length,snapshots:d.characterSnapshots.length,locations:d.locationMarkers.length,maps:d.mapLayers.length,routes:d.mapRoutes.length,items:d.items.length,images:d.blobs.length,brokenImages:0,duplicateArtwork:0},null,2))
