import fs from 'node:fs';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url'
const require=createRequire('F:/Projects/WorldBreaker/PlotWeave-cthulhu-qa/package.json'),{chromium}=require('playwright'),qa=new URL('./qa/',import.meta.url);fs.mkdirSync(qa,{recursive:true})
const path=n=>fileURLToPath(new URL(`./qa/${n}`,import.meta.url)),browser=await chromium.launch({headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[],checks=[],views={}
page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`)});page.on('pageerror',e=>errors.push(`page: ${e.message}`));const assert=(v,l)=>{if(!v)throw Error(l);checks.push(l)},body=async()=>(await page.locator('body').innerText()).replace(/\s+/g,' '),shot=n=>page.screenshot({path:path(n),fullPage:true})
async function visit(name,file,need=[]){await page.getByRole('link',{name,exact:true}).click();await page.waitForTimeout(900);const t=await body();for(const x of need)assert(t.includes(x),`${name} contains ${x}`);views[name]=t.slice(0,5000);await shot(file);return t}
async function images(label){const a=await page.locator('img').evaluateAll(xs=>xs.map(x=>({src:x.src,ok:x.complete&&x.naturalWidth>0,w:x.naturalWidth,h:x.naturalHeight})));assert(!a.some(x=>!x.ok),`${label}: all ${a.length} visible images load`);return a.length}
await page.goto('http://127.0.0.1:5175/',{waitUntil:'networkidle'});await page.getByRole('button',{name:'Library'}).click();await page.getByRole('textbox',{name:/Search the library/}).fill('Call of Cthulhu');const card=page.getByRole('listitem').filter({hasText:'The Call of Cthulhu'});const ct=await card.innerText();assert(ct.includes('11 characters · 3 chapters · 12 scenes · 21 locations'),'Library card counts are canonical');assert(ct.includes('46 original generated illustrations'),'Library card records original generated art');await shot('library-dialog.png');await card.getByRole('button',{name:/Download/}).click();await page.waitForURL(/call-of-cthulhu-world/,{timeout:30000});await page.waitForFunction(()=>document.body.innerText.includes('Reading mode is on'),null,{timeout:60000});await page.waitForTimeout(1000)
const opening=await body();assert(opening.includes('3 Timeline chapters')&&opening.includes('1 scene'),'Opening dashboard shows one revealed scene');await shot('opening-dashboard.png')
const oc=await visit('Characters','opening-characters.png',['Francis Wayland Thurston','George Gammell Angell']);assert(!oc.includes('Gustaf Johansen'),'Johansen is spoiler-gated at opening');await images('Opening characters')
const om=await visit('Maps','opening-maps.png',['Providence']);assert(!om.includes('R’lyeh MAP'),'Future R’lyeh layer is hidden at opening');await images('Opening map');await visit('Items','opening-items.png',['Angell’s Document Box','Wilcox Bas-relief']);await images('Opening items');await visit('Calendar','opening-calendar.png',['Calendar']);await visit('Lore','opening-lore.png',['Source Edition','A Tale in Three Records','Text, Maps, and Illustrations']);await visit('Factions','opening-factions.png',['Factions']);await visit('Knowledge','opening-knowledge.png',['Knowledge'])
for(let i=0;i<11;i++){await page.getByRole('button',{name:'Next moment'}).click();await page.waitForTimeout(120)}await page.waitForFunction(()=>document.body.innerText.includes('Ch.3 · The Alert Escapes'));await page.waitForTimeout(800)
await visit('Dashboard','final-dashboard.png',['3 Timeline chapters','12 scenes','11 Characters','9 Items']);await visit('Timeline','final-timeline.png',['The Horror in Clay','The Tale of Inspector Legrasse','The Madness from the Sea']);const fc=await visit('Characters','final-characters.png',['Characters 11','Gustaf Johansen','Castro','Cthulhu']);assert(await images('Final characters')>=11,'All character portraits render');await visit('Items','final-items.png',['Items 9','Cult Idol','Johansen Manuscript','Alert’s Wheel']);assert(await images('Final items')>=9,'All item art renders');await visit('Relations','final-relations.png',['Francis Wayland Thurston','George Gammell Angell']);await visit('Arc','final-arc.png',['Character Arc','Francis Wayland Thurston']);await visit('Lore','final-lore.png',['The Cthulhu Cult','The Pacific Coordinates']);await visit('Factions','final-factions.png',['Scholarly Investigators','New Orleans Police','Cthulhu Cult','Crew of the Emma']);await visit('Knowledge','final-knowledge.png',['The opened door released Cthulhu','Johansen left a private English account'])
await visit('Maps','final-reading-maps.png',['Maps']);await images('Final reading-mode map')
await visit('Settings','settings.png',['Reading mode']);const off=page.getByRole('button',{name:'Turn off reading mode'});assert(await off.count()===1,'Reading-mode control exists');await off.evaluate(e=>e.click());await page.waitForTimeout(800);assert(await page.getByRole('button',{name:'Turn on reading mode'}).count()===1,'Reading mode turns off');await visit('Maps','final-maps.png',['Maps']);const layers=['A World of Separate Clues','Providence and College Hill','The Louisiana Swamp','R’lyeh'],mapImages={};for(const n of layers){await page.reload({waitUntil:'networkidle'});await page.waitForTimeout(800);await page.getByRole('button',{name:n,exact:true}).click({force:true});await page.waitForTimeout(800);const characters=page.getByRole('button',{name:'Characters',exact:true});assert(await characters.count()===1,`Map character toggle exists: ${n}`);await characters.click();await page.waitForTimeout(300);mapImages[n]=await images(`Map ${n}`);checks.push(`Map layer selected without character-pin occlusion: ${n}`);await shot(`map-${n.toLowerCase().replaceAll(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')}.png`)}for(const view of ['manuscript','corkboard','structure']){await page.goto(`http://127.0.0.1:5175/#/worlds/call-of-cthulhu-world/${view}`);await page.waitForTimeout(900);const t=await body();assert(t.toLowerCase().includes(view),`${view} renders with reading mode off`);if(view==='manuscript')assert(t.includes('The CALL of CTHULHU')&&t.includes('Three men were swept up'),'Complete manuscript renders after reading mode is disabled');await shot(`${view}.png`)}
assert(errors.length===0,'No browser console or page errors');const results={appCommit:'9295d4a',source:'Library UI download',checks,views,mapImages,consoleErrors:errors};fs.writeFileSync(path('app-results.json'),JSON.stringify(results,null,2)+'\n');console.log(JSON.stringify({checks:checks.length,mapImages,consoleErrors:errors},null,2));await browser.close()
