import fs from 'node:fs'
import {maps,locations,characters as characterDefs,items as itemDefs} from './world-ledger.mjs'
import {chapterPlans,withCuts} from './story-ledger.mjs'
import {sourceSections,narrativeText,sourceEdition,sourceUrl,sourceFileSha256,normalize,countWords} from './source-text.mjs'

const W='call-of-cthulhu-world',T='call-of-cthulhu-timeline',now=Date.UTC(2026,8,22),stamp={worldId:W,createdAt:now,updatedAt:now},id=(k,v)=>`coc-${k}-${v}`
// Leaflet's CRS.Simple uses a bottom-left origin. These anchors are matched to
// the labelled dots, buildings, and route circles painted into each map.
const coords={
 'providence-gateway':[405,728],'new-orleans':[320,674],'swamp-gateway':[320,674],'st-louis':[340,717],oslo:[728,828],sydney:[1348,359],auckland:[1460,337],pacific:[315,282],'rlyeh-gateway':[202,232],
 'angell-house':[485,624],brown:[620,682],'wilcox-studio':[880,440],waterfront:[1350,374],
 'bayou-landing':[275,691],'squatter-village':[780,819],'cult-clearing':[1060,734],'police-camp':[1160,534],
 landing:[273,742],'cyclopean-city':[650,639],'great-door':[1004,575],channel:[1254,184]
}
const blobs=[]
function image(kind,key,path){const url=`library/call-of-cthulhu/${path??`art/${kind}/${key}.png`}`,disk=new URL(`../../${url}`,import.meta.url);if(!fs.existsSync(disk))throw Error(`Missing ${url}`);const b=fs.readFileSync(disk);const imageId=id('image',`${kind}-${key}`);blobs.push({...stamp,id:imageId,mimeType:'image/png',url});return{id:imageId,width:b.readUInt32BE(16),height:b.readUInt32BE(20)}}
const mapLayers=maps.map(([key,parent,name,description],i)=>{const a=image('map',key,`maps/${key}.png`);return{...stamp,id:id('map',key),name,description,parentMapId:parent?id('map',parent):null,imageId:a.id,imageWidth:a.width,imageHeight:a.height,scalePixelsPerUnit:null,scaleUnit:null,levelGroupId:null,levelIndex:i,levelLabel:null}})
const locationMarkers=locations.map(([key,map,name,description,link])=>({...stamp,id:id('loc',key),name,description,mapLayerId:id('map',map),linkedMapLayerId:link?id('map',link):null,x:coords[key][0],y:coords[key][1],iconType:link?'building':'landmark',imageId:image('locations',key).id,tags:[],factionId:null}))
const characters=characterDefs.map(([key,name,aliases,description,color])=>({...stamp,id:id('char',key),name,aliases,description,color,portraitImageId:image('characters',key).id,isAlive:!['angell','johansen','briden'].includes(key),birthDate:null,tags:[]}))
const items=itemDefs.map(([key,name,description,iconType])=>({...stamp,id:id('item',key),name,description,iconType,imageId:image('items',key).id,tags:[]}))
const chapters=[],events=[],sceneTexts=[],characterSnapshots=[],itemPlacements=[];let order=0,prev=0
const aliveAt=(key,c,e)=>key==='angell'?c===1&&e<4:key==='briden'?!(c===3&&e===4):key==='johansen'?true:true
for(let ci=0;ci<3;ci++){
 const s=sourceSections[ci],plan=withCuts(s,chapterPlans[ci]),paras=s.text.split(/\n{2,}/),chapterId=id('chapter',ci+1)
 chapters.push({...stamp,id:chapterId,timelineId:T,number:ci+1,title:s.title,synopsis:plan.map(e=>e.description).join(' '),notes:`Authorial division: ${s.sourceHeading}`,wordGoal:countWords(s.text)})
 for(let ei=0;ei<4;ei++){const e=plan[ei],eventId=id('event',`${ci+1}-${ei+1}`),day=ci*4+ei,loc=locationMarkers.find(x=>x.id===id('loc',e.location));
  const threadKeys=[ci===0?'papers':'',ci===1?'cult':'',ci===2?'sea':'',ci>0||ei>0?'correlation':''].filter(Boolean),motifKeys=[/dream|fever/i.test(e.title+e.description)?'dreams':'',/idol|relief|clay|stone|portal/i.test(e.title+e.description)?'images':'',/paper|notes|testimony|manuscript|clipping/i.test(e.title+e.description)?'documents':'',/sea|yacht|island|R’lyeh/i.test(e.title+e.description)?'sea':''].filter(Boolean)
  events.push({...stamp,id:eventId,chapterId,timelineId:T,title:e.title,description:e.description,locationMarkerId:loc.id,involvedCharacterIds:e.cast.map(k=>id('char',k)),mentionedCharacterIds:[],involvedItemIds:e.items.map(k=>id('item',k)),threadIds:threadKeys.map(k=>id('thread',k)),motifIds:motifKeys.map(k=>id('motif',k)),sortOrder:order++,travelDays:day-prev,inWorldTime:day,tension:e.tension,tags:[],structureBeat:null,status:'complete',povCharacterId:id('char',ci===2&&ei>1?'johansen':'thurston'),isFlashback:ci===1||ci===2&&ei>1});prev=day
  const text=paras.slice(e.cut,plan[ei+1]?.cut??paras.length).join('\n\n');sceneTexts.push({...stamp,id:id('scene',`${ci+1}-${ei+1}`),eventId,text,wordCount:countWords(text)})
  e.cast.forEach((key,i)=>characterSnapshots.push({...stamp,id:id('snapshot',`${ci+1}-${ei+1}-${key}`),characterId:id('char',key),eventId,isAlive:aliveAt(key,ci+1,ei+1),currentLocationMarkerId:loc.id,currentMapLayerId:loc.mapLayerId,inventoryItemIds:e.items.filter((_,n)=>n===i).map(k=>id('item',k)),inventoryNotes:'',travelModeId:null,sortKey:ci+1+(ei+1)/10,statusNotes:`${characterDefs.find(x=>x[0]===key)[1]} ${status(key,e.title,i)}.`}))
  e.items.forEach((key,i)=>itemPlacements.push({...stamp,id:id('placement',`${ci+1}-${ei+1}-${key}`),itemId:id('item',key),eventId,locationMarkerId:loc.id,sortKey:i,notes:`Present during “${e.title}”.`}))
 }
}
function status(key,title,i){const v={thurston:'connects inherited evidence during',angell:'records disturbing testimony during',wilcox:'reports dream-born impressions during',legrasse:'pursues material evidence during',webb:'compares field experience during',castro:'guards and discloses cult tradition during',johansen:'acts as sailor and witness during',emma:'receives the visiting inquirer during',briden:'endures the voyage during',cthulhu:'is perceived through signs or presence during',swanson:'commands the police party during'};return `${v[key]??'participates in'} “${title}”${i?` from a distinct position in the scene`:''}`}
const event=(c,e=1)=>id('event',`${c}-${e}`)
const timelines=[{...stamp,id:T,name:'Thurston’s Assembled Record',description:'The three authorial sections in reading order; embedded events from 1907, 1908, and 1925 are marked as retrospective testimony.',color:'#50645d',dayOffset:0}]
const plotThreads=[['papers','Angell’s Papers','An inherited box makes a private scholarly puzzle available to a skeptical reader.'],['cult','The Hidden Cult','Matching words and images connect distant rites without making their full meaning safe.'],['sea','The Emma and the Alert','A newspaper report leads from two ships to an uncharted Pacific place.'],['correlation','Dissociated Knowledge','Separate observations become dangerous when a mind begins to join them.']].map(([k,name,description])=>({...stamp,id:id('thread',k),name,description,color:'#536b63',status:'complete',tags:[]}))
const motifs=[['dreams','Dreams and Fever','Sleep, delirium, and creative vision carry impressions ordinary inquiry cannot explain.'],['images','Repeated Images','Clay, stone, sketches, and carvings preserve the same unsettling outline.'],['documents','Documents and Testimony','The tale reaches its narrator through boxes, reports, clippings, interviews, and a sailor’s manuscript.'],['sea','Black Seas','Oceans divide the evidence while concealing the place to which it points.']].map(([k,name,description])=>({...stamp,id:id('motif',k),name,description,color:'#64746b',tags:[]}))
const relDefs=[['thurston','angell','Grand-nephew and grand-uncle','positive','Thurston inherits the scholar’s papers and intellectual burden.',event(1,1)],['angell','wilcox','Scholar and witness','mixed','Angell questions a sculptor whose dreams resist ordinary explanation.',event(1,2)],['angell','legrasse','Consulted scholar and investigator','positive','Legrasse brings an object Angell helps compare with other evidence.',event(2,1)],['legrasse','webb','Investigators comparing evidence','positive','The policeman’s idol matches the anthropologist’s northern memory.',event(2,1)],['legrasse','castro','Interrogator and prisoner','negative','Legrasse questions a captive who speaks more freely than the others.',event(2,4)],['johansen','briden','Shipmates','positive','The last two sailors return to the Alert together.',event(3,2)],['thurston','emma','Visitor and widow','positive','A shared concern for Johansen’s record gives Thurston access to the manuscript.',event(3,2)] ]
const relationships=relDefs.map(([a,b,label,sentiment,description,startEventId],i)=>({...stamp,id:id('relationship',i+1),characterAId:id('char',a),characterBId:id('char',b),label,sentiment,description,strength:6,isBidirectional:true,startEventId}))
const relationshipSnapshots=[]
const loreCategories=[{...stamp,id:id('lore-category','edition'),name:'Edition and Reading',color:'#796d5d',sortOrder:0},{...stamp,id:id('lore-category','world'),name:'The Recorded World',color:'#52675e',sortOrder:1}]
const lorePages=[
 ['source','edition','Source Edition',`Scene drafts reproduce ${sourceEdition}. Source: ${sourceUrl}. SHA-256: ${sourceFileSha256}. Project Gutenberg framing and licence text are excluded; the story title, byline, transcriber’s note, epigraph, original illustration caption, footnote, three headings, and complete prose are retained. Original English; no translator. First published in the United States in 1928 and now public domain there.`,event(1,1)],
 ['structure','edition','A Tale in Three Records','The story’s three headings are Lovecraft’s own. Each section nests older testimony inside Thurston’s account, so the reading chronology moves backward and forward as documents are opened.',event(1,1)],
 ['calendar','edition','Dates and Narrative Order','The timeline follows reading order. Historical dates stated in the text range from the 1907 Louisiana raid through Thurston’s later inquiry; retrospective scenes are marked as such rather than forced into a false continuous calendar.',event(1,1)],
 ['art','edition','Text, Maps, and Illustrations','The cover, portraits, objects, locations, and interpretive maps are original generated artwork in a restrained 1920s ink-and-oil style. Maps are reading aids rather than surveyed historical claims.',event(1,1)],
 ['rlyeh','world','R’lyeh','The name first appears in Wilcox’s dream reports, attached to a city of dripping stone and unfamiliar geometry.',event(1,2)],
 ['cult','world','The Cthulhu Cult','Legrasse’s evidence describes a secret tradition scattered among isolated communities and maritime routes.',event(2,4)],
 ['coordinates','world','The Pacific Coordinates','Johansen’s record fixes the risen island near 47° 9′ south, 126° 43′ west.',event(3,3)]
].map(([k,c,title,body,visibleFromEventId])=>({...stamp,id:id('lore',k),categoryId:id('lore-category',c),title,body,visibleFromEventId,tags:[],coverImageId:null,linkedEntityIds:[]}))
const factDefs=[
 ['dream','Wilcox formed the relief after a dream','The sculptor says the wet clay took shape after his vision of a vast city.',event(1,2),['angell','wilcox','thurston']],
 ['parallel','The strange dreams occurred worldwide','Angell’s collected reports cluster around Wilcox’s fever in March and April 1925.',event(1,3),['angell','thurston']],
 ['match','Webb recognizes the idol’s design','The Louisiana statuette and Webb’s Greenland memory share image and chant.',event(2,2),['angell','legrasse','webb']],
 ['cult','The prisoners describe an ancient secret cult','Castro’s testimony supplies names and beliefs guarded across generations.',event(2,4),['legrasse','castro']],
 ['alert','Johansen survived aboard the Alert','The Sydney report names the rescued second mate and the captured yacht.',event(3,1),['thurston','johansen']],
 ['manuscript','Johansen left a private English account','His widow preserves a document intended to keep its subject from casual readers.',event(3,2),['thurston','emma','johansen']],
 ['island','The sailors landed on R’lyeh','Johansen identifies the risen city behind the newspaper’s unnamed island.',event(3,3),['johansen','briden','thurston']],
 ['awakening','The opened door released Cthulhu','The landing party’s accidental act gives the repeated image a living referent.',event(3,4),['johansen','briden','thurston']]
]
const knowledgeFacts=factDefs.map(([k,title,description,at])=>({...stamp,id:id('fact',k),title,description,readerLearnsAtEventId:at,originEventId:at,tags:[]})),knowledgeReveals=factDefs.flatMap(([k,,,at,who])=>who.map(c=>({...stamp,id:id('reveal',`${k}-${c}`),factId:id('fact',k),characterId:id('char',c),eventId:at,note:'Learned by observation, document, or testimony.'})))
const factionDefs=[['scholars','Scholarly Investigators','Researchers who compare artifacts, languages, dreams, and expedition records.','#655f52'],['police','New Orleans Police','The officers who cross the bayous to investigate disappearances and ritual activity.','#585f62'],['cult','Cthulhu Cult','A hidden network preserving ritual words, images, and expectations across generations.','#44584e'],['emma','Crew of the Emma','The merchant schooner’s sailors, forced into a fatal encounter in the South Pacific.','#536873']]
const factions=factionDefs.map(([k,name,description,color])=>({...stamp,id:id('faction',k),name,description,color,tags:[],coverImageId:null}))
const memberships=[['scholars','angell','Semitic scholar',event(1,1)],['scholars','webb','Anthropologist',event(2,1)],['police','legrasse','Inspector',event(2,1)],['police','swanson','Captain',event(2,3)],['cult','castro','Initiate',event(2,4)],['emma','johansen','Second mate',event(3,1)],['emma','briden','Sailor',event(3,1)]]
const factionMemberships=memberships.map(([f,c,role,startEventId],i)=>({...stamp,id:id('membership',i+1),factionId:id('faction',f),characterId:id('char',c),role,startEventId,endEventId:null,notes:''}))
const goals=[['thurston','Understand the papers inherited from Professor Angell',event(1,1),event(3,4)],['angell','Compare Wilcox’s reports with earlier evidence',event(1,2),event(2,2)],['legrasse','Identify the idol recovered in the swamp',event(2,1),event(2,4)],['johansen','Bring the captured Alert and its surviving crew away from the island',event(3,3),event(3,4)]]
const characterGoals=goals.map(([c,text,startEventId,endEventId],i)=>({...stamp,id:id('goal',i+1),characterId:id('char',c),type:'primary',text,startEventId,endEventId}))
const routeDefs=[['inquiry','Thurston’s Inquiry','world',['providence-gateway','sydney','auckland','oslo'],'sea'],['swamp','Police Route','swamp',['bayou-landing','squatter-village','cult-clearing','police-camp'],'trail'],['rlyeh','Landing and Escape','rlyeh',['landing','cyclopean-city','great-door','channel'],'sea']]
const mapRoutes=routeDefs.map(([k,name,map,points,routeType])=>({...stamp,id:id('route',k),mapLayerId:id('map',map),name,routeType,waypoints:points.map(p=>id('loc',p)),color:'#8a7658',notes:'Interpretive route based on narrated movement; no surveyed distance is claimed.'}))
const cover=image('world','cover','art/world.png').id
const world={version:18,type:'world',exportedAt:now,world:{...stamp,id:W,name:'The Call of Cthulhu',description:'Inherited papers draw a skeptical Boston scholar into a network of dreams, artifacts, police testimony, and maritime records whose fragments point beyond familiar history and geography.',coverImageId:cover,theme:'theme-horror',readingMode:true,continuityStaleThreshold:5,wordTarget:countWords(narrativeText),calendar:{startYear:1925,yearSuffix:'',months:[{name:'January',days:31},{name:'February',days:28},{name:'March',days:31},{name:'April',days:30},{name:'May',days:31},{name:'June',days:30},{name:'July',days:31},{name:'August',days:31},{name:'September',days:30},{name:'October',days:31},{name:'November',days:30},{name:'December',days:31}]}},mapLayers,locationMarkers,characters,items,characterSnapshots,itemPlacements,chapters,events,sceneTexts,blobs,relationships,relationshipSnapshots,timelines,plotThreads,motifs,loreCategories,lorePages,knowledgeFacts,knowledgeReveals,factions,factionMemberships,characterGoals,mapRoutes,characterMovements:[],continuitySuppressions:[],crossTimelineArtifacts:[],factionRelationships:[],itemSnapshots:[],locationSnapshots:[],mapAnnotations:[],mapRegionSnapshots:[],mapRegions:[],sceneRevisions:[],timelineRelationships:[],travelModes:[],writingLogs:[]}
if(normalize(sceneTexts.map(s=>s.text).join('\n\n'))!==normalize(narrativeText))throw Error('Scene reconstruction failed')
fs.writeFileSync(new URL('../../library/call-of-cthulhu.pwk',import.meta.url),JSON.stringify(world))
console.log(JSON.stringify({chapters:chapters.length,events:events.length,words:countWords(narrativeText),characters:characters.length,locations:locationMarkers.length,maps:mapLayers.length,items:items.length,images:blobs.length},null,2))
