import fs from 'node:fs'
import { maps as mapDefs, locations as locationDefs, characters as characterDefs, items as itemDefs } from './world-ledger.mjs'
import { sectionPlans } from './story-ledger.mjs'
import { sourceSections, narrativeText, sourceEdition, sourceUrl, sourceSha256, normalize, countWords } from './source-text.mjs'

const W='thirty-nine-steps-world',T='steps-timeline',now=Date.UTC(2026,8,15),ref=(k,v)=>`steps-${k}-${v}`,stamp={worldId:W,createdAt:now,updatedAt:now}
const coordinates={
  london:[1070,300],galloway:[590,495],berkshire:[990,230],'kent-road':[1120,235],bradgate:[1250,180],
  'oxford-circus':[735,520],'hannay-flat':[720,605],'portland-place':[700,625],'st-pancras':[950,875],'london-streets':[1010,800],'jermyn-street':[725,375],'scotland-yard':[795,235],'queen-anne-gate':[740,250],'queen-anne-room':[755,260],'admiralty-map-room':[830,250],
  'northbound-line':[835,445],'galloway-railway':[320,610],'galloway-moor':[680,630],'galloway-inn':[520,505],'moor-road':[750,500],'moor-village':[920,520],'sir-harry-house':[1320,680],'political-hall':[880,440],'mountain-pass':[640,790],roadworks:[310,430],'side-glen':[980,710],'turnbull-cottage':[900,245],
  'moffat-junction':[750,470],'black-stone-farm':[245,350],'black-stone-study':[560,500],'farm-storeroom':[700,480],'old-mill':[310,670],'secret-aerodrome':[1280,790],
  'sir-walter-house':[920,260],'sir-walter-study':[940,265],'ruff-clifftop':[840,700],'ruff-anchorage':[1000,250],'trafalgar-lodge':[1000,665],'thirty-nine-steps':[905,525]
}
const blobs=[]
function image(kind,key,path=`art/${kind}/${key}.png`){const url=`library/the-thirty-nine-steps/${path}`,disk=new URL(`../../${url}`,import.meta.url);if(!fs.existsSync(disk))throw Error(`Missing ${url}`);const b=fs.readFileSync(disk);if(b.toString('hex',0,8)!=='89504e470d0a1a0a')throw Error(`Not PNG ${url}`);const id=ref('image',`${kind}-${key}`);blobs.push({...stamp,id,mimeType:'image/png',url});return {id,width:b.readUInt32BE(16),height:b.readUInt32BE(20)}}
const mapLayers=mapDefs.map(([key,parent,name,description],i)=>{const a=image('map',key,`maps/${key}.png`);return {...stamp,id:ref('map',key),name,description,parentMapId:parent?ref('map',parent):null,imageId:a.id,imageWidth:a.width,imageHeight:a.height,scalePixelsPerUnit:null,scaleUnit:null,levelGroupId:null,levelIndex:i,levelLabel:null}})
const locationMarkers=locationDefs.map(([key,map,name,description,child])=>({...stamp,id:ref('loc',key),name,description,mapLayerId:ref('map',map),linkedMapLayerId:child?ref('map',child):null,x:coordinates[key][0],y:coordinates[key][1],iconType:child?'building':'landmark',imageId:image('locations',key).id,tags:[],factionId:null}))
const characters=characterDefs.map(([key,name,aliases,description,color])=>({...stamp,id:ref('char',key),name,aliases,description,color,portraitImageId:image('characters',key).id,isAlive:key!=='scudder',birthDate:null,tags:[]}))
const items=itemDefs.map(([key,name,description,iconType])=>({...stamp,id:ref('item',key),name,description,iconType,imageId:image('items',key).id,tags:[]}))
const chapters=[],events=[],sceneTexts=[],characterSnapshots=[],itemPlacements=[];let previous=sectionPlans[0][0].time,order=0
const mentionPatterns={karolides:/karolides/i,scudder:/scudder/i,jopley:/jopley/i,'sir-walter':/sir walter/i,macgillivray:/macgillivray/i,royer:/royer/i,'old-man':/black stone leader|hooded leader/i}
const threadDefs=[['conspiracy','The Black Stone Conspiracy','Scudder’s warning grows into a race to prevent stolen military intelligence reaching Germany.'],['fugitive','The Double Pursuit','Hannay evades both police and the men who murdered Scudder.'],['disguise','The Art of Disguise','Clothes, voice, behavior, and expectation repeatedly decide who is seen and who remains hidden.'],['clue','The Thirty-Nine Steps','A coded notebook, high tide, and a counted staircase lead to the escape point.'],['war','The Approach of War','The concealed struggle unfolds in the weeks before Britain enters the First World War.']]
const motifDefs=[['identity','Identity and Performance','Names, disguises, manners, and social assumptions make identity unstable.'],['landscape','Reading the Landscape','Hannay survives by reading roads, hills, cover, coast, and human settlement.'],['watching','Watching and Recognition','Glances, aerial search, close inspection, and remembered gestures expose danger.'],['chance','Chance and Improvisation','Accident repeatedly supplies Hannay with both peril and opportunity.']]
for(let ci=0;ci<sourceSections.length;ci++){const s=sourceSections[ci],plan=sectionPlans[ci],paras=s.text.split(/\n{2,}/),chapterId=ref('chapter',ci+1);chapters.push({...stamp,id:chapterId,timelineId:T,number:ci+1,title:s.title,synopsis:plan.map(e=>e.description).join(' '),notes:`Original source heading: ${s.sourceHeading}`,wordGoal:countWords(s.text)});for(let ei=0;ei<plan.length;ei++){const e=plan[ei];if(e.start<0||e.start>=paras.length||ei&&e.start<=plan[ei-1].start)throw Error(`Bad boundary ${ci+1}.${ei+1}`);const id=ref('event',`${ci+1}-${ei+1}`),cast=Object.keys(e.cast),lower=(e.title+' '+e.description).toLowerCase(),mentioned=Object.entries(mentionPatterns).filter(([key,re])=>!cast.includes(key)&&re.test(e.title+' '+e.description)).map(([key])=>ref('char',key));const threads=['conspiracy',...(ci>=1&&ci<=7?['fugitive']:[]),...(/disguis|roadman|milkman|twisdon|impost|acting|identity/.test(lower)?['disguise']:[]),...(ci>=8?['clue']:[]),...(/war|karolides|naval|military/.test(lower)?['war']:[])];const motifs=[...(/disguis|recogn|identity|imperson|actor|name|twisdon/.test(lower)?['identity']:[]),...(/moor|road|hill|coast|cliff|landscape|rail/.test(lower)?['landscape']:[]),...(/watch|search|glance|eyes|find|spot|inspect/.test(lower)?['watching']:[]),...(/chance|crash|accident|unexpected|improvis/.test(lower)?['chance']:[])];events.push({...stamp,id,chapterId,timelineId:T,title:e.title,description:e.description,locationMarkerId:ref('loc',e.location),involvedCharacterIds:cast.map(x=>ref('char',x)),mentionedCharacterIds:mentioned,involvedItemIds:e.items.map(x=>ref('item',x)),threadIds:[...new Set(threads)].map(x=>ref('thread',x)),motifIds:[...new Set(motifs)].map(x=>ref('motif',x)),sortOrder:order++,travelDays:Math.max(0,e.time-previous),inWorldTime:e.time,tension:e.tension,tags:[],structureBeat:null,status:'complete',povCharacterId:ref('char','hannay'),isFlashback:false});previous=e.time;const text=paras.slice(e.start,plan[ei+1]?.start??paras.length).join('\n\n');sceneTexts.push({...stamp,id:ref('scene',`${ci+1}-${ei+1}`),eventId:id,text,wordCount:countWords(text)});cast.forEach((key,i)=>{const loc=locationMarkers.find(x=>x.id===ref('loc',e.location));characterSnapshots.push({...stamp,id:ref('snapshot',`${ci+1}-${ei+1}-${key}`),characterId:ref('char',key),eventId:id,isAlive:key!=='scudder'||!(ci===0&&ei===4),currentLocationMarkerId:loc.id,currentMapLayerId:loc.mapLayerId,inventoryItemIds:key==='hannay'?e.items.map(x=>ref('item',x)):[],inventoryNotes:key==='hannay'&&e.items.length?`Carries or uses ${e.items.map(x=>itemDefs.find(y=>y[0]===x)[1]).join(', ')} in this event.`:'',travelModeId:null,sortKey:(ci+1)+order/1e6,statusNotes:e.cast[key]})});e.items.forEach((key,i)=>itemPlacements.push({...stamp,id:ref('placement',`${ci+1}-${ei+1}-${key}`),itemId:ref('item',key),eventId:id,locationMarkerId:ref('loc',e.location),sortKey:i,notes:`Present and narratively active during “${e.title}”.`}))}}
const event=(c,e=1)=>ref('event',`${c}-${e}`)
const relationships=[
 ['hannay','scudder','Reluctant host and hunted agent','positive','Scudder entrusts Hannay with the conspiracy and leaves him the duty of continuing the fight.',event(1,2)],
 ['hannay','innkeeper','Fugitive and protector','positive','The innkeeper believes Hannay’s adventure and shields him from pursuers.',event(3,5)],
 ['hannay','sir-harry','Unexpected allies','positive','Sir Harry trusts Hannay’s character and opens a path to Whitehall.',event(4,3)],
 ['hannay','turnbull','Strangers bound by practical kindness','positive','Turnbull lends a disguise and later nurses Hannay without demanding explanations.',event(5,2)],
 ['hannay','sir-walter','Field agent and intelligence chief','positive','Sir Walter tests Hannay’s evidence and then accepts him as an operational ally.',event(7,5)],
 ['hannay','old-man','Adversaries','negative','The Black Stone leader repeatedly tries to identify, confine, and defeat Hannay.',event(5,5)],
 ['hannay','dark-man','Hunter and hunted','negative','The dark man pursues Hannay and later carries the stolen naval secret toward the coast.',event(3,7)],
 ['hannay','lisping-man','Hunter and hunted','negative','The smiling actor searches for Hannay and helps stage the final deception.',event(3,7)],
 ['old-man','dark-man','Black Stone collaborators','positive','The leader directs the dark courier as part of the same espionage cell.',event(5,5)],
 ['old-man','lisping-man','Black Stone collaborators','positive','The leader relies on the plump actor’s adaptable identities.',event(5,5)],
].map(([a,b,label,sentiment,description,start],i)=>({...stamp,id:ref('relationship',i+1),characterAId:ref('char',a),characterBId:ref('char',b),label,sentiment,description,strength:5,isBidirectional:true,startEventId:start}))
const relationshipSnapshots=[
 [0,event(1,4),'Trusted successor','positive','Scudder chooses Hannay to continue the work if he dies.',7],
 [4,event(7,6),'Operational allies','positive','Sir Walter accepts the decoded notebook and clears Hannay with the police.',8],
 [5,event(10,7),'Recognition beneath the mask','negative','Hannay recognizes the leader’s gesture and ends the Appleton performance.',10],
].map(([ri,eventId,label,sentiment,description,strength],i)=>({...stamp,id:ref('relationship-snapshot',i+1),relationshipId:relationships[ri].id,eventId,label,sentiment,description,strength,isActive:true,sortKey:i}))
const plotThreads=threadDefs.map(([k,name,description])=>({...stamp,id:ref('thread',k),name,description,color:'#6f604b',status:'complete',tags:[]})),motifs=motifDefs.map(([k,name,description])=>({...stamp,id:ref('motif',k),name,description,color:'#66705d',tags:[]}))
const loreCategories=[{...stamp,id:ref('lore-category','edition'),name:'Edition and Editorial Method',color:'#796650',sortOrder:0},{...stamp,id:ref('lore-category','world'),name:'The World of the Novel',color:'#536069',sortOrder:1}]
const lorePages=[
 ['source','edition','Source Edition',`Scene drafts reproduce every retained word of ${sourceEdition}. Exact file: ${sourceUrl}. SHA-256: ${sourceSha256}. Gutenberg packaging, duplicate title and contents, illustration placeholder, delimiters, and licence are excluded; the dedication, date, headings, and narrative are retained. Original English; no translator. Public domain in the United States.`,event(1)],
 ['boundaries','edition','Extraction and Reconstruction','Extraction begins at the dedication to Thomas Arthur Nelson and ends after the final narrative paragraph. The dedication remains before Chapter I in its first scene. Event cuts are reviewed paragraph boundaries. The validator reconstructs the normalized extracted source with no omitted, duplicated, or reordered words.',event(1)],
 ['calendar','edition','Editorial Calendar','The source specifies 24 May, 31 May, 12 June, 14 June, and 15 June. It closes seven weeks before Britain enters the war, fixing the action in 1914. Intermediate dates and times are editorial approximations constrained by travel, nights, the ten-day illness, and explicit clock times.',event(1)],
 ['maps','edition','Map Method','Britain and London use approximate real geography. Buchan fictionalizes the Galloway pursuit and invents Bradgate and the Ruff; those maps and the Black Stone farm plan are interpretive. Marker coordinates are measured upward from the bottom edge and were visually checked in Kathala.',event(2,6)],
 ['geopolitics','world','Europe before the War','Scudder interprets unrest in the Balkans and great-power rivalry as the surface of a deeper plot. His account contains period prejudice as well as intelligence that later events partially verify.',event(1,3)],
 ['black-stone','world','The Black Stone','A disciplined espionage organization able to use political violence, false identities, aircraft, and social camouflage.',event(3,6)],
 ['recognition','world','Peter Pienaar’s Rule','Hannay remembers that a disguise succeeds when the wearer inhabits the assumed life completely; the principle explains both his escapes and his enemies’ final performance.',event(5,3)],
]
.map(([k,c,title,body,visibleFromEventId])=>({...stamp,id:ref('lore',k),categoryId:ref('lore-category',c),title,body,visibleFromEventId,tags:[],coverImageId:null,linkedEntityIds:[]}))
const factDefs=[
 ['plot','A plot targets Karolides on 15 June','Scudder says Karolides will be assassinated during his London visit.',event(1,3),['hannay','scudder']],
 ['book','Scudder hid the notebook','The coded black notebook was concealed in Hannay’s tobacco jar.',event(2,2),['hannay']],
 ['cipher','Julia Czechenyi unlocks the cipher','Using Julia as the key makes Scudder’s numerical notes readable.',event(3,6),['hannay']],
 ['plans','Naval plans are the real objective','The Black Stone intends to steal secret dispositions from Royer’s conference.',event(4,1),['hannay']],
 ['leader','The archaeologist leads the Black Stone','The hooded eyes identify the remote farm’s owner as Scudder’s feared leader.',event(6,4),['hannay']],
 ['cleared','Hannay is no longer a murder suspect','Scudder’s delayed letter and police inquiry remove Hannay from the suspect list.',event(7,6),['hannay','sir-walter']],
 ['death','Karolides has been assassinated','The telephone confirms Scudder’s first prediction.',event(7,7),['hannay','sir-walter']],
 ['impostor','Lord Alloa was impersonated','The conference visitor is a spy while the real First Sea Lord remains at home.',event(8,6),['hannay','sir-walter','royer','drew','winstanley','whittaker']],
 ['ruff','The steps are at the Ruff','Tide tables and coastguard memory identify the Bradgate headland.',event(9,5),['hannay','coastguard','royer','drew','winstanley','whittaker']],
 ['appleton','Appleton is the hooded leader','A remembered finger movement breaks the Black Stone cell’s domestic performance.',event(10,7),['hannay','old-man','dark-man','lisping-man']],
 ['yacht','The Ariadne is secured','British officers seize the yacht before the courier can deliver the plans.',event(10,9),['hannay','scaife','old-man','dark-man','lisping-man']],
]
const knowledgeFacts=factDefs.map(([k,title,description,at])=>({...stamp,id:ref('fact',k),title,description,readerLearnsAtEventId:at,originEventId:at,tags:[]})),knowledgeReveals=factDefs.flatMap(([k,,,at,people])=>people.map((p,i)=>({...stamp,id:ref('reveal',`${k}-${p}`),factId:ref('fact',k),characterId:ref('char',p),eventId:at,note:'Learns or confirms this through direct testimony, observation, or the shared discussion.'})))
const blackCover=image('factions','black-stone').id
const factions=[['black-stone','The Black Stone','A covert continental espionage cell seeking military advantage through assassination and stolen intelligence.','#35383a',blackCover],['intelligence','British Intelligence','Officials and field allies working to protect the Anglo-French naval arrangements.','#465d68',null],['police','Scotland Yard','The police service pursuing the Portland Place case and later closing the coastal net.','#485052',null]].map(([k,name,description,color,coverImageId])=>({...stamp,id:ref('faction',k),name,description,color,tags:[],coverImageId}))
const factionMemberships=[['black-stone','old-man','Cell leader',event(5,5)],['black-stone','dark-man','Courier and killer',event(3,7)],['black-stone','lisping-man','Actor and pursuer',event(3,7)],['black-stone','alloa-impostor','Conference infiltrator',event(8,6)],['intelligence','sir-walter','Senior official',event(7,5)],['intelligence','hannay','Civilian field ally',event(7,6)],['intelligence','royer','French military partner',event(8,7)],['intelligence','whittaker','Admiralty official',event(8,7)],['police','macgillivray','Director',event(8,2)],['police','scaife','Field officer',event(9,6)]].map(([f,c,role,startEventId],i)=>({...stamp,id:ref('membership',i+1),factionId:ref('faction',f),characterId:ref('char',c),role,startEventId,endEventId:null,notes:''}))
const characterGoals=[['hannay','Carry Scudder’s warning to someone able to act before 15 June',event(2,1),event(7,6)],['hannay','Recover the stolen naval plans before the courier leaves Britain',event(8,7),event(10,9)],['scudder','Expose the Black Stone’s plot while staying alive',event(1,2),event(1,5)],['old-man','Deliver the stolen naval dispositions to Germany',event(5,5),event(10,9)],['sir-walter','Protect the Anglo-French conference and contain the breach',event(7,6),event(10,9)]].map(([c,text,startEventId,endEventId],i)=>({...stamp,id:ref('goal',i+1),characterId:ref('char',c),type:'primary',text,startEventId,endEventId}))
const mapRoutes=[['flight','Hannay’s Flight North and South','britain',['london','galloway','moffat-junction','berkshire','london','bradgate'],'road'],['london','London Pursuit','london',['hannay-flat','portland-place','st-pancras','scotland-yard','jermyn-street','queen-anne-gate','admiralty-map-room'],'road'],['galloway','Across the Galloway Hills','galloway',['galloway-railway','galloway-moor','galloway-inn','moor-road','sir-harry-house','mountain-pass','roadworks','side-glen','black-stone-farm','turnbull-cottage'],'trail'],['farm','Escape from the Farm','black-stone-farm',['black-stone-study','farm-storeroom','old-mill','secret-aerodrome'],'trail'],['ruff','The Coastal Interception','ruff',['ruff-clifftop','trafalgar-lodge','thirty-nine-steps','ruff-anchorage'],'trail']].map(([k,name,map,points,routeType])=>({...stamp,id:ref('route',k),mapLayerId:ref('map',map),name,routeType,waypoints:points.map(x=>ref('loc',x)),color:'#7a563c',notes:'Editorial route based on the source; no surveyed distance is claimed.'}))
const cover=image('world','cover','art/world.png').id
const world={version:18,type:'world',exportedAt:now,world:{...stamp,id:W,name:'The Thirty-Nine Steps',description:'In the weeks before the First World War, a restless mining engineer inherits a murdered agent’s coded warning and races across Britain between police pursuit and a conspiracy hidden behind impeccable respectability.',coverImageId:cover,theme:'theme-action',readingMode:true,continuityStaleThreshold:5,wordTarget:countWords(narrativeText),calendar:{startYear:1914,yearSuffix:' (editorial chronology)',months:[['January',31],['February',28],['March',31],['April',30],['May',31],['June',30],['July',31],['August',31],['September',30],['October',31],['November',30],['December',31]].map(([name,days])=>({name,days}))}},mapLayers,locationMarkers,characters,items,characterSnapshots,itemPlacements,chapters,events,sceneTexts,blobs,relationships,relationshipSnapshots,timelines:[{...stamp,id:T,name:'Hannay’s Account',description:'The ten chapters in their original reading order, mapped onto the reconstructed calendar of May–August 1914.',color:'#765f46',dayOffset:0}],plotThreads,motifs,loreCategories,lorePages,knowledgeFacts,knowledgeReveals,factions,factionMemberships,characterGoals,mapRoutes}
for(const k of ['characterMovements','locationSnapshots','itemSnapshots','travelModes','timelineRelationships','crossTimelineArtifacts','mapRegions','mapRegionSnapshots','mapAnnotations','factionRelationships','continuitySuppressions','writingLogs','sceneRevisions'])world[k]=[]
if(normalize(sceneTexts.map(x=>x.text).join('\n\n'))!==normalize(narrativeText))throw Error('Source reconstruction failed')
fs.writeFileSync(new URL('../../library/the-thirty-nine-steps.pwk',import.meta.url),JSON.stringify(world,null,2)+'\n')
console.log({chapters:chapters.length,events:events.length,words:sceneTexts.reduce((n,x)=>n+x.wordCount,0),characters:characters.length,locations:locationMarkers.length,maps:mapLayers.length,items:items.length,images:blobs.length,snapshots:characterSnapshots.length,sourceSha256})
