export const maps = [
  ['britain', null, 'Britain in 1914', 'Southern Britain and the rail, road, and coastal arc of Hannay’s pursuit.'],
  ['london', 'britain', 'London', 'Central London from Portland Place and St Pancras to Whitehall and Queen Anne’s Gate.'],
  ['galloway', 'britain', 'The Galloway Hills', 'An interpretive map of the fictionalized hill country traversed during Hannay’s flight.'],
  ['black-stone-farm', 'galloway', 'The Black Stone Farm', 'An invented site plan based on the house, disused mill, burn, plantations, and hidden aerodrome.'],
  ['ruff', 'britain', 'The Ruff at Bradgate', 'An interpretive plan of Buchan’s fictional Kent headland and its cliff staircases.'],
]

export const locations = [
  ['london','britain','London','The capital where Hannay’s boredom gives way to Scudder’s conspiracy.','london'],
  ['galloway','britain','Galloway','The southwestern Scottish hill country Hannay chooses for concealment.','galloway'],
  ['berkshire','britain','Berkshire','The wooded southern county where Sir Walter receives Hannay beside a trout stream.'],
  ['kent-road','britain','Road to Kent','The moonlit road carrying Hannay and Scaife toward the coast.'],
  ['bradgate','britain','Bradgate and the Ruff','The fictional Kent resort beside the chalk headland named in Scudder’s clue.','ruff'],
  ['oxford-circus','london','Oxford Circus','The busy junction where Hannay gives England one final day to provide adventure.'],
  ['hannay-flat','london','Hannay’s Flat','The first-floor Portland Place rooms where Scudder hides and is murdered.'],
  ['portland-place','london','Portland Place','The guarded street Hannay escapes in a milkman’s clothes.'],
  ['st-pancras','london','St Pancras Station','The great rail terminus where Hannay catches the moving northbound train.'],
  ['london-streets','london','North London Streets','Fields, terraces, and mean streets Hannay walks after Scotland Yard clears him.'],
  ['jermyn-street','london','Jermyn Street','The West End street where Jopley recognizes Hannay and starts a public fight.'],
  ['scotland-yard','london','Scotland Yard','The police offices where MacGillivray removes Hannay from suspicion.'],
  ['queen-anne-gate','london','Queen Anne’s Gate Hall','Sir Walter’s entrance hall and alcove, where Hannay detects the impostor.'],
  ['queen-anne-room','london','Conference Room','The private room in which British and French officials discuss secret naval plans.'],
  ['admiralty-map-room','london','Admiralty Map Room','A book-lined office where tide tables and charts solve Scudder’s coastal clue.'],
  ['northbound-line','britain','Northbound Railway','The long train journey from London through Dumfries toward Galloway.'],
  ['galloway-railway','galloway','Galloway Railway','A lonely single line among heather hills and burns.'],
  ['galloway-moor','galloway','Open Moor','Exposed ridges, burns, and heather across which Hannay is repeatedly hunted.'],
  ['galloway-inn','galloway','The Literary Innkeeper’s Inn','A small roadside inn where books fill the young landlord’s study.'],
  ['moor-road','galloway','The Moor Roads','Narrow hill roads followed by bicycles, motorcars, police, and pursuers.'],
  ['moor-village','galloway','Moorland Village','A straggling settlement whose post office receives the police warning.'],
  ['sir-harry-house','galloway','Sir Harry’s Shooting Lodge','A comfortable pine-fringed lodge where Hannay finds an unexpected ally.'],
  ['political-hall','galloway','Election Hall','A crowded rural hall where Hannay speaks under the name Twisdon.'],
  ['mountain-pass','galloway','Mountain Pass','A bare crest where the search aeroplane spots Hannay.'],
  ['roadworks','galloway','Turnbull’s Road Section','A roadside quarry and stone heap where Hannay becomes a spectacled roadman.'],
  ['side-glen','galloway','The Side Glen','A remote valley where Hannay releases Jopley and later wakes to a police beat.'],
  ['turnbull-cottage','galloway','Turnbull’s Cottage','The roadman’s plain home beside a stream, secure through his reticence.'],
  ['moffat-junction','britain','Moffat Junction','The main-line station reached by cattle truck on Hannay’s return south.'],
  ['black-stone-farm','galloway','The Remote Farm','The secluded experimental establishment controlled by the hooded-eyed leader.','black-stone-farm'],
  ['black-stone-study','black-stone-farm','The Study','A veranda room of books and archaeology where the old man reveals himself.'],
  ['farm-storeroom','black-stone-farm','The Storeroom','A locked stone chamber holding mining detonators and lentonite.'],
  ['old-mill','black-stone-farm','The Disused Mill','A ruined mill whose loft and flat roof hide the injured fugitive.'],
  ['secret-aerodrome','black-stone-farm','Secret Aerodrome','A concealed plateau landing ground connected to the conspiracy’s search plane.'],
  ['sir-walter-house','britain','Sir Walter’s Riverside Cottage','A white-gated Berkshire house beside a trout stream.'],
  ['sir-walter-study','britain','Sir Walter’s Study','A comfortable room of books and trophies where Scudder’s evidence is tested.'],
  ['ruff-clifftop','ruff','The Ruff Clifftop','A line of villas and golf links above private stairs cut down the chalk.'],
  ['ruff-anchorage','ruff','Offshore Anchorage','The water off the Ruff where the steam yacht Ariadne waits.'],
  ['trafalgar-lodge','ruff','Trafalgar Lodge','Mr Appleton’s ordinary seaside villa, masking the Black Stone’s departure point.'],
  ['thirty-nine-steps','ruff','The Thirty-Nine Steps','The private staircase descending from Trafalgar Lodge to the beach.'],
]

export const characters = [
  ['hannay','Richard Hannay',[], 'A thirty-seven-year-old mining engineer from Rhodesia, physically capable, observant, and hungry for purposeful action.','#8a6745'],
  ['scudder','Franklin P. Scudder',[], 'An American freelance intelligence agent whose investigations uncover a European conspiracy.','#596f75'],
  ['paddock','Paddock',[], 'Hannay’s taciturn servant and former acquaintance from the Selakwe.','#77685c'],
  ['milkman','The Milkman',[], 'A young London milkman willing to assist an unexplained wager for a sovereign.','#8b8271'],
  ['innkeeper','The Literary Innkeeper',[], 'A young Galloway innkeeper and aspiring writer who longs for extraordinary experience.','#6f7453'],
  ['sir-harry','Sir Harry',[], 'A good-hearted young landowner and parliamentary candidate whose judgment is stronger than his speeches.','#765c42'],
  ['turnbull','Alexander Turnbull',[], 'An independent Galloway roadman whose reserve and practical charity protect Hannay.','#676052'],
  ['jopley','Marmaduke Jopley',[], 'A self-important former acquaintance of Hannay’s from South Africa.','#795e52'],
  ['old-man','The Old Man',[], 'A cultivated bald man with a young voice, hooded eyes, and formidable control over the conspiracy.','#454d50'],
  ['dark-man','The Dark Man',[], 'A lean, dark-eyed pursuer whose role grows increasingly urgent as June fifteenth approaches.','#4d4b48'],
  ['lisping-man','The Lisping Man',[], 'A sleek, smiling pursuer and exceptionally convincing actor.','#665d56'],
  ['sir-walter','Sir Walter Bullivant',[], 'A senior intelligence figure whose informal manner conceals disciplined judgment.','#485e69'],
  ['macgillivray','MacGillivray',[], 'A precise Scotland Yard official who directs the police response.','#445563'],
  ['karolides','Constantine Karolides',[], 'The Greek statesman whose survival matters to the European balance of power.','#6c6260'],
  ['royer','Royer',[], 'A French general entrusted with confidential Anglo-French military arrangements.','#4e6074'],
  ['drew','Sir Arthur Drew',[], 'The War Minister attending the secret conference at Queen Anne’s Gate.','#6d5d50'],
  ['winstanley','General Winstanley',[], 'A senior general present when the Black Stone penetrates the conference.','#5d6255'],
  ['whittaker','Whittaker',[], 'An Admiralty official responsible for the naval dispositions discussed with Royer.','#4b6171'],
  ['alloa-impostor','The Alloa Impostor',[], 'A spy whose perfect assumption of a familiar public figure carries him into the conference.','#52505b'],
  ['coastguard','The Coastguard Inspector',[], 'A retired-looking coastguard authority whose memory of the east coast solves the clue.','#486774'],
  ['scaife','Scaife',[], 'MacGillivray’s trusted officer, sent with Hannay to organize the Bradgate operation.','#4c5a51'],
]

export const items = [
  ['notebook','Scudder’s Black Notebook','The coded pocket-book containing Scudder’s evidence and final coastal clue.','book'],
  ['knife','The Long Knife','The weapon left through Scudder’s heart in Hannay’s smoking room.','sword'],
  ['gold-belt','Hannay’s Gold Belt','A money belt holding fifty pounds in sovereigns for Hannay’s flight.','coins'],
  ['bradshaw','Bradshaw Railway Guide','The timetable Hannay uses to select the northbound train.','book'],
  ['milkman-clothes','Milkman’s Cap and Overall','The borrowed work clothes that carry Hannay past the watchers.','armor'],
  ['sir-harry-letter','Sir Harry’s Letter','The introduction asking Sir Walter to receive a man calling himself Twisdon.','scroll'],
  ['roadman-kit','Turnbull’s Roadman Kit','Spectacles, hat, hammer, and barrow used in Hannay’s most successful disguise.','tool'],
  ['jopley-car','Jopley’s Touring Car','The motorcar Hannay commandeers to escape the road cordon.','vehicle'],
  ['lentonite','Lentonite and Detonator','Mining explosive discovered in the Black Stone farm storeroom.','bomb'],
  ['tide-tables','Admiralty Tide Tables','The reference that matches high tide at the Ruff to Scudder’s 10:17 clue.','book'],
]
